### ISSUE TITLE
Where to place and how to place a lauch argument?

### ISSUE THREAD

**Issue by cacarasa** [LavaGang/MelonLoader#107]
--melonloader.agfvunity with this argument... how and where can I force melonloader to use a specific unity library?

thanks in advance

**Comment by HerpDerpinstine** [comment]
The same place you add Game launch options.
If its on Steam for example you add it in the Properties of the Game.

**Comment by cacarasa** [comment]
can you give me an example... i need the game to load with the unity libraries version 2020.3.4

i tried without success this way, in the shortcut of the game:
"D:\Games\Hobo Tough Life\HoboRPG.exe"--melonloader.agfvunity 2020.3.4

thanks

**Comment by ds5678** [comment]
Here is a useful resource:
https://help.steampowered.com/en/faqs/view/7D01-D2DD-D75E-2955

**Comment by cacarasa** [comment]
> Here is a useful resource:
> https://help.steampowered.com/en/faqs/view/7D01-D2DD-D75E-2955

thanks but those arguments are different not for the melonloader....

**Comment by HerpDerpinstine** [comment]
> > Here is a useful resource:
> > https://help.steampowered.com/en/faqs/view/7D01-D2DD-D75E-2955
> 
> thanks but those arguments are different not for the melonloader....

Read what they linked.
Then go reread what I said.

> The same place you add Game launch options.
> If its on Steam for example you add it in the Properties of the Game.

Regardless of if the Launch Options are for the Game itself or for MelonLoader they both get added to the same location.
MelonLoader runs through the game, as does it's Launch Options.
Adding them to your Game **makes MelonLoader use them**.

**Comment by HerpDerpinstine** [comment]
> can you give me an example... i need the game to load with the unity libraries version 2020.3.4
> 
> i tried without success this way, in the shortcut of the game:
> "D:\Games\Hobo Tough Life\HoboRPG.exe"--melonloader.agfvunity 2020.3.4
> 
> thanks

I would also recommend that you **don't pirate games.**
We will not provide support for pirated games.
https://store.steampowered.com/app/632300/Hobo_Tough_Life/
