### ISSUE TITLE
Add Windows 11 to Core::GetOSVersion

### ISSUE THREAD

**Issue by slxdy** [LavaGang/MelonLoader#117]
Add Windows 11 to Core::GetOSVersion

**Comment by nitrog0d** [comment]
IsWindows11OrGreater doesn't exist yet

**Comment by slxdy** [comment]
> IsWindows11OrGreater doesn't exist yet

Ik, thats why I created this feature request...

**Comment by HerpDerpinstine** [comment]
Could maybe add it ourselves using a manual build version check.

**Comment by HerpDerpinstine** [comment]
I left my test IsWindows11OrGreater function in this commit and it turns out it works.
https://github.com/LavaGang/MelonLoader/commit/fb29ff56ffd2e26649eef366145b3df1c51cd560

Marking this issue as Completed.

**Comment by slxdy** [comment]
Nice
