### ISSUE TITLE
MelonLoader fails to locate mono if the game dir is the root of a drive

### ISSUE THREAD

**Issue by SamboyCoding** [LavaGang/MelonLoader#122]
This setup is most common within wine/proton environments where the game dir is mapped to be the D drive, etc. 

Mono::CheckLibName tries to check if base_path (which is, in this case, `D:`) exists, which it apparently doesn't (missing backslash? root of drive "doesn't exist" according to windows/wine/proton? who knows), and therefore fails, even though the rest of the method would succeed. 

This results in an Internal Failure thrown from Mono::SetupPaths because CheckFolderName returns an empty string for every folder.

I suggest simply removing the check for base_path existing and just bailing out if new_path doesn't exist, because clearly base_path must exist in all callers to this method, even if explicitly checking that fact says it doesn't.

**Comment by HerpDerpinstine** [comment]
Should be fixed but needs to be tested yet.
