### ISSUE TITLE
Whitelist `@` in symbol names

### ISSUE THREAD

**Issue by xKiraiChan** [LavaGang/MelonLoader#125]
The F# compiler creates symbols with `@` in the name. (Usually in static variables)
As a result, MelonLoader refuses to load any assemblies created in F# due to [AssemblyVerifier](https://github.com/LavaGang/MelonLoader/blob/master/Bootstrap/Managers/AssemblyVerifier.cpp#L20-L21) not whitelisting it.

**Comment by loukylor** [comment]
Mad lad
