### ISSUE TITLE
Fix Issue with Process.MainWindowTitle

### ISSUE THREAD

**Issue by HerpDerpinstine** [LavaGang/MelonLoader#135]
It was reported that Process.MainWindowTitle sometimes returns null.
It might be down to some Mono weirdness.
Need to patch this behavior.

**Comment by slxdy** [comment]
And how do you wanna patch this? Create your own mono fork lmao?

**Comment by HerpDerpinstine** [comment]
> And how do you wanna patch this? Create your own mono fork lmao?

Harmony patch the methods from C# and redirect to use native functions to poll the information...
