### ISSUE TITLE
Attempting to use a non-static harmony patch gives a cryptic error

### ISSUE THREAD

**Issue by SamboyCoding** [LavaGang/MelonLoader#138]
Using a non static prefix with HarmonyInstance.Patch throws the following cryptic error

```
[ERROR] Exception in Harmony patch of method void VRC.UI.PageWorldInfo::Method_Public_Void_ApiWorld_ApiWorldInstance_Boolean_Boolean_Boolean_APIUser_0(VRC.Core.ApiWorld param_1, VRC.Core.ApiWorldInstance param_2, bool param_3, bool param_4, bool param_5, VRC.Core.APIUser param_6):
System.InvalidProgramException: Invalid IL code in (wrapper dynamic-method) VRC.UI.PageWorldInfo:DMD<VRC.UI.PageWorldInfo::Method_Public_Void_ApiWorld_ApiWorldInstance_Boolean_Boolean_Boolean_APIUser_0> (VRC.UI.PageWorldInfo,VRC.Core.ApiWorld,VRC.Core.ApiWorldInstance,bool,bool,bool,VRC.Core.APIUser): IL_0002: call      0x00000001
```

Needs to be investigated - if it's a fault in the harmony lib it needs to be reported upstream, if it's a fault in the il2cpp patching code, it needs to be fixed our side.

**Comment by Futuremappermydud** [comment]
I feel like the error method should say harmony patch instead of just patched to make it a bit clear patch

**Comment by HerpDerpinstine** [comment]
> I feel like the error method should say harmony patch instead of just patched to make it a bit clear patch

Currently as of the latest commit it is set to say ``Patch Method must be a Static Method!``

**Comment by Futuremappermydud** [comment]
Yes thats what im referring to

> > I feel like the error method should say harmony patch instead of just patched to make it a bit clear patch
> 
> Currently as of the latest commit it is set to say `Patch Method must be a Static Method!`
