### ISSUE TITLE
[StartScreen:AnimatedImage] Implement Custom Animated Image Loading and Parsing

### ISSUE THREAD

**Issue by Slaynash** [LavaGang/MelonLoader#145]
Some games are missing the `System.Drawing` library, making the start screen fails to load.
Some of the ways to fix this are:
 - Use an homemade way to load images, without `System.Drawing`
 - Pack `System.Drawing` inside `MelonStartScreen.dll`

**Comment by slxdy** [comment]
Doesn't this lib come with the MelonLoader\Manager folder tho? You could just load missing assemblies from there tbh

**Comment by Slaynash** [comment]
> Doesn't this lib come with the MelonLoader\Manager folder tho? You could just load missing assemblies from there tbh

`MelonLoader/Managed` isn't loaded on Mono games

**Comment by slxdy** [comment]
> > Doesn't this lib come with the MelonLoader\Manager folder tho? You could just load missing assemblies from there tbh
> 
> `MelonLoader/Managed` isn't loaded on Mono games

Ik, but you can load the assembly from there, that's what I'm saying.

**Comment by HerpDerpinstine** [comment]
> > > Doesn't this lib come with the MelonLoader\Manager folder tho? You could just load missing assemblies from there tbh
> > 
> > 
> > `MelonLoader/Managed` isn't loaded on Mono games
> 
> Ik, but you can load the assembly from there, that's what I'm saying.

Older Mono is a factor here.
The ``System.Drawing.dll`` included is specifically designed for MonoBleedingEdge.
Not only that its built with a high .NET version limiting compatibility there as well.

Also there is the matter of Mono based DLLs can have a specific setup tuned to the running domain its under.
Externally they may look the same but that is for that user familiarity and resolving compatibility.
Underneath internally the Mono DLLs could be doing something different from their normal .NET Framework counterpart.

A drag and drop solution isn't viable.
