### ISSUE TITLE
Remove ZIP Loading Functionality

### ISSUE THREAD

**Issue by HerpDerpinstine** [LavaGang/MelonLoader#156]
It is hardly used and only causes more issues for the end user to have it load Plugins and Mods from ZIP Archives.
Should remove this and instead throw an error if the file type isn't in the compatible list of extensions.

| Extension |
| - |
| .dll |
| .txt |
| .json |
| .xml |
| .mdb |
| .pdb |
| .md |

**Comment by SlidyDev** [comment]
Did you srsly need to make a fuckin issue for this

**Comment by HerpDerpinstine** [comment]
> Did you srsly need to make a fuckin issue for this

Yes.
This is exactly what the Issues page is for.
Make it an issue and mark it on the Projects page for a to-do list.
