### ISSUE TITLE
TLS Bridging Failure on Unity 2018.1.0 x64 Il2Cpp

### ISSUE THREAD

**Issue by Zero-G-Sys** [LavaGang/MelonLoader#159]
I'm having an error while opening a game with melon loader 0.5.2 when it tries to initialize and contact the remote API. Seems to be a TLS connection problem, as said in the title I'm on Windows 7.
Following [this page](https://support.site24x7.com/portal/en/kb/articles/how-to-check-if-tls-1-2-is-enabled), I added the registry keys and have the KB update installed, but it still gives the same error.
Log: **[REDACTED]**

**Comment by HerpDerpinstine** [comment]
```
[00:45:47.204] Failed to Bridge Mono TLS! Web Connection based C# Methods may not work as intended.
```
This isn't an issue with Windows 7.
It is an issue with that build of Il2Cpp missing the TLS Adapter Export needed to bridge TLS.

**Comment by HerpDerpinstine** [comment]
Changing these to Planned until further work can be done.
