### ISSUE TITLE
[Bug]: Internal Failure when I try to install.

### ISSUE THREAD

**Issue by iyurwnn** [LavaGang/MelonLoader#173]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Whenever I try to install MelonLoader on to BONEWORKS it just says internal failure and makes a .txt file in my downloads
[MLInstaller_22-1-18_13-38-40.771.log](https://github.com/LavaGang/MelonLoader/files/7892559/MLInstaller_22-1-18_13-38-40.771.log)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Make sure you are using the latest installer.

**Comment by HerpDerpinstine** [comment]
> ### All of the following criteria must be met
> * [x]  All [Requirements](https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements) must be installed.
> * [ ]  Full `Latest.log` file included. If no file exists then leave this unchecked and state so.
> 
> ### All of the following are optional to answer
> * [x]  Tried reinstalling the Game.
> * [x]  Tried reinstalling MelonLoader.
> * [x]  Tried restarting PC.
> * [ ]  Was able to see the Start Screen.
> 
> ### Describe the issue.
> Whenever I try to install MelonLoader on to BONEWORKS it just says internal failure and makes a .txt file in my downloads [MLInstaller_22-1-18_13-38-40.771.log](https://github.com/LavaGang/MelonLoader/files/7892559/MLInstaller_22-1-18_13-38-40.771.log)
> 
> ### Did you attach your log file?
> * [ ]  Yes, I attached my log file to the text box above.
> * [x]  No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

Is this solved?

**Comment by HerpDerpinstine** [comment]
If no response is given in the next 24 hours I am going to assume this is solved and close the post.
