### ISSUE TITLE
[Bug]: INTERNAL FAILURE!

### ISSUE THREAD

**Issue by Fanixtar** [LavaGang/MelonLoader#174]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/7909650/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by nitrog0d** [comment]
I'm pretty sure MelonLoader doesn't support "BattleBit", according to the logs

**Comment by Fanixtar** [comment]
> I'm pretty sure MelonLoader doesn't support "BattleBit" according to the logs, more like the game was blacklisted to stop cheaters from using MelonLoader to cheat

well idk about that, it was working yesterday

**Comment by werewolf26** [comment]
It look like can't download at the files for it

**Comment by nitrog0d** [comment]
yeah that's what I'm saying the game probably got blacklisted from MelonLoader from yesterday to today, it's not an issue.

**Comment by loukylor** [comment]
BattleBit appears to be a (somewhat) competitive online game and we thus cannot help you mod it as MelonLoader could easily be utilized to cheat with.
