### ISSUE TITLE
[Bug]: error when starting BONEWORK with MelonLoader latest version.  thank you

### ISSUE THREAD

**Issue by maxguy** [LavaGang/MelonLoader#175]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/7918115/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
In Windows, click the Start menu and type in "Proxy" and click the result "Change Proxy".
Disable all 3 toggles in the image below:

![image](https://user-images.githubusercontent.com/8241943/150634960-505824a0-f23a-4c85-83f9-8495d4661723.png)

**Comment by HerpDerpinstine** [comment]
> ### All of the following criteria must be met
> * [x]  All [Requirements](https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements) must be installed.
> * [x]  Full `Latest.log` file included. If no file exists then leave this unchecked and state so.
> 
> ### All of the following are optional to answer
> * [ ]  Tried reinstalling the Game.
> * [x]  Tried reinstalling MelonLoader.
> * [ ]  Tried restarting PC.
> * [ ]  Was able to see the Start Screen.
> 
> ### Describe the issue.
> [Latest.log](https://github.com/LavaGang/MelonLoader/files/7918115/Latest.log)
> 
> ### Did you attach your log file?
> * [x]  Yes, I attached my log file to the text box above.
> * [ ]  No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

Is this solved?

**Comment by HerpDerpinstine** [comment]
If no response is given in the next 24 hours I am going to assume this is solved and close the post.
