### ISSUE TITLE
[Bug]: unable to vr , unable to connect

### ISSUE THREAD

**Issue by orcun9988** [LavaGang/MelonLoader#182]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

Hi, I'm using melonloader for a mod I made for a game, everything continues to work without problems, but I'm getting errors like this on the console screen.

i have tried all versions of melon loader v4.3 and higher and I have received this error in all of them.

i just don't encounter this error in version 2.7.4.

to solve this problem, I tried deleting the bhaptics dll file located in the melonloader/Dependencies folder, but it didn't matter.

Unable to read VR Path Registry from C:\Users\Whis\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Whis\AppData\Local\openvr\openvrpaths.vrpath
Unable to connect to 127.0.0.1:15881
Unable to connect to 127.0.0.1:15881
Unable to connect to 127.0.0.1:15881
Unable to connect to 127.0.0.1:15881
Unable to connect to 127.0.0.1:15881

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
If everything continues to work then please provide the ``Latest.log`` file.
