### ISSUE TITLE
[Enhancement]: Load Native Libraries from the UserLibs Directory

### ISSUE THREAD

**Issue by slxdy** [LavaGang/MelonLoader#185]
### Describe the new feature or enhancement

Some Melons may depend on native libraries and should have a directory where they can store those dependencies.
While I understand you can just tell the user to put the library into Unity's Plugins folder, I feel like Melons should still store all their dependencies in MelonLoader-generated directories.

**Comment by HerpDerpinstine** [comment]
~Requires #153 before this can be done.~

**Comment by HerpDerpinstine** [comment]
This should now be Resolved in v0.6.6
