### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by An1g13** [LavaGang/MelonLoader#208]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

When I opened Vrchat I opened Steam to login and I kept clicking Steam to login but it never worked so I restarted my pc and reopened Vrchat and Steam nothing ever worked.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
I am closing this and marking it as invalid.
You provided very little information about the issue or what you are trying to do.
Not only that if you can see the MelonLoader Start Screen then there is a log file which you did not attach.
