### ISSUE TITLE
Offline dependencies please

### ISSUE THREAD

**Issue by PIndividual** [LavaGang/MelonLoader#209]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Every time I start a game there is a prompt that looks like this appears:
![image](https://user-images.githubusercontent.com/62368342/157211514-f956a014-d9df-41b4-b313-6a6b14abf2b6.png)
Maybe an offline version that allows users to manually download could help
[Latest.log](https://github.com/LavaGang/MelonLoader/files/8204762/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Try installing the x64 release build from https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development
You can do so by using the Manual Zip tab on the installer.
See if the same issue occurs.

**Comment by PIndividual** [comment]
Well, I tried, now the game won't even open :( the command prompt windows flashes and then automatically shuts down itself

**Comment by HerpDerpinstine** [comment]
> Well, I tried, now the game won't even open :( the command prompt windows flashes and then automatically shuts down itself

Apparently there was a crash issue with the Alpha branch of MelonLoader.
The crash issue should now be resolved.
Please download this [MelonLoader.x64.CI.Release.zip](https://github.com/LavaGang/MelonLoader/suites/5602313269/artifacts/181950677) and try again.

**Comment by PIndividual** [comment]
Well, seems like using manual zip install still leads to this situation:
![image](https://user-images.githubusercontent.com/62368342/157784728-37acd769-5002-4037-b116-37ffbe1d8c34.png)

**Comment by PIndividual** [comment]
Problem solved, by looking at what the console shows, I manually fill in the missing files and the game now boots  normally, thanks XD
