### ISSUE TITLE
[Question]: Regarding the Development branch of Master.

### ISSUE THREAD

**Issue by LordBongski** [LavaGang/MelonLoader#219]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Is there a specific reason as to why none of the Development branches of Master are no longer available for public view? in the past this has been public.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
The [alpha-development](https://github.com/LavaGang/MelonLoader/tree/alpha-development) branch still exists and is publicly viewable.
Locking this post for being invalid.
