### ISSUE TITLE
[Bug]: Crash/Game not responding. x86, Mono, Unity 5.3.4

### ISSUE THREAD

**Issue by gompoc** [LavaGang/MelonLoader#220]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/8344062/Latest.log)
Crashes or freezes the game while loading. Can sometimes give an empty message box (as seen below) other times just nothing.
![image](https://user-images.githubusercontent.com/91314780/159976825-60e2d6da-8fa3-495b-8970-247176c45f51.png)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
This is now fixed in the latest alpha-development nightly build.
