### ISSUE TITLE
[Bug]:  NO SUPPORT MODULE LOADED

### ISSUE THREAD

**Issue by IT-AINT-GOT-NO-GAS-IN-IT** [LavaGang/MelonLoader#222]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

ERROR NO SUPPORT MODULE LOADED
![fbds](https://user-images.githubusercontent.com/102868264/161390282-9a714c7e-d2ae-4c18-9343-6108b7983140.PNG)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Maybe attach the file itself instead of a screenshot

**Comment by HerpDerpinstine** [comment]
Marking this as invalid.
You have provided only a screenshot and not the actual log file as requested.
