### ISSUE TITLE
[Bug]: Failed to download Cpp2IL

### ISSUE THREAD

**Issue by matidfk** [LavaGang/MelonLoader#223]
### All of the following criteria must be met

- [x] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/8443158/Latest.log)

It seems that the version its looking for (2022.9.9) doesnt exist

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Working as intended. Stop trying to ruin people's experience.
