### ISSUE TITLE
[Bug]: Failed to download 

### ISSUE THREAD

**Issue by Sockwearer2** [LavaGang/MelonLoader#229]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I download melon loader with all dependencies installed to run it. I run the game and it give me an error.

[MelonLoader_22-04-20_18-14-13.074.log](https://github.com/LavaGang/MelonLoader/files/8523743/MelonLoader_22-04-20_18-14-13.074.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Stop trying to cheat on crab game
