### ISSUE TITLE
[Enhancement]: Native MacOS Support

### ISSUE THREAD

**Issue by Lincoln-Muller** [LavaGang/MelonLoader#230]
### Describe the new feature or enhancement

While Unity supports MacOS and Linux building, melonloader only supports Windows. Would it be possible to get a native Mac Version without messing around with wine?

Or, in the meantime, is it possible to use MelonLoader with Wine? I have tried it myself, but when I install it (with the automated installer, or manually), the game just launches normally, no MelonLoader screen appears.\

Perhaps I am missing a library required to run Melonloader?

Thanks,

Lincoln

**Comment by SamboyCoding** [comment]
MelonLoader does work with wine, yes. There are some instructions for linux here, but generally the same thing should work on mac: https://github.com/RinLovesYou/VRChat-Linux/wiki/Modding. Note it says VRChat but the same steps should work for any game, though you'll have to replace `438100` with the AppID of your game.

**Comment by Lincoln-Muller** [comment]
@SamboyCoding Thanks!

Successfully got it working with Crossover.
