### ISSUE TITLE
[crash]: 

### ISSUE THREAD

**Issue by Nikopabeer** [LavaGang/MelonLoader#231]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Townscaper Little First Perons Mod and ModUI dosen't work, Loader/game crashes instantly.
![Screenshot 2022-04-21 160112](https://user-images.githubusercontent.com/103966921/164474881-a2e53893-6d99-4253-a1a5-dcc27b78204f.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by loukylor** [comment]
I believe that error is caused by an invalid assembly of some kind in a mod. I don't think it's a MelonLoader issue.

Have you tried loading the game without any mods in the Mods folder?

**Comment by HerpDerpinstine** [comment]
Marking this as invalid and locking it.
Issues posts should include the log file when checked off, not a screenshot of the console.
Also this post has gone 10-11 days with no response.

**Comment by Nikopabeer** [comment]
My mistake, attach the log data next time.

Without mods everything loads, have also tried each mod individually. Seems to be due to the ModUi mod.
