### ISSUE TITLE
[Bug]: Flagged by antivirus (Bitdefender)

### ISSUE THREAD

**Issue by Azimuth037** [LavaGang/MelonLoader#232]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Bitdefender antivirus flags MelonLoader files as infected and automatically quarantines them. Unsure if this is repeatable with other antivirus software such as Malwarebytes or McAfee, but it became a recurring issue for me.
[MelonLoader_22-04-22_00-07-02.851.log](https://github.com/LavaGang/MelonLoader/files/8536750/MelonLoader_22-04-22_00-07-02.851.log)
 

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
An issue with your antivirus isn't really an issue with our software. Additionally, this only happens with antivirus software known to be of poor quality, including Bitdefender, Webroot, Avast, etc.

**Comment by IR3v0I** [comment]
Well it kinda is, had that issue with an update for hunt showdown once, made by crytek... and now my F-Secure is removing the "VRChat\MelonLoader\Dependencies\ll2CppAssemblyGenerator\Cpp2IL\cpp2il_out" file every time I run melonloader, have to turn of F-Secure to be able to run and cant turn back on while running, will instantly remove the file and crash vrchat. And F-Secure is at least not a free antivirus...
Edit: v0.5.4 is causing this wasn't with 5.3

**Comment by SamboyCoding** [comment]
0.5.4 uses an updated version of cpp2il compared to 0.5.3, which may be why it's only occurring on that version. However, to give you some idea of how over-the-top your AV is being, the dll files generated by cpp2il, at least in the configuration melonloader uses it in, *do not contain any code*. So your "antivirus" is literally removing empty files. So I'd classify that as "of poor quality".

**Comment by Azimuth037** [comment]
I have not seen Bitdefender do this with anything else at all. The software from my experience ranks more highly than others like Avast or AVG and has never suddenly decided to flag any 'empty files' before during my use (even when I intentionally tried to get it to.)

**Comment by SamboyCoding** [comment]
The code to generate those dll files is open-source (it's on my github profile), so you can verify for yourself - or get someone else to - that there is zero executable code actually emitted to them. I'm not going to go crying round to all the AV manufacturers who decide to block the empty files I produce, asking them to unblock them, because there are literally hundreds of possible files and variants depending on unity version etc.

**Comment by Azimuth037** [comment]
Look, I was trying to bring this to your attention because it seemed like an issue. If you don't want to treat it like its your problem thats your decision.

**Comment by slxdy** [comment]
> Look, I was trying to bring this to your attention because it seemed like an issue. If you don't want to treat it like its your problem thats your decision.

It's not even his problem... How is it his problem if the software YOU downloaded is messing with HIS software?

**Comment by Azimuth037** [comment]
Because its HIS software being flagged by not one but multiple antivirus softwares. I just thought attention might want to be brought to it was all.

**Comment by Azimuth037** [comment]
Listen this is just something interesting I thought I'd bring attention to. Didn't expect everyone to suddenly feel like crusading because of it.

**Comment by slxdy** [comment]
> Because its HIS software being flagged by not one but multiple antivirus softwares. 

So? Again, how is this HIS problem?

**Comment by slxdy** [comment]
> Listen this is just something interesting I thought I'd bring attention to. Didn't expect everyone to suddenly feel like crusading because of it.

We have had enough issues like this
