### ISSUE TITLE
[Bug]:  Exception while Contacting RemoteAPI Host

### ISSUE THREAD

**Issue by lmaodick1239** [LavaGang/MelonLoader#237]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

exception thrown on startup
latest.log :https://pastebin.com/He3drkFT
thats all i know

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
The latest release of MelonLoader has been recently removed from GitHub for an unknown reason and you're running an older version of MelonLoader. Please install MelonLoader manually from https://github.com/LavaGang/MelonLoader/releases/tag/v0.5.4

If you don't know how to manually install MelonLoader, refer to https://github.com/LavaGang/MelonLoader.Installer/blob/master/README.md#manual-zip

**Comment by slxdy** [comment]
Update: The latest release is back. You can simply reinstall MelonLoader using the official installer to fix your issue

**Comment by lmaodick1239** [comment]
now i got it to work. but i had to do it manually by downloading all the github files manually by getting the urls and the locations from the logs. it seems  like all my webclient requests are all aborted(?) for some reason
