### ISSUE TITLE
[Bug]: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by lmaodick1239** [LavaGang/MelonLoader#238]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/8695410/Latest.log)
all of the web requests turn back null and my game wont boot

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
![image](https://user-images.githubusercontent.com/61495410/168484341-3946c0b6-d6ee-4d29-ad34-d137fb06b141.png)

**Comment by lmaodick1239** [comment]
> ![image](https://user-images.githubusercontent.com/61495410/168484341-3946c0b6-d6ee-4d29-ad34-d137fb06b141.png)

thanks,it also seems as if i use a vpn the web requests also work
