### ISSUE TITLE
[Bug]: Inconsistent crashing - "SIGSEGV" error

### ISSUE THREAD

**Issue by Xrayxout** [LavaGang/MelonLoader#239]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Been making a mod and sometimes, would randomly see the game crash and going to check the logs that Melon generates, it would show no details of a crash. just my mod completing it's function and that's it. but i managed to copy and paste the entire CMD window before it crashed and discovered a "Got a SIGSEGV while executing native code" error. i sent this issue in the MelonLoader discord and was told to try running the game with the "--melonloader.disablestartscreen" launch command and the issue did not go away. if anymore info is needed lemme know

[Copied from window.log](https://github.com/LavaGang/MelonLoader/files/8695848/Copied.from.window.log)
 

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by loukylor** [comment]
It doesn't make sense for the game to crash after your mod manages to finish some init stuff after a fatal error. If the fatal error is what is actually causing the crash then the game would likely crash before your mod initializes. It also doesn't make sense for Synth Riders to be crashing, for, as far as I know, it is supported by MelonLoader just fine.

Does your game still crash without your mod in the Mods folder? If it doesn't try to get help debugging it in the MelonLoader Discord.

**Comment by Xrayxout** [comment]
it doesn't crash with no mods. will try debugging with the discord

**Comment by Xrayxout** [comment]
I debugged it using DNSpy and got this. does this help?

[Output-Debug.txt](https://github.com/LavaGang/MelonLoader/files/8696116/Output-Debug.txt)

**Comment by HerpDerpinstine** [comment]
> it doesn't crash with no mods. will try debugging with the discord

If it doesn't crash without mods but crashes with mods, the problem is most likely the mods.

**Comment by Xrayxout** [comment]
After trying with a universal mod, the same type of error appears as well but it describes different reason for it. the game would continue but it would eventually bug out and crash or become unplayable. how do we even diagnose these with mod creators? how do we go about fixing it if it's our fault?

here is the log with just Unity Explorer
[Unity Explorer same type of error.txt](https://github.com/LavaGang/MelonLoader/files/8697158/Unity.Explorer.same.type.of.error.txt)

**Comment by loukylor** [comment]
Can you [verify game files](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB)? There looks to be some weirdness with one of the game files, or a MelonLoader bug. It's most likely some weirdness though.

**Comment by Xrayxout** [comment]
I am not on Steam i am on Oculus. but i reinstalled it and still same issue

**Comment by SlidyDev** [comment]
Which game are we talking about here in the first place?

**Comment by Xrayxout** [comment]
I have found and fixed the issue. turns out a Timer() function was causing inconsistent results and causing the game to crash. thanks for the help :)
