### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by eterlan** [LavaGang/MelonLoader#244]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Hi! After trying hours to find out problem vainly, want some help from you guys.. Do you have any idea about that?
Seems like clearing console fails due to reflection fails.. 

![@9$)K375`YLTG)0Y8P XO2F](https://user-images.githubusercontent.com/37736673/169570326-ea873536-f84d-4824-9ff0-9e07802d0cd2.png)
[MelonLoader_22-05-20_23-36-58.500.log](https://github.com/LavaGang/MelonLoader/files/8741904/MelonLoader_22-05-20_23-36-58.500.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Well, you're kinda out of luck in this case because
1. Your system language is using an alphabet that the logger fails to log properly (so we can't read the error messages)
2. The console cleaner issue is the last thing you should be worrying about because the Il2CppUnhollower is failing, and you're not gonna be able to do anything without that

**Comment by eterlan** [comment]
> Well, you're kinda out of luck in this case because
> 
> 1. Your system language is using an alphabet that the logger fails to log properly (so we can't read the error messages)
> 2. The console cleaner issue is the last thing you should be worrying about because the Il2CppUnhollower is failing, and you're not gonna be able to do anything without that

Thanks for your reply! I found out it's unity's fault, just write something and recompile then problem is solved.. Hope you have a nice day!

**Comment by slxdy** [comment]
huh
