### ISSUE TITLE
[Bug]: Failed to get SHA512 Hash from Repo!

### ISSUE THREAD

**Issue by Goosypie** [LavaGang/MelonLoader#247]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Whenever I try to do it on BTD6 it just doesn't.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
This issue is invalid. You haven't tried any of the solutions mentioned in the issue template, nor have you described your issue well.
