### ISSUE TITLE
[Bug]: INTERNAL FAILURE？？？？

### ISSUE THREAD

**Issue by LLLL640** [LavaGang/MelonLoader#248]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

display 
 [00:04:14.249] [INTERNAL FAILURE] Failed to Find Mono Library!

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Try reinstalling your game

**Comment by LLLL640** [comment]
您好！
   很高兴收到您的邮件！我会尽快查收，查看后会尽快回复您！谢谢！祝好！

**Comment by slxdy** [comment]
bruh

**Comment by LLLL640** [comment]
Reinstallation is useless

**Comment by Gen-LLL** [comment]
Did you solve this problem? I meet the same error.
