### ISSUE TITLE
[Bug]: Software problems

### ISSUE THREAD

**Issue by LLLL640** [LavaGang/MelonLoader#250]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

At present, it is still in version 2.6 of, but the overwrite error and some other errors are displayed. Is there any way to solve it?
![搜狗截图22年06月07日1815_1](https://user-images.githubusercontent.com/106987255/172356456-b0a9222e-b7ea-4bbc-aa3d-f58d630c9f30.png)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
1. That's a modified version of MelonLoader
2. MelonLoader does not have native support for Genshin's modified engine

**Comment by slxdy** [comment]
3. Stop creating those issues; you literally won't find help here with Genshin
