### ISSUE TITLE
[Bug]: Failed to Open Mono Assembly under Proton (old Unity versions?)

### ISSUE THREAD

**Issue by Hexcede** [LavaGang/MelonLoader#253]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I am currently trying to get MelonLoader working with a mono game using Unity version `2019.4.21f1` working under Proton. The game is 20 Minutes Till Dawn. I am having similar issues with all of the other Unity mono games I try.

I am presented with an error and a matching line in my log file: `[INTERNAL FAILURE] Failed to Open Mono Assembly!`

I followed the steps on the wiki for proton/wine installs and get a console window to appear, and I have enabled debug logs.

Here is my [Latest.log](https://github.com/LavaGang/MelonLoader/files/8886110/Latest.log).

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by Hexcede** [comment]
This issue is very likely related to improper dotnet config. For example, `mscoree.dll` is deleted when running `--force dotnet472` as the wiki suggests to do, which of course is required for MelonLoader to function, however wine's installer explicitly removes `mscoree.dll`. Perhaps installing a different compatible dotnet version after cancelling the installer may fix this issue.

**Comment by Hexcede** [comment]
I indeed confirmed this is the case. When using a fresh prefix, `CLR.dll` fails to be found by .NET programs like `dnSpy` (e.g. when trying to attach a debugger). After running any `--force dotnetXX` command, `mscoree.dll` is not re-created (dotnet didn't get installed because we skipped it since it won't function) so the program then can't find `mscoree.dll`.

This is a complex issue, and, I'm not sure the real cause or solution or what's changed to create this problem in the first place ☹️

**Comment by guoshuyan** [comment]
你可以看一下你是否使用了 ASCII 字符集以外的字符（比如汉字“开”）
You can check whether you use characters other than ASCII character set (such as Chinese character "开")

**Comment by RinLovesYou** [comment]
Hi there, I can not reproduce this.
![image](https://user-images.githubusercontent.com/29461788/196008057-925f3c10-a4c8-4e67-b718-af57d2d4430d.png)


I need to update the Wiki entry anyways, vcrun and dotnet are just not required for ML to run anymore

**Comment by Hexcede** [comment]
> Hi there, I can not reproduce this. ![image](https://user-images.githubusercontent.com/29461788/196008057-925f3c10-a4c8-4e67-b718-af57d2d4430d.png)
> 
> I need to update the Wiki entry anyways, vcrun and dotnet are just not required for ML to run anymore

Is this screenshot under Proton?

Based on your logs, the game's Unity version is now newer. The issue seemed to be specific to Unity version `2019.4.21f1` and possibly others. Whereas the game's Unity version in the screenshot you posted is `2019.4.40f1`. It's only a minor version difference, but I could previously confirm that the issue occurred under Proton Experimental with a fresh Unity project I compiled myself using specifically Unity version `2019.4.21f1`.

**Comment by RinLovesYou** [comment]
I really doubt that's a thing, but i'll install 2019.4.21f1 and make a demo project to test.

**Comment by RinLovesYou** [comment]
![image](https://user-images.githubusercontent.com/29461788/196046509-a60f909c-f0bc-4683-b38a-2318fda74dcc.png)

Aside from the start screen failing, i am still entirely unable to reproduce this issue
As i've mentioned before, you can skip `vcrun2019/dotnet472` and see if that resolves your issue? I've already submitted a pull request to the Wiki [here](https://github.com/LavaGang/MelonWiki/pull/66)

**Comment by HerpDerpinstine** [comment]
@Hexcede Was this resolved?

**Comment by Hexcede** [comment]
> @Hexcede Was this resolved?

I apologize, I've been super busy so I haven't had a chance to test/respond. I'll go ahead and test and follow up later today.
