### ISSUE TITLE
[Bug]: The code execution cannot proceed because VCRUNTIME140_1.dll was not found.

### ISSUE THREAD

**Issue by ibramaj** [LavaGang/MelonLoader#255]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I had this error opening melonloader

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by HerpDerpinstine** [comment]
That error only happens when you **don't have all the requirements installed**.

I am marking this post as invalid.
It is obvious you just checked a box without actually reading them.
