### ISSUE TITLE
[Bug]: Harmony is failing to initialize on some games [Nightly Build]

### ISSUE THREAD

**Issue by slxdy** [LavaGang/MelonLoader#261]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Compared to the latest release version, Harmony is failing to initialize on some games (such as Welcome To The Game II) now.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/9077831/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Duplicate Issue
More information posted on #275
