### ISSUE TITLE
[Bug]: Everytime i download other games there comes up a message that says "Proxy has been loaded by a Process that is not a Unity Game! Continuing without MelonLoader..." Its annoying pls fix :) 

### ISSUE THREAD

**Issue by JensErSej** [LavaGang/MelonLoader#263]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Everytime i download other games there comes up a message that says "Proxy has been loaded by a Process that is not a Unity Game! Continuing without MelonLoader..." Its annoying pls fix :) 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Go into your root Steam folder and remove `version.dll`

**Comment by slxdy** [comment]
And next time don't try installing MelonLoader on games through their shortcuts cuz the feature is kinda broken for some people
