### ISSUE TITLE
[Bug]: Cant delete melonloader from boneworks

### ISSUE THREAD

**Issue by Blunerz** [LavaGang/MelonLoader#266]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I deleted melonloader folders from the boneworks, and i have this issue (it crashes the game) (screenshot)
![image](https://user-images.githubusercontent.com/105878986/180418315-cf4ec39b-1551-4a6d-89cd-39589e8d0b25.png)
After that i reinstalled boneworks and i still have this

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Well your first mistake was trying to manually delete things.
You could have just used the installer to uninstall MelonLoader.
Either way delete ``version.dll`` to fix it.

**Comment by Blunerz** [comment]
thanks, someone on reddit told me to delete it manually
