### ISSUE TITLE
[Bug]: Failed to Initialize Assets Manager!

### ISSUE THREAD

**Issue by Cross2pro** [LavaGang/MelonLoader#267]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

Failed to Initialize Assets Manager! error when using MelonLoader in il2cpp game (Per Aspera).
And the Unity version was not recognized at first. After I manually added the parameter (--melonloader.agfvunity) and corrected it, Dumper seemed to be able to export correctly, but an error was reported when loading the mod.

[MelonLoader_22-07-22_22-08-08.415.log](https://github.com/LavaGang/MelonLoader/files/9168470/MelonLoader_22-07-22_22-08-08.415.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
As of this commit https://github.com/LavaGang/MelonLoader/commit/946d7add4b825ecbf9b6dd8b1da1b8009b91362b and the upcoming v0.5.5 update:
The ``--melonloader.agfvunity`` launch option has been replaced with ``--melonloader.unityversion``
``--melonloader.unityversion`` will now work properly for allowing the user to specify the Unity Version.
