### ISSUE TITLE
[Enhancement]: Support for Neos VR

### ISSUE THREAD

**Issue by SeyfertGames** [LavaGang/MelonLoader#269]
### Describe the new feature or enhancement

Neos VR fully supports modding, and there is even a Community Made NeosModLoader made for it. I was wondering if you could add MelonLoader support Neos VR. Currently, when you install it and run it it crashes on launch
[Latest.log](https://github.com/LavaGang/MelonLoader/files/9192497/Latest.log)

**Comment by loukylor** [comment]
Why would you need MelonLoader if the game already supports modding?

**Comment by SeyfertGames** [comment]
> Why would you need MelonLoader if the game already supports modding?

It does but It would be nice if MelonLoader was supported on Neos VR

**Comment by SeyfertGames** [comment]
What I mean is you need to install a 3rd party application to mod Neos VR. So if MelonLoader was one of those options people who are already familiar with MelonLoader and know how to create mods for it don't have to learn how to use a entirely different Mod Loader.

**Comment by HerpDerpinstine** [comment]
Give me some time and I will look into it.

**Comment by SeyfertGames** [comment]
> Give me some time and I will look into it.

did you figure out whats causing the issue with Neos VR?

**Comment by HerpDerpinstine** [comment]
This is now fixed in the latest alpha-development nightly build.
