### ISSUE TITLE
[Bug]: Chilloutvr hangs and wont shut down with Melonloader installed.

### ISSUE THREAD

**Issue by SquidNeko** [LavaGang/MelonLoader#273]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Bug]: Chilloutvr hangs and wont shut down with Melonloader installed.

Always have to forceclose Chillout when its installed.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Does this also happen without any mods installed?

**Comment by SquidNeko** [comment]
Hmm. Actually no. Probably the mod then.

**Comment by slxdy** [comment]
Then the issue is technically invalid

**Comment by HerpDerpinstine** [comment]
Marking as invalid.
Form wasn't filled out properly.

**Comment by slxdy** [comment]
That too
