### ISSUE TITLE
[Bug]: MelonLoader does not work with game "Dream Quest"

### ISSUE THREAD

**Issue by OU2018** [LavaGang/MelonLoader#280]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I tried to create a Chinese mod for the game dream quest, but an error in the log occurred when I added the melonloader and ran it in dnspy for the first time.
Dreamquest can be downloaded on steam, and the unity version used to make the game seems to be 4.6.5
I want to know whether it is because melonloader does not support unity of too low version or my operation error. Thank you for your help.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/9387326/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by nitrog0d** [comment]
For who's gonna look into this... It's a very old game made in 2014, Unity version is 4.6.5f1, AssetsTools.NET is failing, it only has the "mainData" file to read the game information
Here's a copy of it if the AssetsTools.NET dev wants to take a look: https://anonfiles.com/e9j3nd70yd/mainData

**Comment by HerpDerpinstine** [comment]
This is now fixed in the latest alpha-development nightly build.
