### ISSUE TITLE
[Bug]: Program AssemblyUnhollower.exe stopped working

### ISSUE THREAD

**Issue by Legoras** [LavaGang/MelonLoader#282]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Testes both versions - 5.4 and beta 5.5
[Latest.log](https://github.com/LavaGang/MelonLoader/files/9393002/Latest.log)

After shutting down AssemblyUnhollower.exe, game will continue to load.

When adding any Mod, shutting down AssemblyUnhollower.exe game will load but of course without working mod (no dependencies)
[Latest.log](https://github.com/LavaGang/MelonLoader/files/9393095/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
Do you have enough ram/space on your disk?

**Comment by Legoras** [comment]
Yes, 16GB ram, 779GB free space at M2 SSD
Game do not use more than 10gb of ram at first launch.

**Comment by nitrog0d** [comment]
Game works fine on latest commit from alpha-development, game version v0.7.5f
Unhollower was dying when scanning method cross-references
