### ISSUE TITLE
[Bug]: System.ArgumentOutOfRangeException Error

### ISSUE THREAD

**Issue by BobTheVirginGod** [LavaGang/MelonLoader#283]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

So the game is crashing and melonloader is showing this:
**[ERROR] Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.**

Now, the game probably has anti-melonloader because it crashes when it finds MelonLoader.dll even without it being injected.
I tried compiling the Melon Loader source and changing the MelonLoader.dll name to something else. This made me see the loading screen but the error above accurse.

Any help would me good, thanks :)

[log.log](https://github.com/LavaGang/MelonLoader/files/9423049/logs.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by loukylor** [comment]
The link to your log goes to a 404. Can you reattach it?

Also, what game is it? If it has anti-MelonLoader, it's there for a reason, and we will not help you bypass it.

**Comment by slxdy** [comment]
Yea no, invalid issue.

**Comment by BobTheVirginGod** [comment]
No need i fixed it by downloading the new version of Cpp2IL.
