### ISSUE TITLE
[Bug]: "System.BadImageFormatException: Invalid assembly" with non ascii class name

### ISSUE THREAD

**Issue by MeitziQ** [LavaGang/MelonLoader#288]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When using non ascii charter on class name (eg ä), MelonLoader will give you 
**[ERROR] Failed to Load Assembly for mod.dll: System.BadImageFormatException: Invalid assembly**
I think, at least it should be give better error if not supported.

Example MOD which will cause error. (removing ä will fix it) 
```
using MelonLoader;
[assembly: MelonInfo(typeof(MelonTest.Main), "MelonTest", "0.1")]
namespace MelonTest {
    public class Main : MelonMod {
        public override void OnApplicationStart() {
            MelonLogger.Msg("Hi from my mod!");
        }
    }
    public class Ryhmä { //This ä will cause System.BadImageFormatException: Invalid assembly
        public void something_more() { }
    }
}
```

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SlidyDev** [comment]
Right, and what version are you using?

**Comment by MeitziQ** [comment]
Running public version, so its v0.5.4

**Comment by nitrog0d** [comment]
I think this is because MelonLoader stops obfuscated assemblies from loading in and that was flagged

**Comment by HerpDerpinstine** [comment]
Intended behavior by the obfuscation detection.
