### ISSUE TITLE
[Bug]: Console waits for input

### ISSUE THREAD

**Issue by MeitziQ** [LavaGang/MelonLoader#289]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Its quite easy to get console some kind of "waiting for input" state even by accident.
There are cases, where user think game is crashed or halted even its not.

Steps to re-produce:
1. Start any game with MelonLoader default settings (console is visible) 
2. "Draw" some text on console with your mouse. 

Result:
**Game will stop running.**

Expected result:
**Game should run, regardless of console input / output.** 

Example: 
![console](https://user-images.githubusercontent.com/16046000/189631187-03124c1b-951f-492d-85d1-d4fec68d688a.PNG)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
You do realise that that's a normal cmd.exe feature, right? It has nothing to do with ML

**Comment by MeitziQ** [comment]
I am not cmd expert.
Original game does not use cmd at all, so this is caused by melon.
And of course, it’s possible this is not bug, it a design flaw.


This breaks my “on all possible cases, allow original game run normally” rule, so its somewhat annoying.

**Comment by slxdy** [comment]
> it’s possible this is not bug, it a design flaw.

Then it's not on our end, but Microsoft's

**Comment by nitrog0d** [comment]
Just right click the console to let it go. This is a cmd thing and not caused by MelonLoader, it's a cmd feature that pauses for you so you can select text

**Comment by HerpDerpinstine** [comment]
That is a feature of cmd and you can disable that yourself by going to the command prompt settings.
There is no good way to disable that in code without it getting in the way of development.
Closing this issue.
