### ISSUE TITLE
[Bug]: MelonLoader does not work with game "Eleven Table Tennis"

### ISSUE THREAD

**Issue by yrichard6208** [LavaGang/MelonLoader#292]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I have reported this issue previously at [here](https://github.com/LavaGang/MelonLoader/issues/270), the issue was marked as Completed and Closed, but it seems still does not work for me. I have attached the latest log here. 

The game is able to run, but the problem is that mod seems does not work. 

I have tried the sample MelonLoader mod, none of callbacks are working.

[MelonLoader_22-09-15_20-39-52.063.log](https://github.com/LavaGang/MelonLoader/files/9579735/MelonLoader_22-09-15_20-39-52.063.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
That issue is marked closed because that specific issue has already been fixed in the upcoming update.
Please wait for it to release.
