### ISSUE TITLE
[Bug]: Game Crashing when Failing to read Game Info

### ISSUE THREAD

**Issue by MeitziQ** [LavaGang/MelonLoader#294]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

_Car Mechanic Simulator 2021_ Steam
After game got update, with Unity version from 2020.3.32 to 2020.3.38 (maybe related, maybe not)
MelonLoader is no longer able to load game base assembly file. 

With MelonLoader version 0.5.3 you will see:
[DEBUG] Initializing Base Assembly...
[DEBUG] [MonoLibrary] Setup Successful!
[DEBUG] [MonoResolveManager] Setup Successful!

With MelonLoader version 0.5.4 or 0.5.5 (here its from 0.5.5)
[DEBUG] Initializing Base Assembly...
[ERROR] System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

[Latest.log v0.5.5](https://github.com/LavaGang/MelonLoader/files/9600719/Latest.log)
[Latest.log ok v0.5.3](https://github.com/LavaGang/MelonLoader/files/9600723/Latest.log)

Two ways to test this:
1. Demo or real game from [Steam](https://store.steampowered.com/app/1190000/Car_Mechanic_Simulator_2021/) (demo is older version, but its seems get exact same error)
2. Only [game assembly dll](https://1drv.ms/u/s!Anf_vIbyhTaYlWRTLa9opizogUkq?e=YKayw4)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
ML failed to read the game info, but that wont affect mods

**Comment by MeitziQ** [comment]
I disagree.

When MelonLoader does load game info correctly, mods works.
When it does not, its says what is on title and "Failed to Initialize Assets Manager!" and game crash. 

These are current facts:
Game works with MelonLoader v0.5.3
Game does not work with MelonLoader v0.5.4 nor v0.5.5
Previous version of game, did work with MelonLoader v0.5.4

with version 0.5.4 you get  first System.IO.EndOfStreamException and System.OutOfMemoryException then "Failed to Initialize Assets Manager!"
and these affect so that game crash or quit. (not sure if it crash or just someone give up) 

In theory, it of course possible that first error what you say, only error that it cant read something. However, its seems highly unlikely first error is not related to this issue. 

Should I change the title to this "Failed to Initialize Assets Manager!" and focus on that? 
Does Initialize Assets Manage need any game info ?

[Latest (1).log](https://github.com/LavaGang/MelonLoader/files/9601221/Latest.1.log)

**Comment by slxdy** [comment]
Also, 0.5.5 should not give you the error. As long as it has the Unity version, everything should be fine

**Comment by MeitziQ** [comment]
With version v0.5.5 Open-Beta there is no longer any errors. Game just crash before it can fully start. 

Should I make a new bug report with that info, or add log file here? 
I think, reading Game Info bug is fixed, however, it seems maybe crashing bug is different.

**Comment by slxdy** [comment]
Log pls

**Comment by MeitziQ** [comment]
This is v0.5.5 and game crash. (game still work with version v0.5.3 )

[v0.5.5 Open-Beta crash.log](https://github.com/LavaGang/MelonLoader/files/9709993/Latest.log)

[Unity Player.log](https://github.com/LavaGang/MelonLoader/files/9710039/Player.log)

**Comment by HerpDerpinstine** [comment]
Works on the latest alpha-development nightly build.
