### ISSUE TITLE
[Enhancement]: show used command line options 

### ISSUE THREAD

**Issue by MeitziQ** [LavaGang/MelonLoader#295]
### Describe the new feature or enhancement

Even if you have debug logging enabled, used command line options is not logged.

Only line is Game::ApplicationPath but it does not show command line options how game was started.

**Comment by MeitziQ** [comment]
After one night, my mind also tells me, maybe there is difference between:

a. MelonLoader options used
b. Full commandline options

Maybe, in same cases, b will show security related data, like auth codes on some games?

**Comment by HerpDerpinstine** [comment]
This is now added in the latest alpha-development nightly build.
