### ISSUE TITLE
my game wont load and is stuck on the cpp2il initializing binary for last 20 minutes

### ISSUE THREAD

**Issue by Matybery** [LavaGang/MelonLoader#301]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

![image](https://user-images.githubusercontent.com/109036177/193419137-27b820f5-33e2-47a8-b63e-a0eb4186c71d.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
You should definitely have a log file, please upload it.

**Comment by SlidyDev** [comment]
Bruh, Sam
