### ISSUE TITLE
[Bug]: Demeo doesn't start

### ISSUE THREAD

**Issue by TheGrayAlien** [LavaGang/MelonLoader#303]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

The usual MelonLoader DOS window opens and it identifies Demeo but after the new ML splash the screen goes black for about 2 seconds and then it just returns to Windows as if nothing happened. Reverted to previous alpha version for a week ago and all works fine...
[Latest.log](https://github.com/LavaGang/MelonLoader/files/9693559/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Looking into this.

**Comment by HerpDerpinstine** [comment]
This is now fixed in the latest alpha-development nightly build.
