### ISSUE TITLE
[Bug]: System.MissingMethodException: Method not found: void System.Net.ServicePointManager.set_Expect100Continue

### ISSUE THREAD

**Issue by cxgreat2014** [LavaGang/MelonLoader#307]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Game cannot running and show this error message in the console:

```log
[ERROR] System.MissingMethodException: Method not found: void System.Net.ServicePointManager.set_Expect100Continue(bool)
  at MelonLoader.Core.Initialize () [0x0000b] in <80a94e21ac074902a9d511c653789548>:0 
```

Tried reinstalling the Game, reinstalling MelonLoader, restarting PC, didn't work.

Run with `--melonloader.debug` log:

[Latest.log](https://github.com/LavaGang/MelonLoader/files/9754615/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by cxgreat2014** [comment]
Seems like this issue: https://hackmd.io/@ghorsington/rJuLdZTzK

**Comment by HerpDerpinstine** [comment]
https://github.com/LavaGang/MelonLoader/issues/100
