### ISSUE TITLE
[Bug]: MelonLoader not working

### ISSUE THREAD

**Issue by IGBT-001** [LavaGang/MelonLoader#309]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

As mentioned in the title, when I localized a game, I found that after installing the MelonLoader framework, it could not work, no matter it is the x64\x86 version, I don't know if it is a game problem or what.
The following is the operation record:
1. Download and unzip MelonLoader.x64.zip
2. Copy the file to the root directory of Beacon Pines
3. Run the Beacon Pines game, the x86 version MelonLoader crashes and reports an error, the x64 version does not have any prompts but still cannot work

The link below is the game itself
https://drive.google.com/drive/folders/1Yggq4SByYeHh4BMCFCcgT4p5AhUBIwZY?usp=sharing
[MelonLoader_22-10-18_19-03-22.320.log](https://github.com/LavaGang/MelonLoader/files/9809653/MelonLoader_22-10-18_19-03-22.320.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
This is now fixed in the latest alpha-development nightly build.
