### ISSUE TITLE
[Bug]: Coroutines do not yield properly (Unity 2021.3.5f1 and newer)

### ISSUE THREAD

**Issue by extraes** [LavaGang/MelonLoader#327]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Yielding YieldInstructions, like WaitForSeconds and WaitForSecondsRealtime does nothing except wait a single frame.
The only way to wait a specified number of seconds is to have a timer count up by incrementing using Time.deltaTime or Time.unscaledDeltaTime.
My log file is [here](https://github.com/LavaGang/MelonLoader/files/10142949/Latest.log)
The code used to test is available [here](https://gist.github.com/extraes/ca4dfe1a0de9b15b1389ae2158dd350a)

Reimplementing WaitForSeconds and WaitForSecondsRealtime in the managed domain does nothing due to yielded coroutines not being executed.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SwiTool** [comment]
I'm adding to this issue that it seems that yielding a `MelonCoroutines.Start()` also returns in the next frame : 
```cs
System.Collections.IEnumerator CustomWaitForSeconds(float time)
{
    float t = 0;
    while ((t += Time.deltaTime) < time) yield return null;
}

// Somewhere in another coroutine
Stopwatch stopwatch = new Stopwatch();
stopwatch.Restart();
yield return MelonCoroutines.Start(CustomWaitForSeconds(5f));
stopwatch.Stop();
float swTime = (float)System.Math.Round(stopwatch.ElapsedMilliseconds / 1000.0, 2);
Log($"Stopwatch = {swTime} sec; Stopwatch VS time = {swTime - 5} sec"); // expecting this log 5s after, but is triggered after next frame
```

Result : 
```
[11:55:14.722] [CoroutineWaiter] Stopwatch = 2.15 sec; Stopwatch VS time = -2.85 sec
```
 
Edit: It took 2.15s because it's in the loading screen

I reproduced with the game engine version `2021.3.2f1`

**Comment by SwiTool** [comment]
I reproduced with the game engine version `2021.3.2f1`
