### ISSUE TITLE
[Bug]: Error when tried began playing

### ISSUE THREAD

**Issue by Caritusy** [LavaGang/MelonLoader#352]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/10251699/Latest.log)
It seems like the game was running successfully,but after "[20:26:36.939] 0 Mods loaded." the game just crashes.
crash screenshot:
![crash](https://user-images.githubusercontent.com/120786737/208242066-4eb53f41-9ccf-4e34-a8c1-5ebbdee313b6.png)
Main meaning of this error page: 0x344C300 command used 0x016 memory, this memory couldn't be read.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Its using a Unity version of 2020.3.17f99.
This most likely is a custom build of the engine.

**Comment by Caritusy** [comment]
So how can I solve this problem,using a different version of MelonLoader?

**Comment by nitrog0d** [comment]
It's using a modified Unity engine, we can't really help you
