### ISSUE TITLE
[Bug]: Incorrect operation of "Melon Loader" after updating "The Long Dark"

### ISSUE THREAD

**Issue by PhantomX5571** [LavaGang/MelonLoader#361]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Hello dear "Lava Gang". 
After updating the game "The Long Dark" and the release of DLC, your "MelonLoader" began to work incorrectly. I was able to install it and was able to see its boot screen (command prompt). But after 20 seconds of waiting, the window closes and the game does not start. Alas, I did not find the logs. I would like to know the approximate timing of the update of "MelonLoader" for correct operation under the new update of the game "The Long Dark".

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by mghicks** [comment]
I also see the same game crash behavior since TLD updated.  Removed all mods, tested again--same behavior. 
[MelonLoader_22-12-24_18-05-42.866.log](https://github.com/LavaGang/MelonLoader/files/10299249/MelonLoader_22-12-24_18-05-42.866.log)

Though, I see in discord this may be a well-known issue with a new Unity version...

**Comment by SamboyCoding** [comment]
This should be fixed with 0.6.0 - though mods will need to be updated to work.
