### ISSUE TITLE
[Bug]: il2cpp_init detour failed: One of the dependent libraries is missing.

### ISSUE THREAD

**Issue by WildArticunoAppeared** [LavaGang/MelonLoader#367]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When attempting to play Bloons TD 6 with MelonLoader v0.6.0 ALPHA Pre-Release installed, I get the following error:

il2cpp_init detour failed: One of the dependent libraries is missing.

And the game immediately shuts down.
Downgrading to MelonLoader v0.5.7 Open-Beta allows BTD6 to work just fine, however. But after reinstalling the v0.6.0 alpha the problem reappears.
I tried validating the game's files as I had a similar error happen to another Unity game after an update, but that didn't seem to do anything. Even reinstalling the game did nothing.

Here's the log file - it's basically just one line saying something very similar.
[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/10302512/Latest-Bootstrap.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Install the .net 6 runtime

**Comment by WildArticunoAppeared** [comment]
> Install the .net 6 runtime

Fixed that particular error for me. But other users are reporting that this issue persists even after installing the runtime.

**Comment by Vegthmar** [comment]
Can someone help me find the .net 6 runtime

**Comment by nls-thsg** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by someguy123man** [comment]
im not entirely shure what is happining but im on the 0.5.7 version and it brings up the coad sheet and looks normal but then it has a bunch of error text and closes

**Comment by Kirwons202** [comment]
Guys, where i need to put .zip archive with  .net 6 runtime? I just can't download it with autoinsataller

**Comment by busarudolf** [comment]
Install the .net 6 runtime
