### ISSUE TITLE
[Bug]: Crash on Mod loading

### ISSUE THREAD

**Issue by JoeGit8101** [LavaGang/MelonLoader#368]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I'm trying to install mods for Bonelab but, it keeps crashing when I get to the mod loading screen.
I've tried just installing "Bonelib" but that doesn't work either.
It happens for any mod i add.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/10318011/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Your mods are out of date. 0.6.0 broke compatibility with pre-0.6.0 mods. If the mod you want to use has not been updated yet, you will have to remain on 0.5.7.

**Comment by JoeGit8101** [comment]
> Your mods are out of date. 0.6.0 broke compatibility with pre-0.6.0 mods. If the mod you want to use has not been updated yet, you will have to remain on 0.5.7.

If you want me to use melon loader 0.5.7, i am all ready using it.
But if you want me to use mods with the version 0.5.7, then that makes a whole lot more scense.

**Comment by JoeGit8101** [comment]
> Your mods are out of date. 0.6.0 broke compatibility with pre-0.6.0 mods. If the mod you want to use has not been updated yet, you will have to remain on 0.5.7.

If you want me to use melon loader 0.5.7, i am all ready using it.
But if you want me to use mods with the version 0.5.7, then that makes a whole lot more sense.
