### ISSUE TITLE
[Bug]: CRASH strange 

### ISSUE THREAD

**Issue by werasik2aa** [LavaGang/MelonLoader#372]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

![image](https://user-images.githubusercontent.com/20810116/211152811-0c800805-974a-43f4-8d6b-fcdad705f41e.png)
[MelonLoader_23-01-07_20-22-51.449.log](https://github.com/LavaGang/MelonLoader/files/10366359/MelonLoader_23-01-07_20-22-51.449.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by werasik2aa** [comment]
the game crash after this line

**Comment by RinLovesYou** [comment]
Fixed in 0.6.0 alpha. Enable alpha in the installer settings.
