### ISSUE TITLE
[Bug]: MelonLoader crashes during initial loading of BTD6

### ISSUE THREAD

**Issue by dephtstriker** [LavaGang/MelonLoader#373]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

The MelonLoader seems to work like normal until it tries to initialize binary.
Then the loader crashes and the game gets loaded without the MelonLoader. 
I've reinstalled the game a few times as well as the MelonLoader.
I've also tried different versions of the melon loader. 
I have installed all the requirements in the correct versions.
[MelonLoader_23-01-09_16-20-17.945.log](https://github.com/LavaGang/MelonLoader/files/10374075/MelonLoader_23-01-09_16-20-17.945.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Fixed in 0.6.0 
 Enable alpha versions in the installer settings.
