### ISSUE TITLE
[Bug]: Missing Dependencies

### ISSUE THREAD

**Issue by EmiRZx** [LavaGang/MelonLoader#375]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I'm trying to install "Developer Console" mod, it looks like mod is updated but it doesn't working. I keep getting missing dependency error on melon console.

![Screenshot_5](https://user-images.githubusercontent.com/52245396/211373878-455f35c8-4d52-4f58-b751-226a2bfdcc7b.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Please include your log file.

**Comment by HunnyBuhn** [comment]
I'm having the same issue with missing dependencies on btd6, and would like some help.

**Comment by Rkb301** [comment]
> I'm having the same issue with missing dependencies on btd6, and would like some help.

Create an issue thing or describe it in detail here lol oof...

**Comment by ds5678** [comment]
This user is using an outdated MelonLoader installation.
