### ISSUE TITLE
[Crash]: Farthest  Frontier Playtest v08.1 does not work with Melon Loader v0.5.7 Open-Beta any more = CTD

### ISSUE THREAD

**Issue by darksharke** [LavaGang/MelonLoader#378]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Farthest  Frontier Playtest v08.1 does not work with Melon Loader v0.5.7 Open-Beta any more = CTD

For info only; anyone who so far has been choosing to run Farthest Frontier mods (from Nexus mods) using Melon Loader and successfully ran the game and all previous playtests with Melon Loader and mods from Nexus with NO ILL EFFECTs (in fact MANY improvements) be aware that this latest playtest v.08.01will NOT work if you have Melon Loader installed. It just crashes during load. Removing the mods folder has no effect at al. Melon Loader (latest version) crashes during its start up process and the game stops with it. 

[MelonLoader_23-01-19_20-58-34.157.log](https://github.com/LavaGang/MelonLoader/files/10461241/MelonLoader_23-01-19_20-58-34.157.log)

[MelonLoader_23-01-19_20-59-02.296.log]

(https://github.com/LavaGang/MelonLoader/files/10461244/MelonLoader_23-01-19_20-59-02.296.log)

 I guess this is a fundamental change somewhere in THIS new playtest or either Melon Loader needs an update or FF has chosen to nerf it so thatmods don't work  (I would hope that is not the case) if you have Melon Loader installed. My only solution to continue with mods was to stop using the playtest now and continue with the ordinary Farthest Frontier v 08.0 which still works perfectly...

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
> unity 2021.3.15

Yeah they updated the unity version, use 0.6.0 alpha and it'll work.

**Comment by damasioj** [comment]
For 0.6.0 alpha it's throwing an error when running the playtest:

> [20:58:13.892] [Il2CppAssemblyGenerator] Error Generating Interop Assemblies!
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Il2CppInterop.Generator.Contexts.AssemblyRewriteContext.RewriteTypeRef(TypeReference typeRef) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs:line 133
>    at Il2CppInterop.Generator.Passes.Pass12FillTypedefs.DoPass(RewriteGlobalContext context) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Passes/Pass12FillTypedefs.cs:line 33
>    at Il2CppInterop.Generator.Runners.InteropAssemblyGeneratorRunner.Run(GeneratorOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs:line 79
>    at Il2CppInterop.Generator.Il2CppInteropGenerator.Start() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 30
>    at Il2CppInterop.Generator.Il2CppInteropGenerator.Run() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 47
>    at MelonLoader.Il2CppAssemblyGenerator.Packages.Il2CppInterop.ExecuteInterop() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Packages\Il2CppInterop.cs:line 97

Attempting to load a mod throws another error:

> Failed to create an instance of the Melon.[21:00:48.913] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> File name: 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
>    at AutoFertilize.CompostAutomationService..ctor()
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
>    --- End of inner exception stack trace ---
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at MelonLoader.MelonAssembly.LoadMelons() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonAssembly.cs:line 239

I would imagine the second error is due to the first one though.

**Comment by SamboyCoding** [comment]
Can I get a full log for that?

**Comment by damasioj** [comment]
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10473663/Latest.log)

**Comment by rkr87** [comment]
I'm getting the same issue with 0.8.1p2.

**Comment by ferryfc** [comment]
is er al een update

**Comment by SamboyCoding** [comment]
Farthest frontier should now work. No need to redownload anything, just launch the game with melonloader 0.6.0 and it should work.
