### ISSUE TITLE
[Bug]: BTD 6 - Failed to download UnityDependencies ( 2021.3.12, the link is wrong)

### ISSUE THREAD

**Issue by Rkb301** [LavaGang/MelonLoader#380]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/10499671/Latest.log)
So I'm trying to launch BTD 6 v34.3.6116 with mods, I have 3 mods in the mods folder, its not even getting to the mod reading part. When I launch the game by double clicking on the .exe file it opens the console thing, does the startup, gets to installing unity dependencies and says that it failed to do it. I checked what link it was downloading from, found out its not hosted there anymore. The link for the dependencies is different now. I thought ok I'll manually download it and put it there but it doesn't read it, it just tries to download and install it. Please help.
Also I'm not sure what the start screen is and if I saw it or not.
### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Update to 0.6.0 

Enable alpha versions in the installer settings

**Comment by Rkb301** [comment]
Also, the game was working and launching properly before I installed MelonLoader.

**Comment by Rkb301** [comment]
> Update to 0.6.0
> 
> Enable alpha versions in the installer settings

Umm I tried that and it said missing the .NET framework 6.0.0 CORE, so I went to the official website installed its installer .exe file, ran it and tried again, it didn't work. Said the same thing that its missing the framework. So I switched back to 0.5.7 cuz it got me the farthest.
