### ISSUE TITLE
[Bug]: BTD 6 - (Slightly Different) Failed to download UnityDependencies ( 2021.3.12, the link is wrong)

### ISSUE THREAD

**Issue by Rkb301** [LavaGang/MelonLoader#381]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

P.S. - Rin please don't instantly close it again. So I'm trying to launch BTD 6 v34.3.6116 with mods, I have 3 mods in the mods folder, its not even getting to the mod reading part. When I launch the game by double clicking on the .exe file it opens the console thing, does the startup, gets to installing unity dependencies and says that it failed to do it. I checked what link it was downloading from, found out its not hosted there anymore. The link for the dependencies is different now. I thought ok I'll manually download it and put it there but it doesn't read it, it just tries to download and install it. Please help.
Also I'm not sure what the start screen is and if I saw it or not.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10499824/Latest.log)
The images below are showing where it crashes/gets stuck.
![image](https://user-images.githubusercontent.com/68736754/214579938-909ec93b-e5c3-44b6-bdbc-b8282da8388e.png)
![image](https://user-images.githubusercontent.com/68736754/214580000-70bda649-f5a6-4311-acfd-848ce40a404d.png)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by Rkb301** [comment]
The post above has the wrong Latest.log
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10499870/Latest.log)
This is the correct one.

**Comment by RinLovesYou** [comment]
You still haven't updated to 0.6.0

**Comment by Rkb301** [comment]
> You still haven't updated to 0.6.0

As I said in the previous post, 
Umm I tried that and it said missing the .NET framework 6.0.0 CORE, so I went to the official website installed its installer .exe file, ran it and tried again, it didn't work. Said the same thing that its missing the framework. So I switched back to 0.5.7 cuz it got me the farthest.

**Comment by RinLovesYou** [comment]
0.5.7 just doesn't work on that version. You need to install the .net 6 desktop runtime. 

Also, is that a pirated game i see?

**Comment by Rkb301** [comment]
Attaching the screenshots and latest.log after going to 0.6.0 in a minute or so too.

**Comment by Rkb301** [comment]
> 0.5.7 just doesn't work on that version. You need to install the .net 6 desktop runtime.
> 
> Also, is that a pirated game i see?

Uhhhhh no...... Totally not......

**Comment by Rkb301** [comment]
> 0.5.7 just doesn't work on that version. You need to install the .net 6 desktop runtime.
> 
> Also, is that a pirated game i see?

Never faced an issue with the pirated thing earlier, been a few years LOL

**Comment by RinLovesYou** [comment]
Go buy the game

**Comment by Rkb301** [comment]
> Go buy the game

Have exams going on, don't have permission to spend anything until May 1st :)

**Comment by RinLovesYou** [comment]
Come back when you bought it then

**Comment by Rkb301** [comment]
> Come back when you bought it then

Can you not close this and let someone else answer this?????
I'm gonna have to create a new one now..... Not tryna be rude but, just ignore the post if you can't solve my issue dammit!

**Comment by RinLovesYou** [comment]
We do not give support with pirated games. Of course I'll close it

Your issue is directly related to the fact it's pirated

**Comment by Rkb301** [comment]
> We do not give support with pirated games. Of course I'll close it

Huh, I'm pretty sure that wasn't a thing until like 5 months ago?

**Comment by RinLovesYou** [comment]
It has always been our stance.

**Comment by Rkb301** [comment]
> We do not give support with pirated games. Of course I'll close it
> 
> Your issue is directly related to the fact it's pirated

Its always worked with the pirated versions before, idk why its not working this time

**Comment by RinLovesYou** [comment]
Please just accept the fact that we do not, never have, and never will support piracy

**Comment by Rkb301** [comment]
> It has always been our stance.

Ok, so just clear this for me please? The fact that its telling me .NET Framework Core 6.0.0 not found or whatever is cuz its pirated and not cause of melon loader bugging?

**Comment by RinLovesYou** [comment]
No. You've probably installed the wrong version of the .net runtime

**Comment by Rkb301** [comment]
> Please just accept the fact that we do not, never have, and never will support 

> No. You've probably installed the wrong version of the .net runtime
Ok thanks!!!
