### ISSUE TITLE
[Bug]: Melon loader 0.5.3 doesn't work correctly for muse dash

### ISSUE THREAD

**Issue by mzl857** [LavaGang/MelonLoader#382]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Melon loader 0.5.3 works normally。But,the new version of just as plan cannot be completely unlocked.
[0.5.3 Latest.log](https://github.com/LavaGang/MelonLoader/files/10506883/0.5.3.Latest.log)
I tried other versions, but they didn't work properly。
[0.5.7 Latest.log](https://github.com/LavaGang/MelonLoader/files/10506884/0.5.7.Latest.log)
[0.6.0 Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/10506901/0.6.0.Latest-Bootstrap.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by mzl857** [comment]
![无标 题](https://user-images.githubusercontent.com/79705615/214770860-641a6667-825b-44e8-a636-cd5d014b41da.png)
![无标题](https://user-images.githubusercontent.com/79705615/214770863-070a7fdd-1edd-4210-9765-ef187f722d09.png)

**Comment by RinLovesYou** [comment]
Please try 0.6 again, you're missing the dotnet 6 runtime in that log

https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Choose "desktop runtime"

**Comment by mzl857** [comment]
> Please try 0.6 again, you're missing the dotnet 6 runtime in that log
> 
> https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> Choose "desktop runtime"

Very thanks！！！
But,can I unlock the new version of just as plan with version 0.6？

**Comment by RinLovesYou** [comment]
i don't know what that means, that sounds like a game specific thing. Can i assume MelonLoader itself works now? For anything game specific you'll have to talk to the modding community for that game

**Comment by mzl857** [comment]
> i don't know what that means, that sounds like a game specific thing. Can i assume MelonLoader itself works now? For anything game specific you'll have to talk to the modding community for that game

>Yes！Thank you very much. The melon loader is now working fine
