### ISSUE TITLE
[Bug]: BTD6 (34.3) Melon Loader (0.6.0 x64) crush "Caught Exception invoking Initialize! System.IO.IOException: Wrong descriptor"

### ISSUE THREAD

**Issue by Muponia** [LavaGang/MelonLoader#385]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

MelonLoader v0.6.0 (5.7.0 too) x64
Windows 7(looks like 2000, but its just a interface style)

Starting a game, like in every install guide.
Then instead of MelonLoader version, OS and Hash Code,
I get "Caught Exception invoking Initialize! System.IO.IOException: Wrong descriptor"
and some other stuff (on photo(cmd show entire thing, word moves to a new line))

I tried use x86(5.7.0 x86 too), but melonloader doesnt even shows(cmd and no melonloader loading menu things), but game said "Modded Client, most game modes are not avaible"(like in guides)

![photo](https://user-images.githubusercontent.com/123737330/215078800-42e8eb0f-b766-43ec-a250-bfdc2f44cc42.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Windows 7 is officially out of support, and we don't support it either.
