### ISSUE TITLE
[Bug]: [ERROR] SceneManager.sceneLoaded override failed: System.TypeInitializationException: The type initializer for 'NativeClassStruct' threw an exception. ---> System.ArgumentException: Field passed in is not a marshaled member of the type Il2CppClass_27_3

### ISSUE THREAD

**Issue by Nerddotexp** [LavaGang/MelonLoader#388]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[MelonLoader_23-02-03_15-50-29.157.log](https://github.com/LavaGang/MelonLoader/files/10583098/MelonLoader_23-02-03_15-50-29.157.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
You need to use 0.6.0
