### ISSUE TITLE
[Bug]: no uninstall button when selecting a game that melon is installed on

### ISSUE THREAD

**Issue by AltoidDev** [LavaGang/MelonLoader#389]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

when i select a game that melon is installed in, there is no uninstall and repair options, it just tells me to install it again
![image_2023-02-04_162032075](https://user-images.githubusercontent.com/100539243/216795151-6e781c2c-3011-4ead-bdb5-86b23ff69138.png)
![image](https://user-images.githubusercontent.com/100539243/216795155-23813d97-5320-4d9b-82ad-0f8bb1c6334d.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Yeah this is a known issue with 0.6, we need to rewrite the installer to be cross platform anyways

Will keep this open until 0.6.1 is out, hoping to have it done with that release

**Comment by SamboyCoding** [comment]
this is fixed now
