### ISSUE TITLE
[Bug]: melonpreferences

### ISSUE THREAD

**Issue by donimuzur** [LavaGang/MelonLoader#391]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.
using melonloader 0.6.- alpha pre-release
cant read melon preferences config on regional that using  comma ',' decimal separator. 
im using regional indonesia.

_**[08.07.15.311] Error while Loading Preferences from UserData/WorkAreaOverhauledConfig.cfg: Tomlet.Exceptions.TomlMissingNewlineException: Expecting a newline character at the end of a statement on line 3, but found an unexpected ','
   at Tomlet.TomlParser.Parse(String input) in /_/Tomlet/TomlParser.cs:line 91
   at Tomlet.TomlParser.ParseFile(String filePath) in /_/Tomlet/TomlParser.cs:line 29
   at MelonLoader.Preferences.IO.File.Load() in D:\a\MelonLoader\MelonLoader\MelonLoader\Preferences\IO\File.cs:line 84
   at MelonLoader.MelonPreferences.LoadFileAndRefreshCategories(File file, Boolean printmsg) in D:\a\MelonLoader\MelonLoader\MelonLoader\Preferences\MelonPreferences.cs:line 313**_

this is my config :
**_[WorkAreaOverhauled]
# multipliy the effect radius of work area (default value is 1)
WorkAreaOverhauledArboristBuildingConfig = 1,0_**

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by donimuzur** [comment]
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10660983/Latest.log)

**Comment by SamboyCoding** [comment]
Already fixed in nightly builds

**Comment by Wolzlin** [comment]
high,
I have the same problem, using melon loader 6.1 and the Preference Manager in "Farthest frontier" Since changing the loader to Beta 6,  I can't use the Preference Manager any more.  Using the F5 key doesnt open the Manager any more and I can't find a config file for the Preference Manager where I could change the =Opening Key" Attached pls find the latest log and I ask you to please have a look at it, as I don't know how to program this file.
Thank you very much for your assistance and the best greetings from Bavaria Germany

**Comment by Wolzlin** [comment]
Sorry i forgot to attach the latest log: 
[Latest.log](https://github.com/LavaGang/MelonLoader/files/11178057/Latest.log)
