### ISSUE TITLE
[Bug]: Mods in BTD6 is now working

### ISSUE THREAD

**Issue by 0Ariel0** [LavaGang/MelonLoader#392]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I was trying to install mods in bloons td 6 because my file of "Save" never saved because my game is pirated so I tried to use mods to improve the game and put logo level maximum and infinite money since it lost everything. But when I went to install the melon loader it just didn't start the mods.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/10678370/Latest.log)

Orthers log:

[MelonLoader_23-02-07_15-28-41.945.log](https://github.com/LavaGang/MelonLoader/files/10678372/MelonLoader_23-02-07_15-28-41.945.log)

[MelonLoader_23-02-07_15-33-22.319.log](https://github.com/LavaGang/MelonLoader/files/10678373/MelonLoader_23-02-07_15-33-22.319.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Pirated game, no support
