### ISSUE TITLE
[Bug]: --melonloader.launchdebugger with Wine causes crash on init

### ISSUE THREAD

**Issue by asc11cat** [LavaGang/MelonLoader#393]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Using --melonloader.launchdebugger flag causes crash on loader init, no logs are produced.

Wine 7.0, il2cpp game, loader version is v0.6.0

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Yeah that's simply unsupported under wine, will make sure to clarify that
