### ISSUE TITLE
[Bug]: Melonloader V6 install but il2cpp_init missing

### ISSUE THREAD

**Issue by Massator** [LavaGang/MelonLoader#394]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

i [install]([url]([url]([url](url)))) melonloader v6 for the mod in farthest frontier but the console  say :  il2cpp_init missing in the librairies

[12:10:44.079] [ERROR] Internal Failure: il2cpp_init detour failed: One of the dependent libraries is missing.
![image](https://user-images.githubusercontent.com/124883358/217797676-929d4164-7e91-45f0-be29-9e8e1dc078c8.png)
i don't know where is the problem

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
install the .net 6.0 Runtime.

**Comment by rakosi2** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-6.0.13

**Comment by Massator** [comment]
It works! Thank you !
