### ISSUE TITLE
[Bug]: The strongest modLoader blocked by Unicode. error Failed to Open Mono Assembly

### ISSUE THREAD

**Issue by ffftian** [LavaGang/MelonLoader#396]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I tried to add modLoader to a beta game
This is a game developed by Chinese people. Its {}. exe is in Chinese 
I used the Chinese name to package the unity game myself, and also failed
I think that's the problem

The Chinese packaged file folder and exe are similar to
打包测试，项目输中文_Data
 打包测试，项目输中文.exe
As a contrast, when I name the game in English Path is English,ModLoader is no problem

![error](https://user-images.githubusercontent.com/43436493/218298546-5fdade14-20b5-4089-a964-3cd7b107928e.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Yes, Unicode isn't supported.
