### ISSUE TITLE
[Bug]: Crashing on start of game

### ISSUE THREAD

**Issue by boowoompp** [LavaGang/MelonLoader#397]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

im loading the game but when i get to the end of the melon loader screen it crashes (im playing bonelab btw)
[MelonLoader_23-02-16_09-56-19.832.log](https://github.com/LavaGang/MelonLoader/files/10757236/MelonLoader_23-02-16_09-56-19.832.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
use 0.6.1
