### ISSUE TITLE
Farthest Frontier  0.8.1* arbeitet wieder mit Melonloader zusammen, aber nur mit Alpha 0.60 und .net 6

### ISSUE THREAD

**Issue by ronaldi40** [LavaGang/MelonLoader#398]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Farthest Frontier  0.8.1a arbeitet definitiv nicht mehr mit Melonloader zusammen, auch nicht Alpha 0.60
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10765791/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by ronaldi40** [comment]
Farthest Frontier 0.8.1a arbeitet definitiv nicht mehr mit Melonloader zusammen, auch nicht Alpha 0.60

**Comment by SamboyCoding** [comment]
0.6.0 definitely works, multiple people are using it fine. Do a clean reinstallation of melonloader.

**Comment by ronaldi40** [comment]
If you can't read, you've already tried it.
Kannst Du nicht lesen, ist schon längst ausprobiert.

**Comment by SamboyCoding** [comment]
Well try it again, because you're doing it wrong. It works. The log you've sent is not from a fresh install of MelonLoader.

**Comment by ronaldi40** [comment]
What am I doing wrong? I've installed it many times now, so it doesn't look like a clean install. I even deleted the remaining directories by hand after the uninstallation, including in the registry. Oh, and nothing is created in the Userdata folder either. So where is the mistake please?
Was mache ich denn falsch?
Ich habe es mittlerweile viele male installiert, daher sieht es nicht wie eine Neuinstallation aus. Ich habe sogar nach der Deinstallation die übrig gebliebenen Verzeichnisse von Hand gelöscht, auch in der Registry. 
Ach so, im Ordner Userdata wird auch nichts erstellt. Also wo liegt der Fehler bitte?

**Comment by ronaldi40** [comment]
Mehr kann man nicht machen, fertig es funktioniert eben nicht!!!
https://github.com/LavaGang/MelonLoader.Installer/blob/master/README.md#how-to-install-re-install-or-update-melonloader

**Comment by SamboyCoding** [comment]
Delete all melonloader files, reinstall melonloader, and then send a log *of the first time running the game after installing ML* here. Can't even begin to help without that.

**Comment by ronaldi40** [comment]
Hello, I've done this a number of times, it just doesn't work. Take a look at the Nexusmods page, there are many who have the same problem, almost all of them.
And one more thing, I've been setting up computers and software for over 30 years, I know what I'm talking about. Thanks
Hallo, das habe schon etliche male gemacht, es funktioniert halt nicht. Schau doch einmal auf der Nexusmods Seite vorbei, da gib es sehr viele, die das selbe Problem haben, fast alle.
Und noch was, ich richte Computer und Software seit über 30 Jahre ein, ich weiß, wovon ich rede. Danke

**Comment by PavRose** [comment]
I have an issue too. The moment I try to start the game I get an error saying that one of the libraries is missing (it happens only with 0.6 and I have tried to instal it at least 10 times).

**Comment by SamboyCoding** [comment]
@PavRose "One of the dependent libraries is missing" = you didn't install .net 6

**Comment by SamboyCoding** [comment]
> Hello, I've done this a number of times, it just doesn't work. Take a look at the Nexusmods page, there are many who have the same problem, almost all of them.
And one more thing, I've been setting up computers and software for over 30 years, I know what I'm talking about. Thanks
Hallo, das habe schon etliche male gemacht, es funktioniert halt nicht. Schau doch einmal auf der Nexusmods Seite vorbei, da gib es sehr viele, die das selbe Problem haben, fast alle.
Und noch was, ich richte Computer und Software seit über 30 Jahre ein, ich weiß, wovon ich rede. Danke

@ronaldi40 

That's super crazy, because you know what? I just installed melonloader 0.6.0 on farthest frontier 0.8.1a and it worked first time.

**Comment by PavRose** [comment]
@SamboyCoding I have net6 inside the MelonLoader folder. The error I get says "il2cpp_initdetourfailed"

**Comment by ronaldi40** [comment]
Blödsinn, ich habe .net6 installiert und sogar die Repsraturfunktion ausgeführt, welche auch automatisch .net6 von Farthest Frontier aktualisiert.
Heck, I installed .net6 and even ran the repair function, which also automatically updates Farthest Frontier's .net6.

**Comment by SamboyCoding** [comment]
@PavRose No, you need to install [the net6 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-6.0.13). @ronaldi40 You definitely have it installed, but you are yet to provide me with the log I asked for from a fresh installation of melonloader.

**Comment by PavRose** [comment]
@SamboyCoding It works perfectly! Thanks a lot for the help. I think an installation video will be very helpful.

**Comment by ronaldi40** [comment]
Hallo, es funktioniert wieder. Bin allein drauf gekommen.
Das Spiel mußte komplett deinstalliert und neu installiert werden.
Und noch was, das Entfernungsproblem, mit dem "," , wird so gelöst, in "userdata" das Komma in Punkt "." ändern, Datei auf schreibgeschützt setzen und fertig.
Danke für Deine Unterstützung.
