### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by qqwsvnba123** [LavaGang/MelonLoader#400]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

**Hello, my problem is that I installed all the components as required, but as soon as I entered the game, I could not enter the game

0.6.0[NewEntryPoint] Passing ptr to LoadAssenblyAndGetFuncPtr back to host...[NewEntryPoint] Configuring inports...[NewEntryPoint] Initializing. In default load context: True[NewEntryPoint] Caught exception invoking Initialize? Systen.I0.IOException:柄无效。at Microsoft.Win32.SafeHandles.SafeFileHandle.GetFileOptions<>at System.I0.FileStream..ctor<SafeFileHandle handle, FileAccess access, Int32bufferSize>at System.IO.FileStream..ctor<SafeFileHandle handle, FileAccess access)at **MelonLoader.Utils.MelonConsole.Init<>** in D:\aMelonLoaderMelonLoaderMelo nLoader\Wtils MelonConsole.cs:line 23at MelonLoader.Core.Initialize<> in D:aMelonLoader MelonLoader MelonLoader Core.cs:line 46at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize<> in D:\aMelonLoader MelonLoaderMelonLoader.NativeHostMelonLoaderInvoker.cs:line 10at MelonLoader.NativeHost.NativeEntryPoint.Initialize> in D:\aMelonLoaderM elonLoaderMelonLoader.NativeHost WativeEntryPoint.cs:line 43

Now using the system Windows 7 flagship Edition 64-bit SP1 (4.09.00.0904), download the necessary components are.NET 3.4.7.2,.NET 4.8, NET 6.0, Microsoft Visual C++ 2015-2019 [x64]**

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Windows 7 is not supported.

**Comment by qqwsvnba123** [comment]
> 不支持 Windows 7。

Ok, thank you very much
