### ISSUE TITLE
[Bug]: btd6 crashes when launched after getting error: internal failure. failed to download cpp2il. latest log doesnt generate

### ISSUE THREAD

**Issue by spinmastercodes** [LavaGang/MelonLoader#401]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

so. i litterally spent a month or 2 trying to get github alone to work. fixed my pc. did all that crap. finally got it to work. was hype to play some btd6 with mods

then. another f*cking problem apeared. cpp2il. failed to download. COULDNT FIND NO CRAP ON THE INTERNET ABOUT THIS ive literally lost my mind over this. brooo. i need therapy and m o d s. i cant live without my  m o d s

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by DarkNebulousSpaector** [comment]
I had the issuse expsct i only reinstalled melon loader, it just won't start

**Comment by emmaliefje** [comment]
I have the same issue. Uninstalling melonloader loads the game just fine. Have tried a few solutions online [https://www.reddit.com/r/MelonLoader/comments/uvf100/melon_loader_fails_to_download_cpp2il/](found here) with no luck. Any solutions are appreciated.

**Comment by SamboyCoding** [comment]
Make sure you're using melonloader 0.6.0 for BTD6. Beyond that, we can't help without a log file - which definitely exists if it's getting as far as the error you're saying.

**Comment by ssertewfsf** [comment]
> Make sure you're using melonloader 0.6.0 for BTD6. Beyond that, we can't help without a log file - which definitely exists if it's getting as far as the error you're saying.
There isnt an option to download version 6.0 only 5.7

**Comment by Bootykit** [comment]
> > Make sure you're using melonloader 0.6.0 for BTD6. Beyond that, we can't help without a log file - which definitely exists if it's getting as far as the error you're saying.
> > There isnt an option to download version 6.0 only 5.7

Use one of the zip files (x86 or x64), and manually move files instead of installer as it's missing the new version.

**Comment by SamboyCoding** [comment]
It's not missing the new version, you have to enable it in the installer settings -> show alpha pre-releases

**Comment by sunyudai** [comment]
Resolved this issue for myself, see my reply to duplicate issue #428 

https://github.com/LavaGang/MelonLoader/issues/428#issuecomment-1540919885
