### ISSUE TITLE
[Bug]: Demeo PC VR doesn't work since this morning's patch

### ISSUE THREAD

**Issue by TheGrayAlien** [LavaGang/MelonLoader#402]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

This morning's Demeo patch changed a variable that MelonLoader uses to check if the game is running on PC or VR. This breaks the game entirely for PC VR users when using MelonLoader by leaving players at a black screen forever after the initial "Resolution" logo (even with no mods loaded) but somehow still allows PC-Edition users to play the game and even run mods.

The variable Demeo changed was **MotherbrainGlobalVars.IsRunningOnDesktop** which is now **MotherbrainGlobalVars.IsRunningOnNonVRPlatform** instead. 

The issue is located in the Module.cs in the \Dependencies\CompatibilityLayers\Demeo folder and the related decompilation. Should be a quick and easy fix.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
MelonLoader does not check for PC/VR. That is up to the mods, Please check with the mod authors for support
