### ISSUE TITLE
https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-6.0.13

### ISSUE THREAD

**Issue by J-P2** [LavaGang/MelonLoader#404]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-6.0.13

_Originally posted by @rakosi2 in https://github.com/LavaGang/MelonLoader/issues/394#issuecomment-1424607250_

This didn't work for me. I tried it 5mins ago and I'm still getting the same error as the original poster

**Comment by RinLovesYou** [comment]
Then you didn't install the right one. You need the x64 version of the desktop runtime 

![IMG_20230112_014919](https://user-images.githubusercontent.com/29461788/221080397-247bdfaa-a85c-4322-9c0c-e9919c85a557.jpg)
