### ISSUE TITLE
[Bug]: crash using .60 with Farthest Frontier Internal Failure: il2cpp_init detour failed: One of the dependent libraries is missing

### ISSUE THREAD

**Issue by gvales161616** [LavaGang/MelonLoader#405]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/10820236/Latest-Bootstrap.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by GSNotifications** [comment]
You need https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-6.0.12 to run it.

**Comment by RinLovesYou** [comment]
Closing this due to a week of inactivity, and this not being a bug.
