### ISSUE TITLE
[Bug]: Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Object elements in a custom attribute signature should be either 'null' or an instance of BoxedArgument.

### ISSUE THREAD

**Issue by BSBP4L** [LavaGang/MelonLoader#411]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Hello I am at my wits end. I have searched for answers through the internet and have found nothing so i am here. every time i boot up melon loader along with btd6 it always produces these same errors listed below. any help is appreciated and if you need to call me dumb if it is something so simple
[MelonLoader_23-02-28_16-19-05.267.log](https://github.com/LavaGang/MelonLoader/files/10855300/MelonLoader_23-02-28_16-19-05.267.log)
[!!!!]UPDATE[!!!!]
Just make sure you are using the latest version FROM GITHUB. i am so sorry i am going to be in a corner if you need me

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Use MelonLoader 0.6.0 for BTD6.

**Comment by BSBP4L** [comment]
> Use MelonLoader 0.6.0 for BTD6.

i am i used both the autmomatic installer along with going so far as to manually install it and it still gives me those errors

**Comment by RinLovesYou** [comment]
The log clearly says 0.5.7

**Comment by BSBP4L** [comment]
alright ill try again

**Comment by BSBP4L** [comment]
I'm so stupid I'm so sorry everyone i was using the one from the melon loader website i will now subject myself to huddling in a corner out of shame.
