### ISSUE TITLE
[Enhancement]: Add a warning when installing Melonloader for BTD6

### ISSUE THREAD

**Issue by Timotheeee** [LavaGang/MelonLoader#413]
The BTD6 modding discord servers are constantly flooded with users attempting to use version 0.5.7, which doesn't work for BTD6. I suggest adding a warning so that when the installer is given a btd6 directory, it gives the user a warning that versions older than 0.6.0 do not work on btd6 anymore and that .net 6.0 is required. this would remove 80% of the help requests.

**Comment by RinLovesYou** [comment]
Melonloader is not made for btd6, so it would be a bit annoying to maintain something like that. It's not like btd6 is the only game that needs 0.6, we can't possibly keep track of them all.

Once 0.6.1 comes out, it will be out of alpha and installed by default. Then these problems should stop.
