### ISSUE TITLE
[Enhancement]: Add support of Custom Engine versions

### ISSUE THREAD

**Issue by Caritusy** [LavaGang/MelonLoader#419]
### Describe the new feature or enhancement

My last error report #352 @nitrog0d says "It's using a modified Unity engine"
But in actually that's not a modified version,the game was created on a LTS version so that the MelonLoader loaded the Unity version incorrectly. (e.g. The detail tell me that's a 2020.3.17f1c1(LTS) but MelonLoader failed to load the version and mark it to 2020.3.17f99)

**Comment by SamboyCoding** [comment]
C1 is a modified engine for our purposes, it often comes with encryption and difficult-to-understand modifications over the normal version of the engine.

**Comment by Caritusy** [comment]
Can players just select their own engine version if the modified engine's version was been confirmed?
