### ISSUE TITLE
[Bug]: attempted to use melonloader with btd6, it crashs on loading screen

### ISSUE THREAD

**Issue by Xeov** [LavaGang/MelonLoader#427]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

log file : https://github.com/LavaGang/MelonLoader/files/11012065/MelonLoader_23-03-19_18-58-17.730.log
i installed melonloader with bloons td 6 and it loads without mods but when i tried to use it with mods but it gets up until the "Cpp2IL initializing binary" and and crashs.
i dont understand what "Was able to see the Start Screen." box means

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
Use melonloader 0.6.0 for BTD6.

**Comment by Xeov** [comment]
> Use melonloader 0.6.0 for BTD6.

yo i made new issue
