### ISSUE TITLE
[Bug]: [17:27:40.372] [Custom_Maps] [ERROR] System.NullReferenceException: Object reference not set to an instance of an object   at CustomMaps.CustomMaps.OnSceneWasLoaded (System.Int32 buildIndex, System.String sceneName) [0x00005] in <aae81561c5984e49ab049ae33835dc15>:0   at MelonLoader.MelonEvent`2+<>c__DisplayClass1_0[T1,T2].<Invoke>b__0 (MelonLoader.LemonAction`2[T1,T2] x) [0x00000] in <6425afb6ac6a429aaf770255d2f7de57>:0   at MelonLoader.MelonEventBase`1[T].Invoke (System.Action`1[T] delegateInvoker) [0x00018] in <6425afb6ac6a429aaf770255d2f7de57>:0

### ISSUE THREAD

**Issue by CadenMcAllister** [LavaGang/MelonLoader#431]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

When I launch Boneworks I am met with this issue when loading into the start screen. It only occurs when I am trying to install custom maps. This might not be the right place to ask this, and I am sorry if it is not. However I have not been able to find a solution to this anywhere else.
![Screenshot 2023-03-26 172935](https://user-images.githubusercontent.com/126972887/227808708-3994a2c6-b6f2-4556-8746-1273111c6515.png)
[MelonLoader_23-03-26_17-27-09.458.log](https://github.com/LavaGang/MelonLoader/files/11073239/MelonLoader_23-03-26_17-27-09.458.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
this is the wrong place. this is an issue with a mod, not melonloader. please go to the modding server for the game, can be found on the wiki or our discord.

**Comment by CadenMcAllister** [comment]
Ok

**Comment by CadenMcAllister** [comment]
I fixed it by using Melon Loader 0.5.7
