### ISSUE TITLE
[Bug]: Not Initialize

### ISSUE THREAD

**Issue by Bright1192** [LavaGang/MelonLoader#435]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

A lot of white words appeared when the console was loading forced to exit ,And latest.log file does not refresh
[![](https://user-images.githubusercontent.com/112922267/230700946-e975d52e-1960-4e7b-8454-35bd0d0fbe82.png)![](https://user-images.githubusercontent.com/112922267/230700948-358bfe1a-f320-4c96-a66c-a6a17422c3f2.png)](https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/issues/42)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Please make sure that there is no Unicode inside the path, If that does not resolve your issue then please reopen this issue.
