### ISSUE TITLE
[Bug]: UnityEngine.AudioModule.dll gets flagged as a virus

### ISSUE THREAD

**Issue by CaydeTheProtogen** [LavaGang/MelonLoader#440]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

The file BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppInterop\Il2CppAssemblies\UnityEngine.AudioModule.dll gets flagged as a virus and when allowed as an exception cannot be deleted or removed, may have more in it too, if the file isn't installed melon loader cannot work

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Really nothing we can do about it, allow the entire game folder recursively in your antivirus is all we can tell you to do
