### ISSUE TITLE
"failed to execute cpp2il" MelonLoader not working. I assume something is missing

### ISSUE THREAD

**Issue by xPhilipDK** [LavaGang/MelonLoader#442]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When I try to start my game, MelonLoader opens and gives the message as seen in the picture, but nothing else happens and it soon closes afterward.
![MelonLoader](https://user-images.githubusercontent.com/45209716/234341736-16da6eba-f80e-4196-911b-723cc485391b.png)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by xPhilipDK** [comment]
By downgrading a version, I managed to move some steps forward. However, I now get the message that MelonLoader "failed to execute cpp2il"
![MelonLoader 2](https://user-images.githubusercontent.com/45209716/234364992-216d8c5f-0ea6-4ddf-9022-23936c90baf0.png)

**Comment by SamboyCoding** [comment]
Remove the apostrophe (`'`) from your game path

**Comment by xPhilipDK** [comment]
I was presented to that solution somewhere else, and it solved the problem. Thanks.
