### ISSUE TITLE
[Bug]: failed to clean out console

### ISSUE THREAD

**Issue by joejoejoejoejoejoejoejoeeeeeee** [LavaGang/MelonLoader#443]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

First off, I did not get specifically the latest.log file, i have the latest log with the error I have. 
log in question:
[MelonLoader_23-04-25_20-22-38.031.log](https://github.com/LavaGang/MelonLoader/files/11328152/MelonLoader_23-04-25_20-22-38.031.log)
The error is that I get a failed to clean out console errors. All mods load, no start sceen. About all I can tell, since I am not a dev in any field, at all. I will also mention I am using R2MODMAN/Thunderstore Mod Manager.

### Did you attach your log file?

- [x] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Does this issue persist without the use of r2modman?

**Comment by rakosi2** [comment]
Closing due to no response from the creator, If you still are having this issue, feel free to reopen this issue.
