### ISSUE TITLE
[Bug]: Missing Method System.IO.FileStream

### ISSUE THREAD

**Issue by alfabe78h** [LavaGang/MelonLoader#448]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Hello i was installing melonloader on firewatch and then i finished the installation and then ı tried launching the game and an error screen popped up
![ApplicationFrameHost_PjaUMtNxYs](https://user-images.githubusercontent.com/104769587/235352358-4972f849-4986-4630-8f02-319c01936309.png)
it was really fast i had to record it and slow it down and i tried everything but it just doesnt work it didnt even create a log file.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by ghost** [comment]
i had this too

**Comment by alfabe78h** [comment]
does anyone have a solution

**Comment by flerouwu** [comment]
Hey guys! Melon Loader v0.5.7 works with Firewatch. Try downgrading to that version and trying again.

**Comment by alfabe78h** [comment]
why doesnt it work with other versions tho

**Comment by flerouwu** [comment]
> why doesnt it work with other versions tho

It's probably some change in the v0.6.1 release that broke it.

**Comment by alfabe78h** [comment]
Ok thanks
