### ISSUE TITLE
[Bug]: Auto close game (Star Rail)

### ISSUE THREAD

**Issue by ascent-sys** [LavaGang/MelonLoader#449]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

The game crashes if "version.dll" is used. Probably related to anti-cheat.

![Star Rail 1](https://user-images.githubusercontent.com/61962629/235686508-3337a78f-02dd-49dd-87dc-f6aad83b996a.png)

This is the only message in the console. Next comes the crash.

If use "winhttp.dll" the initialization continues, but at some point an error occurs and everything closes.

![Star Rail 2](https://user-images.githubusercontent.com/61962629/235687116-3104be7a-738f-4c60-89fc-5a6c17f481a7.png)

There are no such errors in the log files.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11373802/Latest.log)
[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/11373803/Latest-Bootstrap.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
miHoYo uses a custom version of Unity and we also do not provide any support to circumvent any form of Anti-Cheat.
