### ISSUE TITLE
[Bug]: Stuck on "Cpp2IL - Seaching Binary for Required Data" RecRoom Game

### ISSUE THREAD

**Issue by DanDaMan95** [LavaGang/MelonLoader#450]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11375662/Latest.log)

Ive tried everything i can think off but no use hope this normal and im missing something or you just cant use melon loader with this game.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
We do not support games with anticheat
