### ISSUE TITLE
[Bug]: how can I change text size?

### ISSUE THREAD

**Issue by nomeansh** [LavaGang/MelonLoader#451]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I wanna change the text size, but Im not found.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
text size of what

**Comment by nomeansh** [comment]
> text size of what

ALT+1 window

**Comment by rakosi2** [comment]
Ctrl and scroll wheel also works
