### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by clothingandprefabsrr** [LavaGang/MelonLoader#453]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

ok so in the middle of loading  everything it just shuts down, im using v0.5.7, the issue only started when i installed v0.6.1, and while  0.4.3 works it doesnt load any mods. heres my latest.log
[Latest.log](https://github.com/LavaGang/MelonLoader/files/11436297/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by clothingandprefabsrr** [comment]
The issue was i forgot 1 of the dependencies lol

**Comment by clothingandprefabsrr** [comment]
ok uhm now its crashing on the loading screen of bonelab

**Comment by RinLovesYou** [comment]
this is not how you use github issues. These are for bug reports without any mods, and not for questions without any further info. If you're having trouble with mods i suggest going to where you got them.

**Comment by clothingandprefabsrr** [comment]
oh ok srry

**Comment by clothingandprefabsrr** [comment]
it was my first time
