### ISSUE TITLE
[Bug]: Signature and Mono Issue

### ISSUE THREAD

**Issue by sinz6th** [LavaGang/MelonLoader#455]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11448857/Latest.log)

Troubleshooting done:
Reinstalled the game Multiple times.
Reinstalled Melon loader twice.
Made sure it uses the x64 ver. and not Auto-Detect.
Made sure all the Req. are met, even reinstalled them to make sure.
I tried the melon loader installer and the manual install. (zip)
I have no mods & plugins installed.

Other issue not mentioned in Latest.log:

Your mono runtime and class libraries are out of sync.
The out of sync library is: C:\Program Files (x86)\Steam\steamapps\common\Citywars Tower Defense\MelonLoader\net35\MelonLoader.dll

I'm not exactly sure on how to 'fix' the issue listed above, as all the other issues posted on this repo are connected to Terraria servers and or Linux/Ubuntu related which i think are completely different from this game since you don't run the server yourself.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
out of sync is caused by an unimlemented internal call we didn't catch, and the signature issue isn't a big concern either. I'm not sure what you're talking about with Terraria, there aren't really any issues connected to it. That's not even a unity game. Does your game crash? these are pretty non-fatal errors.

**Comment by sinz6th** [comment]
> out of sync is caused by an unimlemented internal call we didn't catch, and the signature issue isn't a big concern either. I'm not sure what you're talking about with Terraria, there aren't really any issues connected to it. That's not even a unity game. Does your game crash? these are pretty non-fatal errors.

The reason i mentioned Terraria was because it also uses mono? but via Tshock and it has the same error message so i thought those could be related and provide a solution, sorry-

My game doesn't crash no.

Edit: If the problem i listed really doesn't change anything I'm fine with closing the issue, i just thought it's something that needs fixing
