### ISSUE TITLE
[Bug]: i get an error on melonloader and r2modman

### ISSUE THREAD

**Issue by pogawer** [LavaGang/MelonLoader#457]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

So when i tryed melon loader it seid oh missing bootstrap.dll and I downloaded a bootstrap.dll it did not fix so i uninstald the game and reinstalled, nothing so i unistaled melon loader, now it game me a new message say cant find Where my game is even tho i put it on boneworks several times, so i try r2modman and try it, it gives me an error that closed emetely. but i try melon loader again and it now seys cant find bootstrap.dll could not get on recording
and i all ready know just reinstall it I DID MENY TIMES can ANY ONE SHOW ME A VID OF HOW TO DOOOOOOOOOOOoo
edit: idk if i have the log file but i know i think i have used it befor but idk
and this is what happends.
watch to the end
https://clipchamp.com/watch/OoHDdFVZOJI

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by pogawer** [comment]
still waiting

**Comment by PlacideJumonville** [comment]
Same problem

**Comment by pogawer** [comment]
some one help its been 2 weeks

**Comment by AlphaLovesYou** [comment]
hey. github issues are not a good place to go to for support (as you obviously can tell).
for more immediate support you should go to the official melon loader discord server.

**Comment by rakosi2** [comment]
If it works without r2modman but not with it, it should maybe be asked in https://github.com/ebkr/r2modmanPlus

**Comment by rakosi2** [comment]
Are you still having this issue?

**Comment by PlacideJumonville** [comment]
I fixed the issue. I deleted steam and reinstalled it and all the games. It takes awhile, but it works!

**Comment by rakosi2** [comment]
Nice
