### ISSUE TITLE
[Crash]: Error Generating Interop Assemblies!

### ISSUE THREAD

**Issue by Rekitt** [LavaGang/MelonLoader#460]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11517485/Latest.log)

Error Generating Interop Assemblies!

### Did you attach your log file?

- [x] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Looks like it doesn't have access to the path. Have you tried running as admin? Alternatively you can set the permissions for (assumably) the entire drive for your user
