### ISSUE TITLE
[Bug]: Access to Il2CppAssemblyGenerator files is denied

### ISSUE THREAD

**Issue by MaxOhNoo** [LavaGang/MelonLoader#461]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11525231/Latest.log)

Melonloader runs fine without mods, fails to load with any mods installed. 
Melonloader 0.6.1 beta
BTD6 36.3
Net6 runtime

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Assembly generation is failing. make sure you don't have any files from the game open, or try running as admin. When running as admin the base path might be wrong, you can specify it with a launch option `--melonloader.basedir=path/to/game`

**Comment by MaxOhNoo** [comment]
No files open, ran as admin with a manually set directory. Does not work.

**Comment by rakosi2** [comment]
Make sure a virus scanner hasn't deleted any MelonLoader files.

**Comment by rakosi2** [comment]
Seems like this issue is resolved, If it wasn't, feel free to reopen it.
