### ISSUE TITLE
[Bug]: DLL Not Found

### ISSUE THREAD

**Issue by ALEZ-DEV** [LavaGang/MelonLoader#467]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I install melon loader for Punishing:  Gray Raven and it seems that's DLL files is missing, but I don't know which
default log (this log don't catch the error)
[Latest.log](https://github.com/LavaGang/MelonLoader/files/11590959/Latest.log)
I succeed to copy the error directly from the terminal
[log.txt](https://github.com/LavaGang/MelonLoader/files/11590976/log.txt)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by ALEZ-DEV** [comment]
I fixed the issue
I just simply downgrade from version 0.6.1 to version 0.5.7

**Comment by elfoxus** [comment]
Same for me

**Comment by hatrd** [comment]
same, Internal Failure: failed to load the original dll. Solved by downgrading.
