### ISSUE TITLE
No way bro 

### ISSUE THREAD

**Issue by GalaxyDonut5** [LavaGang/MelonLoader#472]
### Describe the new feature or enhancement

Theres no way you can add mods but only for PC, not even mobile or laptops. seriously need to add that cause i play on mobile and chromebook

**Comment by RinLovesYou** [comment]
This is not how you open a feature request. 
If you had read our wiki, you'd have seen that a mobile fork exists that is not ready to be merged upstream. I don't think Chromebooks even support unity, if they do, i don't think anyone on the team has a Chromebook. You're free to open a respectful issue if Chromebooks do indeed have unity games.

**Comment by SwiTool** [comment]
This feels so disrespectful....

Developers are not machines, you should talk to them nicely.
Your message have no purpose but to make the readers rageful and NOT do what you are requesting.
