### ISSUE TITLE
[Bug]: Failed to allocate console!

### ISSUE THREAD

**Issue by Danetterry** [LavaGang/MelonLoader#475]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I'm using proton on Fedora 38

When i trying to start game with version.dll it crashes 

Using start options in steam gnome-terminal %command%
i get error message [15:05:24.904] [ERROR] Failed to initialize MelonLoader: Failed to allocate console!

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Yes this is a known issue, however the cause is unknown and completely random. Once i finally find a game where this happens i will try to fix this, until then i sadly can't do anything about it.

**Comment by WeraPea** [comment]
I found a workaround by adding --melonloader.hideconsole to the launch arguments.

**Comment by dxnvswrld** [comment]
how do i access launch arguments
