### ISSUE TITLE
[Bug]: Attribute Primitive failure

### ISSUE THREAD

**Issue by Niksen13** [LavaGang/MelonLoader#478]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I'm not entirely sure what IL2CPP_TYPE_END is, but it seems to stop assembly generation.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11782201/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Unicode characters in the path like `依盖之书` is know to cause issues, remove them and try again.
