### ISSUE TITLE
[Bug]: Crashed on start 4+ times in a row.

### ISSUE THREAD

**Issue by TheanMcGarity** [LavaGang/MelonLoader#482]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

When i tried to start the game to test a mod i was working on, i got this error
![image](https://github.com/LavaGang/MelonLoader/assets/37884292/4a9bc6c5-9014-42bb-af9d-408a09e550d9)
The startup ui started on the 5-7th try, but it was bugged, and was stuck, i didnt get a screen shot, but this is what it would of looked like
![image](https://github.com/LavaGang/MelonLoader/assets/37884292/3c6b228a-02c9-4eb8-8d28-80614118ca14)
the next try, the game fully worked.

also the log was there but the error wasnt somehow

Game - Slime Rancher 2
ML Version - 0.6.1

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
The MelonLoader start screen is non-essential. You can temporarily work around it by using `--melonloader.disablestartscreen`

**Comment by RinLovesYou** [comment]
There is also no reason to censor what the Start Screen is saying

**Comment by TheanMcGarity** [comment]
@RinLovesYou that is what it looked like it  was empty
here is a photoshop of it with more detail (going to edit it in to the main post)
![image](https://github.com/LavaGang/MelonLoader/assets/37884292/4fb3443d-4a56-40e2-8fcf-53a5934a3bdd)
