### ISSUE TITLE
[Bug]: [ChilloutVR] --no-mods flag ignored if it's not the first flag

### ISSUE THREAD

**Issue by shininghero** [LavaGang/MelonLoader#483]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

It seems if the --no-mods flag is not the first flag, it gets ignored, causing mods to be used anyways.

Steps to reproduce:

- Set the `--no-mods` flag in steam launch options
- Launch in desktop mode
- Check CVR's command line options in Task Manager.  `--no-mods` will be the only flag.

Launched like this, it will run with mods disabled.  Now:

- Launch SteamVR, and launch ChilloutVR
- Check the command line options in Task Manager again.  It will say `-vr --no-mods`.

CVR will be running with mods, despite --no-mods being in the command line.

To demonstrate that the issue is launch option ordering:

- Set the launch options to `--no-mods -vr`
- Launch CVR in desktop mode.  Ignore the "You launched in desktop despite being in VR" warning.

CVR should now be running in VR mode, and with mods disabled.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Marking this as Completed as I can't seem to reproduce this issue with newer MelonLoader versions.
