### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EllisMurray** [LavaGang/MelonLoader#485]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Internal FailureFailed to initialize MelonLoader: Failed to load library!确定内部故障初始化MelonLoader失败:加载库失败!确定
![image](https://github.com/LavaGang/MelonLoader/assets/135338707/4ab10f8d-f429-48a2-9d0d-b3dc463e7193)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
This is most likely caused by Unicode characters in the path, similar to #497

**Comment by nervous-inhuman** [comment]
@rakosi2 I'm encountering the same error, and the path has no UTF-8 characters, just plain old ASCII. Fwiw, I'm on the latest (v0.6.2) release.
