### ISSUE TITLE
[Bug]: IL2cpp not downloading//missing file!

### ISSUE THREAD

**Issue by mikusgszyp** [LavaGang/MelonLoader#486]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/11909114/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by Slxdy** [comment]
Isnt this an android game?

**Comment by rakosi2** [comment]
Are you still having this issue? You were unable to download a file from GitHub, maybe there was an outage at the time.

**Comment by rakosi2** [comment]
Closing Issue due to no response.
