### ISSUE TITLE
[Bug]: INTERNAL FAILURE! Please upload the log file"C: Users lenovo Downloads MLInstaller 23-7-11 15-33-05.596.log'when requesting support.

### ISSUE THREAD

**Issue by asd-1-23** [LavaGang/MelonLoader#489]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

每当我尝试将MelonLoader安装到BONEWORKS上时，它只会说内部故障，并在我的下载
中创建一个.txt文件[MLInstaller_22-1-18_13-38-40.771.log]

日志文件中内容为：SHA512 Hash from Temp File does not match Repo Hash!

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
duplicate with #490
