### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by codetech101** [LavaGang/MelonLoader#492]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I have tried playing smt nocturne hd remaster with mods but every time I finish the fight with the Preta after becoming the Demi-fiend when it gets to the menu where you get money and exp it just freezes I should also mention that my playthrough on a new game plus

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
okay..? this isn't the Nocturne HD remaster github, this is the MelonLoader github. Please only open issues that occur without running any mods, as we do not make those.

**Comment by codetech101** [comment]
I was using MelonLoader for mods and it was causing the game to freeze
