### ISSUE TITLE
[Bug]: Does not load descenders

### ISSUE THREAD

**Issue by ghost** [LavaGang/MelonLoader#494]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

A cmd window popped up for like 0.1 seconds. I got the text of it which said:
Unhandled Execption: System.MissingMethodExeption: Method not found: 'System.IO.FileStream..ctor'.
    at MelonLoader.Core.Initialze () [0x00000] in <filename unknown>:0
![Uploading image.png…]()

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
game is stripped. Just needs unstripping.

https://hackmd.io/@ghorsington/rJuLdZTzK

**Comment by ghost** [comment]
> 

I've tried this. It completely fucked up my game. Game woudnt load at all. Just throw the games crash message and a error log (i can provide that if needed). I then replaced the orginal files with the fixed one, game still didnt work. Just kept giving kernelbase.dll errors :(
