### ISSUE TITLE
[Enhancement]: Attribute for RegisterTypeInIl2CppWithInterfaces

### ISSUE THREAD

**Issue by MillzyDev** [LavaGang/MelonLoader#495]
### Describe the new feature or enhancement

Similar to how the Unhollower RegisterTypeInIl2Cpp methods have an attribute for automatically registering, this feature would be an equivalent attribute but for the [RegisterTypeInIl2CppWithInterfaces methods](https://github.com/knah/Il2CppAssemblyUnhollower/blob/f583252790caaaabf1b8705bd858c7a19cddbcdf/UnhollowerBaseLib/ClassInjector.cs#L77-L79).

Example:
```csharp
using System;
using System.ComponentModel;
using MelonLoader;
using UnityEngine;

[RegisterTypeInIl2CppWithInterfaces]
public class MyBehaviourWithInterfaces : MonoBehaviour, INotifyPropertyChanged
{
    public MyBehaviourWithInterfaces(IntPtr ptr) : base(ptr)
    {
    }
    ...
}

[RegisterTypeInIl2CppWithInterfaces(logSuccess: true)]
public class MyOtherBehaviourWithInterfaces : MonoBehaviour, INotifyPropertyChanged
{
    public MyOtherBehaviourWithInterfaces(IntPtr ptr) : base(ptr)
    {
    }
    ...
}
```

**Comment by HerpDerpinstine** [comment]
Should be implemented as of https://github.com/LavaGang/MelonLoader/commit/1a33c452322f9d8fcbdd2e3be7235acde6d76422
