### ISSUE TITLE
[Bug]: Debugging doesn't work

### ISSUE THREAD

**Issue by OI3livion** [LavaGang/MelonLoader#496]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12100672/Latest.log)

I'm using dnSpy version 6.1.8 (x64), when I try to debug the game, following the steps in the wiki, it fails:

`unable to connect to the debugged process [...] make sure you have patched the mono.dll file of the game`

Unity: 5.5.3f1
net35

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
well, did you get the patched mono? https://github.com/dnSpy/dnSpy/wiki/Debugging-Unity-Games

**Comment by OI3livion** [comment]
I'm using this but no luck
https://github.com/wh0am15533/Patched-Unity-Mono/blob/main/CustomBuilds/Unity-debugging-5.x/unity-5.5.3.rar

**Comment by OI3livion** [comment]
Allright I had to compile mono.dll from the official repo, but now it works!
