### ISSUE TITLE
[Bug]: 模组加载器无法初始化/MelonLoader failed to initialize

### ISSUE THREAD

**Issue by ghost** [LavaGang/MelonLoader#497]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

游戏开始运行时直接弹出Internal Failure窗口，窗口内显示Failed to initialize MelonLoader:Load LibraryExW failed。
使用手动安装方法仍未解决，已多次尝试检查游戏文件完整性、重新下载MelonLoader、LimbusLocalize以及字体文件。
已排查网络问题：已尝试更换加速工具（Watt Toolkit、Steamcommunity 302，CFW未尝试，但我想不是这个能解决的），已检查防火墙设置，已尝试暂时关闭杀软，已证实主机能够连接上GitHub。
已尝试重新启动电脑，已尝试将企业版系统更换为专业版（密钥方式）。
已尝试更换汉化模组及附属文件版本，均未解决。
游戏本体在完全删除汉化模组文件后可以正常启动。
两个log（Latest(框架日志).log，Player(游戏日志).log）均未生成，UserLibs未生成，Plugins未生成。
错误截图见下，文件夹内文件（启动游戏后）见下。

When the game starts running, an Internal Failure window will pop up directly, displaying Failed to initialize MelonLoader: Load LibraryExW failed.
The manual installation method did not solve the problem,Multiple attempts have been made to check the integrity of game files,re-download MelonLoader,LimbusLocalize and font file.
Possibility of the Internet connection causing problems has been checked and excluded: the accelerator has been replaced many times(Watt Toolkit,Steamcommunity 302)(I haven't tried CFW or such ladders yet,but I think it neither can sovle the problem of fail to init the melonlodaer),Firewall settings have been checked and it has been confirmed that the host can connect to GitHub.
The computer has already been restarted,the system version has been changed from business version to professional version(by changing the key).
The version of the mod and the modloader has been changed,neither of them has solved the problem.
The game itself can start normally after completely removing the mod files and melonloader.
Two logs (Latest(框架日志). log, Player(游戏日志). log), UserLibs, and Plugins were not generated even afer running the game.
Please see the screenshot of the error and the files in the folder (after starting the game) below.

![image](https://github.com/LavaGang/MelonLoader/assets/98738122/2338dfd7-04e6-4ab6-9d17-c4d2c6b1e0c3)
![image](https://github.com/LavaGang/MelonLoader/assets/98738122/81c61a04-8d26-446b-8dbd-04e46006abfa)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
It is very likely that this is caused by Chinese/other unicode symbols in the path to the game.

**Comment by XiaHuaXH** [comment]
This is not a problem that occurred to me, so I'm sorry that  I couldn't provide an exact answer immediately. However, in my impression, it was placed in the default installation path of Steam under C:\ Program Files (x86).In my opinionaAlthough the system language is Chinese,this path does not contain Chinese characters, right?I have never figured this out.
Also, I'm sorry, I'm not sure if I should first publish these in the issue of that mod, but I have done it

**Comment by XiaHuaXH** [comment]
This is not a problem that occurred to me, so I'm sorry that I couldn't provide an exact answer immediately. However, in my impression, it was placed in the default installation path of Steam under C:\ Program Files (x86).In my opinion although the system language is Chinese,this path does not contain Chinese characters, right?I have never figured this out.
Also, I'm sorry, I'm not sure if I should first publish these in the issue of that mod, but I have done it.

**Comment by XiaHuaXH** [comment]
This is not a problem that occurred to myself, so I'm sorry that I couldn't provide an exact answer immediately. However, in my impression, it was placed in the default installation path of Steam under C:\ Program Files (x86).In my opinionaAlthough the system language is Chinese,this path does not contain Chinese characters, right?I have never figured this out.
Also, I'm sorry, I'm not sure if I should first publish these in the issue of that mod, but I have done it

**Comment by ghost** [comment]
This is not a problem that occurred to myself, so I'm sorry that I couldn't provide an exact answer immediately. However, in my impression, it was placed in the default installation path of Steam under C:\ Program Files (x86).In my opinion although the system language is Chinese,this path does not contain Chinese characters, right?I have never figured this out.
Also, I'm sorry, I'm not sure if I should first publish these in the issue of that mod, but I have done it.

**Comment by ghost** [comment]
I just found out that if the installation path contains non ASCII characters,,Steam cannot running at all.

**Comment by ghost** [comment]
I have found that the lack of Microsoft Visual C++2015-2019 Re distributable can cause this issue, and I overlooked this issue during troubleshooting
