### ISSUE TITLE
[Bug]: It gets scanned as a virus by AVG, now I cant install it.

### ISSUE THREAD

**Issue by NickArcadeNerd** [LavaGang/MelonLoader#498]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

AVG says its a virus, trying to install unityexplorer with it.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by NickArcadeNerd** [comment]
it says it scans something related to Alexa

**Comment by RinLovesYou** [comment]
then make an exception in your antivirus. This isn't the AVG support forum, and not a bug in MelonLoader. Many antiviruses false detect MelonLoader, because it injects into another program. The code is right here and you're free to look over if if you don't trust it.

**Comment by NickArcadeNerd** [comment]
Thx!
