### ISSUE TITLE
[Bug] : MelonLoader- INTERNAL FAILURE! failed to make logs folder!

### ISSUE THREAD

**Issue by shaneteague** [LavaGang/MelonLoader#500]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Whenever i try to start the game, it takes me to my command prompt [cmd] it says. MelonLoader-INTERNAL FAILURE failed to make logs folder! the lastest version didnt work.My game is 86x but it worked on an 64x and its taking me to my cmd and 
doing the same things  the game [car mechanic simulator 2021] is supported by mods mostly nexus mods . other people have been using Nexus mods+ Melonloader perfect but i seem to be the only one having the trouble that i'm aware of. Thank you 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
this sounds like an issue with your system's permissions, rather than MelonLoader.

**Comment by shaneteague** [comment]
> @RinLovesYou how would i fix it ?

**Comment by RinLovesYou** [comment]
look up how to give yourself permission for the folder..? Is it possible you got your game on the Microsoft Store? if so, you're kind of out of luck.

**Comment by shaneteague** [comment]
@RinLovesYou no, i didn't get my game out of microsoft store.

**Comment by shaneteague** [comment]
i got it working

**Comment by YAOSEF0** [comment]
> i got it working

how?
