### ISSUE TITLE
[Bug]: crashing when i start the game

### ISSUE THREAD

**Issue by YOnikos** [LavaGang/MelonLoader#501]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

im trying to launch the game from the vortex with no mods Loads normally when i add a mod IT Crashes all the time does anyone know how to fix it please tell me the game is called **Bloons TD6**

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
using an unsupported 3rd party launcher is outside of scope for us. We don't make vortex, whatever that is.
