### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HackerKillTTV** [LavaGang/MelonLoader#505]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12255513/Latest.log)

Failed to Download Cpp2IL! (INTERNAL FAILURE)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Internet skill issue, not a MelonLoader issue. Double check your ability to access https://raw.githubusercontent.com or switch to a better DNS. i.e. CloudFlare 1.1.1.1
