### ISSUE TITLE
[Bug]: MelonLoader BTD6 generally crashes during startup in Proton (linux)

### ISSUE THREAD

**Issue by fmpreferences** [LavaGang/MelonLoader#506]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

This happens both with GE Proton 8, Proton 8, and Experimental. Vanilla BTD is completely fine. 

Latest log attached, but it is unhelpful it because it never logs what causes the crash

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12286808/Latest.log)

![Screenshot_20230807_215923](https://github.com/LavaGang/MelonLoader/assets/57734230/cd2a8706-70eb-403a-8c89-f88f36b98207)

Note: I had to post a picture because as soon as any error occurs it crashes and closes immediately meaning I cannot actually copy the text, this was taken from a screen recording

I should have posted this ages ago. The one year anniversary of this happening is probably passed by now. 

I may have another bug report but I have even less information on why that other bug is happening. I think it is related to this problem. 

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
invalid, we don't make mods, and can't guarantee stability under proton in the first place. if this somehow happens *without* mods, feel free to open another issue.
