### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BaiBuCYBGT** [LavaGang/MelonLoader#507]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12294044/Latest.log)
https://github.com/LavaGang/MelonLoader/assets/37788089/61787ada-0b77-45c4-a545-1f2e3f89f43b
 after finish title "Starting game" , the game ,and back to epic games launcher main

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Loading a mod invalidates this issue, if you can reproduce this without mods, please open another issue.
