### ISSUE TITLE
[Bug]: not able to open game assembly

### ISSUE THREAD

**Issue by CheeseBlockmc** [LavaGang/MelonLoader#508]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

i just fixed it loading bonelib but it says cant open game assembly. so im confused somebody help.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
verify the integrity of your game, or just reinstall it.

**Comment by rakosi2** [comment]
Seems like this issue is resolved, If it wasn't, feel free to reopen it.
