### ISSUE TITLE
game opening then closing

### ISSUE THREAD

**Issue by bobthebuilder1234143** [LavaGang/MelonLoader#511]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

so it was able to open after i reinstalled it and then it just kept closing after it say unity.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/12354279/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Your log contains no errors, aside from that, we do not offer support for online pvp games.
