### ISSUE TITLE
Tunic game support

### ISSUE THREAD

**Issue by RiverLilyCC** [LavaGang/MelonLoader#514]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I'm trying to connect ML to Tunic but can't seem to get it working.
5.7 doesn't work because of the unity version ("no support module loaded")
6.0, 6.1 and nightly don't work because of unhollower support

I've included the logs for both cases

[Latest5.7.log](https://github.com/LavaGang/MelonLoader/files/12511284/Latest5.7.log)
[Latest6.1.log](https://github.com/LavaGang/MelonLoader/files/12511285/Latest6.1.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by AlphaLovesYou** [comment]
hey. would recommend going to the discord for support for this as github issues are not the best place for these kind of things.
im gonna assume the unhollower issue is caused by you not using the correct version of Unity Explorer. make sure you are using the updated fork as UE has been abandoned for some time now.

**Comment by RinLovesYou** [comment]
Not an issue with MelonLoader, simply using the [wrong UnityExplorer](https://github.com/GrahamKracker/UnityExplorer/releases)
