### ISSUE TITLE
[Bug]:ではなく質問　 Android および Oculus Quest のサポート て書いてますができません

### ISSUE THREAD

**Issue by yuyop123** [LavaGang/MelonLoader#515]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

 Oculus Quest 2 にどうやったら認識されますか
ボーンらぼ

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by yuyop123** [comment]
Oculus Quest 2　にメロンloaderは使用できますか?

**Comment by RinLovesYou** [comment]
Please form your questions in English, and don't file bug reports for questions. The Quest runs android, and you'll find a server for an Android fork of MelonLoader on the [wiki](https://melonwiki.xyz/#/android/general)
