### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cityrhath1** [LavaGang/MelonLoader#517]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

crash cmd on start with last version for war robots game please fix it

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by cityrhath1** [comment]
crash :[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...

**Comment by RinLovesYou** [comment]
we do not support modding competitive multiplayer games
