### ISSUE TITLE
[Bug]: whenever melonloader trys to load my btd6 mods it crashes

### ISSUE THREAD

**Issue by ggc2510** [LavaGang/MelonLoader#519]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

when i use melonloader on btd 6 it gets to the part where it says "loading melons" and trys to load a mod and crashes

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Please post a log.

**Comment by ggc2510** [comment]
[latest.log](https://github.com/LavaGang/MelonLoader/files/12569856/latest.log)

**Comment by RinLovesYou** [comment]
that is a minecraft log..?

**Comment by rakosi2** [comment]
Closing ticket since invalid log was provided, if you are still having this issue, you can reopen and provide the correct log.

**Comment by ggc2510** [comment]
how do i get the right log

**Comment by ggc2510** [comment]
[Latest.log](https://github.com/LavaGang/MelonLoader/files/12601406/Latest.log)
nvm i found out how

**Comment by rakosi2** [comment]
All of your mods are old or not even mods, I request that you delete all of your mods and redownload the newest versions. We can not help any further since it is a mod issue and not a MelonLoader issue.
