### ISSUE TITLE
[Bug]: Game crashes when starting

### ISSUE THREAD

**Issue by darkwarriorx0545** [LavaGang/MelonLoader#520]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Game loads all mods and when displaying "Starting game..." it hangs for a longer while and crashes. i have all dependencies installed and the latest version of melon loader (0.6.1). Im using it in Bloons TD 6 (Epic Games). I tried reinstalling BTD6, reinstalling melonloader and restarting my computer, nothing fixed crashes.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/12569876/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
You are missing BTD6EpicGamesModCompat

**Comment by darkwarriorx0545** [comment]
alright, fixed it.

**Comment by darkwarriorx0545** [comment]
i tried it and it didn't fixed it. here's the next log:
[Latest.log](https://github.com/LavaGang/MelonLoader/files/12569912/Latest.log) (some parts of it are in polish
