### ISSUE TITLE
[Bug]:  FindGameObjectsWithTag or FindObjectOfType crashes the game on startup (ori and the will of the wisps)

### ISSUE THREAD

**Issue by dashadowofcat** [LavaGang/MelonLoader#524]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12642881/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
The game must be stripped. There's really nothing much you can do about that with il2cpp games. This is not a bug with MelonLoader.

**Comment by RinLovesYou** [comment]
It is also possible you are referencing actual Unity libs instead of Il2CppInterop generated ones. Normally these methods should get unstripped.

**Comment by dashadowofcat** [comment]
> It is also possible you are referencing actual Unity libs instead of Il2CppInterop generated ones. Normally these methods should get unstripped.

thanks for the help
