### ISSUE TITLE
[Bug]: failed to download cppil2

### ISSUE THREAD

**Issue by lilwaaa** [LavaGang/MelonLoader#526]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[MelonLoader_23-09-19_14-31-19.530.log](https://github.com/LavaGang/MelonLoader/files/12664864/MelonLoader_23-09-19_14-31-19.530.log)
 
when i install melonloader v0.6.1 works perfectly, but when i use any other version that error appears

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
we do not support pirated copies of games.
