### ISSUE TITLE
[Bug]: "Failed to download UnityDependecies!"

### ISSUE THREAD

**Issue by NelDaDude** [LavaGang/MelonLoader#530]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I'm trying to mod BTD6 and I did everything that I needed to do. I got MelonLoader, the Mod Helper, and .NET 6.0 but when I open the game it says "Failed to Downlaod UnityDependencies!". How do I fix it?
<img width="960" alt="{08EAE602-7338-450B-9BE1-DCB58EF44CA8}" src="https://github.com/LavaGang/MelonLoader.Installer/assets/145769035/f63dd98d-7cbc-4fc9-9bde-543e4d03ee6f">

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Please upload a full log.

**Comment by RishishJain35** [comment]
Hi Same Problem here
[Uploading Latest.log…]()

**Comment by RishishJain35** [comment]
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13427042/Latest.log)

Same Problem here

**Comment by Rios5733** [comment]
Same here

**Comment by Daniel-WR-Hart** [comment]
Same issue with the Steam version of Disco Elysium
[Latest.log](https://github.com/LavaGang/MelonLoader/files/14158688/Latest.log)
