### ISSUE TITLE
[Bug]: Boneworks console error (no Latest.log file)

### ISSUE THREAD

**Issue by Jeliman359** [LavaGang/MelonLoader#531]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

so i fix one problem [support module not loaded], and then another issue pops up, had this issue even follow me from boneworks to bonelab (im gonna fucking lose it honestly i just wanna have fun)
![image](https://github.com/LavaGang/MelonLoader/assets/139167715/61635429-07b6-49be-9f7d-a7a59124d7d3)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Please upload a full log.

**Comment by Jeliman359** [comment]
> Please upload a full log.

did you even look at my bug report for a second? I literally selected the "No, I could not find a log file..."

**Comment by AlexFlipnote** [comment]
![image](https://github.com/LavaGang/MelonLoader/assets/19587382/7afd3660-38f5-4b4d-8c23-91db7bbb7619)

**Comment by Jeliman359** [comment]
> ![image](https://user-images.githubusercontent.com/19587382/270707876-7afd3660-38f5-4b4d-8c23-91db7bbb7619.png)

get outta here boomer kek

**Comment by rakosi2** [comment]
If you are having trouble finding the log, at least copy and paste the entire console.

**Comment by Jeliman359** [comment]
i cannot do that, the console freezes once that error appears, then it closes itself

**Comment by rakosi2** [comment]
Are you using MelonLoader 0.5.4?

**Comment by Jeliman359** [comment]
im using the latest one from the EXE installer, which is 0.6.1

**Comment by rakosi2** [comment]
Downgrade to MelonLoader 0.5.4 for Boneworks

**Comment by Jeliman359** [comment]
that did the trick, thank you

**Comment by RinLovesYou** [comment]
I refuse to believe there is no log.

**Comment by Jeliman359** [comment]
there is now since it managed to launch but it works now
