### ISSUE TITLE
Il2Cpp

### ISSUE THREAD

**Issue by Siarh** [LavaGang/MelonLoader#534]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

The game on Unity Il2Cpp, when MelonLoader is enabled, calls the Mono loader. UnityExplorer.MelonLoader.IL2CPP doesn't work, only UnityExplorer.MelonLoader.Mono, which doesn't load the data. I tried specifying the path to the loader in Config.cfg --melonloader.agfregenerate="C:\Program Files (x86)\Steam\steamapps\common\Game\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll", but the loader parameters don't change. The \Il2Cpp.dll disappears from the folder, no matter how I specify its parameters - it remains read-only.

Launch Arguments
Argument	Description
--no-mods	Launch game without loading any Plugins Mods
--quitfix	Fixes the Hanging Process Issue with some Games
--melonloader.consoleontop	Forces the Console to always stay on-top of all other Applications
--melonloader.hideconsole	Hides the Console
--melonloader.disablestartscreen	Disables the Melon Start Screen
--melonloader.hidewarnings	Hides Warnings from Displaying
--melonloader.debug	Debug Mode
--melonloader.dab	Debug Analytics Blocker
--melonloader.magenta	Magenta Console Color
--melonloader.rainbow	Rainbow Console Color
--melonloader.randomrainbow	Random Rainbow Console Color
--melonloader.maxlogs	Max Log Files [ Default: 10 ] [ Disable: 0 ]
--melonloader.maxwarnings	Max Warnings per Log File [ Default: 100 ] [ Disable: 0 ]
--melonloader.maxerrors	Max Errors per Log File [ Default: 100 ] [ Disable: 0 ]
--melonloader.loadmodeplugins	Load Mode for Plugins [ Default: 0 ]
--melonloader.loadmodemods	Load Mode for Mods [ Default: 0 ]
--melonloader.agfregenerate	Forces Regeneration of Assembly
--melonloader.agfvunity	Forces use a Specified Version of Unity Dependencies
--melonloader.agfvdumper	Forces use a Specified Version of Dumper
--melonloader.agfvunhollower	Forces use a Specified Version of Il2CppAssemblyUnhollower

### Did you attach your log file?

- [x] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
please show an image of the game folder

**Comment by Siarh** [comment]
![1](https://github.com/LavaGang/MelonLoader/assets/22790026/d997f7cb-679c-4a6f-8fd6-7995ef0c3f55)

**Comment by RinLovesYou** [comment]
We do not support the modding of competitive multiplayer games.
