### ISSUE TITLE
[Bug]: Can't open the game, mod loader 1.5.7

### ISSUE THREAD

**Issue by Huarastaca** [LavaGang/MelonLoader#535]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

i have desktop net 6.0 thingy installed
Installed version 1.5.7 for townscaper, run the app, console shows up, nothing appears wrong, game window swhos up and immediatly crashes, can't find crash report, or open crashhandler
[MelonLoader_23-10-02_12-00-25.635.log](https://github.com/LavaGang/MelonLoader/files/12783809/MelonLoader_23-10-02_12-00-25.635.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
1. Uninstall MelonLoader (with the installer)
2. Create a new shortcut to your Townscaper.exe
3. Add   `--melonloader.disablestartscreen` as a startargument (see screenshot)
4. Install MelonLoader **0.5.7**
5. Start the game through the new shortcut from now on
![shortcut](https://cdn.discordapp.com/attachments/931657977172213810/1139300833515798598/image.png?ex=651bd6d5&is=651a8555&hm=cd36c2521bbdf56e3344242f3d553486e0a95fa5dd297f3a6c06dd8967676f1c&)

**Comment by Huarastaca** [comment]
Ok thanks, will try it ouy

Em seg., 2 de out. de 2023 13:21, Attila ***@***.***>
escreveu:

**Comment by Huarastaca** [comment]
its still not working because it says, [image:
fadba0c3-7715-48c4-bdaf-3d9871791cc3.png]
the name ... specified in the target box is not valid, make sure the path
and name of the archive is correct

Em seg., 2 de out. de 2023 às 13:21, Attila ***@***.***>
escreveu:

**Comment by Huarastaca** [comment]
fyi putting it correctly still gives error
[image: image.png]

Em ter., 3 de out. de 2023 às 22:10, Alberto Huarastaca <
***@***.***> escreveu:

**Comment by Huarastaca** [comment]
at the end i figuredmy erros and i manage to open it, i'm sorry for the
headache that must be very boring for you. thx much love

Em ter., 3 de out. de 2023 às 22:11, Alberto Huarastaca <
***@***.***> escreveu:

**Comment by sashagithublol** [comment]
hi! i have the exact same problem and the solution given doesnt work, it says the name specified is not valid as @Huarastaca said. anyone know how to fix this? thanks! :]
