### ISSUE TITLE
[Enhancement]: Android support

### ISSUE THREAD

**Issue by Higor95y** [LavaGang/MelonLoader#536]
### Describe the new feature or enhancement

Maybe you can make a mod injector on Android, like you install mods and put them in the melon mods folder, or put the mod's http and melon auto installs... (personal things: I always wanted to have mods on ballons td 6 on Android but I don't have a PC for that and the one I had broke if you can do this I thank you devs and everything you achieved if you at least read what I wrote...)

**Comment by rakosi2** [comment]
Android Support is being worked on inside a fork called [LemonLoader](https://github.com/LemonLoader/MelonLoader), you can find more info on our [wiki](https://melonwiki.xyz/#/android/general)

**Comment by Higor95y** [comment]
thanks :)

**Comment by Higor95y** [comment]
but it doesn't support ballons td 6 :(

**Comment by RinLovesYou** [comment]
Then open an issue on their repo.
