### ISSUE TITLE
 Waiting for you to press enter - feel free to copy the error...  [this thing doesent work]

### ISSUE THREAD

**Issue by IamThundderZ** [LavaGang/MelonLoader#539]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[MelonLoader_23-10-07_21-22-09.842.log](https://github.com/LavaGang/MelonLoader/files/12838139/MelonLoader_23-10-07_21-22-09.842.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
We do not support multiplayer pvp games.

**Comment by IamThundderZ** [comment]
> We do not support multiplayer pvp games.

no its not like that when that shows I press enter and that doesent work
