### ISSUE TITLE
Crash on RedMatch Two[Bug]: 

### ISSUE THREAD

**Issue by MintyBits** [LavaGang/MelonLoader#542]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

The games goes all the way to the loading screen but will crash with the error 'A New Guard Page for the Stack Cannot be Created' despite me having 8gb of ram and 16gb of virtual memory available, I tried to change versions this causes the error message to
not be displayed and simply exit without warning.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12900293/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Nothing seems wrong in the log. I have not seen this game before but since it is a Online PvP game, it is possible that it contains a variant of anti-cheat which MelonLoader does not try to hide from and easily detectable. If it is the game itself closing due to modifications then there is nothing we can do.

**Comment by RinLovesYou** [comment]
Closed due to being an online pvp game
