### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mistrzuNO** [LavaGang/MelonLoader#545]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Hello my game isn't starting while i have melon loader installed into the game (BTD 6) I dont have any mods installed too so i doesn't know why is that so. I start the game as administrator tried launching it with Windows 8 compatibility. Hope you can help me ^-^.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12909287/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Dup of #541
