### ISSUE TITLE
[Bug]: UnityDependencies Installation error in Bloons TD 6

### ISSUE THREAD

**Issue by ghost** [LavaGang/MelonLoader#555]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Not Launching.log](https://github.com/LavaGang/MelonLoader/files/13063288/Not.Launching.log)
[Launching but error.log](https://github.com/LavaGang/MelonLoader/files/13063289/Launching.but.error.log)

An error is coming that UnityDependencies Cannot be installed
I have uploaded 2 log files, "Launching but error.log" is for when there were no mods installed and it loaded but still came the error and "Not Launching.log" is for when I tried to load the game with BT6ModHelper mod installed and it crashed.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Closed due to being a pirated version of the game.
