### ISSUE TITLE
[Bug]: failed to find Bootstrap

### ISSUE THREAD

**Issue by ALEZ-DEV** [LavaGang/MelonLoader#557]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13074016/Latest.log)
This log is not very useful so I tried to copy the error I got from the terminal directly
[copied.log](https://github.com/LavaGang/MelonLoader/files/13074041/copied.log)
This is for the game Punishing: Gray Raven
and when I start it from the official launcher
![image](https://github.com/LavaGang/MelonLoader/assets/38623465/4b255120-d863-4bf2-a221-82d68efef8ce)

I have already create an [issue](https://github.com/LavaGang/MelonLoader/issues/467) a few month ago and I said that all was fixed, but no because when I tried to load some mod, the mod was loaded, but the mod was to run
and this time I run the latest version of MelonLoader (6.1.0)

(PS: the game have already some issue in vanilla to start sometime)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment]
Missing Bootstrap usually means that `MelonLoader\Dependencies\Bootstrap.dll` was removed, either by the user or something like an anti-virus. Make sure that it is whitelisted and reinstall MelonLoader.

**Comment by ALEZ-DEV** [comment]
`MelonLoader\Dependencies\Bootstrap.dll` is here and not removed
![image](https://github.com/LavaGang/MelonLoader/assets/38623465/c586fa87-b4d1-4947-98c5-01af97d1860f)

**Comment by rakosi2** [comment]
Wonder why the popup is referencing `KuroGame_haru` folder instead of the `Punishing Gray Raven`.
Maybe try and install [MelonLoader Nightly](https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development/MelonLoader.Windows.x64.CI.Release.zip) and see if that helps

**Comment by ALEZ-DEV** [comment]
I installed the nighlty version of MelonLoader on PGR, but I have always the same issue

**Comment by ALEZ-DEV** [comment]
I made research on my side and it seems that the code failed to know that my game is an Mono game
I think that is the method `MonoLibrary.Setup()` in `MelonLoader\MonoInternals\MonoLibrary.cs` that fail

there is the code of the method MonoLibrary.Setup()

```
internal static bool Setup()
{
    IntPtr NativeMonoPtr = GetLibPtr();
    if (NativeMonoPtr == IntPtr.Zero)
    {
        MelonLogger.ThrowInternalFailure("[MonoLibrary] Failed to get Mono Library Pointer from Internal Call!");
        return false;
    }

    try
    {
        Instance = NativeMonoPtr.ToNewNativeLibrary<MonoLibrary>().Instance;
    }
    catch (Exception ex)
    {
        MelonLogger.ThrowInternalFailure($"[MonoLibrary] Failed to load Mono NativeLibrary!\n{ex}");
        return false;
    }

    MelonDebug.Msg("[MonoLibrary] Setup Successful!");
    return true;
}
```

but I can't go further to know how to solve this issue, if someone who have good knowledge of the project can help me would be appreciated

**Comment by ALEZ-DEV** [comment]
Okay guys, I soon found the solution, It's very funny thought

thank to @SamboyCoding (if I don't mention the wrong person) for guiding my to this solution

My issue was that the game I wanted to run just change de directorie name of  `Il2cpp_data` to `Native`, so I just tried to change the name of the file but the game was just unable to run after that, so I did something else

I just cloned the project and change the Line 43 of [MelonLoader/blob/master/MelonLoader/Utils/MelonEnvironment.cs](https://github.com/LavaGang/MelonLoader/blob/master/MelonLoader/Utils/MelonEnvironment.cs) to :
`public static string Il2CppDataDirectory => Path.Combine(UnityGameDataDirectory, "Native");`
and the game was able to run

but I had another annoying issue, it was when sometime a launched the game, it was throwing this error
`Attempted to read or write protected memory. This is often an indication that other memory is corrupt`
so I found this [Melon issue](https://github.com/LavaGang/MelonLoader/issues/433) and just put `--melonloader.disablestartscreen` argument when I start the game

but (yes another one but) UnityExplorer don't want to load in game because it said that some of the following dependencies are missing :
```
[20:47:56.210] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'UnityExplorer' is missing the following dependencies:
    - 'UnityEngine.CoreModule' v3.7.1.6
    - 'UnhollowerBaseLib' v0.4.22.0
    - 'UnityEngine.UIModule' v3.7.1.6
    - 'UnityEngine.UI' v3.7.1.6
    - 'UnityEngine.TextRenderingModule' v3.7.1.6
    - 'Il2Cppmscorlib' v3.7.1.6
    - 'UnityEngine.AudioModule' v3.7.1.6
    - 'Il2CppSystem.Core' v3.7.1.6
    - 'UnityEngine.PhysicsModule' v3.7.1.6
```
but I thing that MelonLoader is just trying to find these dependencies in the wrong directorie or somthing like that,
I will try to solve this last issue more later, but if someone find an idea to solve it, I'll take it

**Comment by rakosi2** [comment]
Do you have a virus scanner like McAfee? Missing those files usually means that a virus scanner deleted them.

**Comment by lory-dev** [comment]
Still didn't work

**Comment by rakosi2** [comment]
> Still didn't work

What do you mean by "still", this is the first time you are commenting here. What is your issue?

**Comment by AquaticVyper** [comment]
Having the same issue. I have uninstalled and reinstalled the game three times. Restarted my device multiple times. Made sure all the dependency files are there (they are). Uninstalled and Re-Installed melon loader multiple times. I have literally wiped any remnants of either Boneworks OR Melon Loader from my PC and reinstalled both CLEANLY once more and STILL I get the issue. I just don't understand what more I can do. 

I even installed it on a different drive one more time to see if that would fix it. Nope. Same issue.

**Comment by ALEZ-DEV** [comment]
@AquaticVyper what are you trying do to ?

**Comment by VadimkaG** [comment]
I have the same problem. How to fix it?

**Comment by rakosi2** [comment]
@VadimkaG please share your log file

**Comment by VadimkaG** [comment]
@rakosi2
If I understand correctly, this error does not create a log file.
As written above, bootstrap file exists.

I was able to solve the problem by installing an older version: 0.5.7.
On version 0.5.7 everything runs fine.

**Comment by hajaren1466** [comment]
This issue is still occuring. I can't use 0.6.1 or 0.6.2. The mod for the game I'm playing requires 0.6.1 and I can't use it because of the bootstrap error. The file exists. Help.

**Comment by Moyerj19370goodtogoattminus29** [comment]
for some weird reason this happened and I have it on video. 
https://outplayed.tv/media/wXVbR5

**Comment by Moyerj19370goodtogoattminus29** [comment]
trust me this is real.

**Comment by antix2137** [comment]
![obraz_2024-06-23_162238307](https://github.com/LavaGang/MelonLoader/assets/173617365/a1476394-8782-4331-913b-9cf378c608c3)
can someone plss help me

**Comment by gamerdragonryan** [comment]
![image](https://github.com/user-attachments/assets/7a8133eb-3b98-49a2-b48d-34a24729889b)
 here is what i have not sure if it loaded

**Comment by clarkbruce5348** [comment]
I am having the same issue failed to find bootstrap

**Comment by jpeaglesandkatz** [comment]
Getting frequent  [MelonLoader.Bootstrap] Runtime config not found at: .... \net6\MelonLoader.runtimeconfig.json'

using latest debug nightly because it apparently is the only one that will not outright crash the game....

Btw.. game folder is excluded from defender. Not getting the win32 GUi pop up error message but the mentioned message in the console window.... 

Sometimes it starts and loads the mod, lot of times it doesn't
