### ISSUE TITLE
[Bug]: Incorrect working directory with games launched with steam that do not have their executable in the main folder

### ISSUE THREAD

**Issue by mojobojo** [LavaGang/MelonLoader#558]
### All of the following criteria must be met

- [x] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

You can reproduce this with a fresh install onto Heartwood Online. If you do this, try to launch  through steam you get this error. 

![error](https://cdn.discordapp.com/attachments/733305093264375849/1167605813859336242/image.png)

My current solution was to create symbolic links to the game and melon loader folders like this.

![solution](https://media.discordapp.net/attachments/733305093264375849/1167610244629790740/image.png)

After I did this, melon loader works fine. 

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
That is what the basedir argument is for?

**Comment by mojobojo** [comment]
> That is what the basedir argument is for?

Wasn't even aware of it. No way I could have known given I just started using this. Good to know thats an option though. Thanks.
