### ISSUE TITLE
[Bug]: Game crashes whenever I open the game

### ISSUE THREAD

**Issue by Itouchnograss** [LavaGang/MelonLoader#560]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I just put melonloader into Bloons td 6. I checked, it was opening completely fine before. but all I did was add melonloader (I didn't do anything else I just hit the button to install the most recent version of melonloader on to btd6) and the game now wont launch. I get the error il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime.
[15:39:45.156] [ERROR] il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime. I have 0 clue what this means and I am too stupid to understand it. I Tried downloading that .net 6.0 thing and have no idea what it is or what it even does.

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
.NET 6 is a C# runtime. You need to have it installed. You can get it [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.24-windows-x64-installer)

**Comment by Itouchnograss** [comment]
Tysm! That worked
