### ISSUE TITLE
Some Melons are missing dependencies, which you may have to install and when game starts just pops up with the modded client popup in BTD6

### ISSUE THREAD

**Issue by GravityPlays** [LavaGang/MelonLoader#562]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Whenever I try to play with mod helper on BTD6 it just says "some Melons are missing dependencies, which you may have to install" and the game runs like normal as it would without melonloader or mods except it shows with the modded client popup and if I try to do no mods it just says "No support module loaded!" and the same thing happens.

without mods [Latest.log](https://github.com/LavaGang/MelonLoader/files/13199869/Latest.log)
With mod helper [Latest.log](https://github.com/LavaGang/MelonLoader/files/13199875/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment]
Hello,

Can you try the [nightly build](https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development/MelonLoader.Windows.x64.CI.Release.zip) and make sure that a virus scanner is not deleting MelonLoader files.

**Comment by GravityPlays** [comment]
The problem was McAfee real time scanning I should have checked if it was a virus scanner thank you.
