### ISSUE TITLE
[Internal Failure]: Won't install.

### ISSUE THREAD

**Issue by croakcali** [LavaGang/MelonLoader#563]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Unity Game: C:\Program Files\RotMG Exalt Launcher\RotMG Exalt Launcher.exe

I try installing the application with this Unity Game and it cuts through halfway, and I get the pop-up Internal Failure. Please help.

[MLInstaller_23-10-30_18-59-45.678.log](https://github.com/LavaGang/MelonLoader/files/13211208/MLInstaller_23-10-30_18-59-45.678.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment]
The access to a file has been denied. Please make sure the game is closed when installing MelonLoader, or try restarting your computer. If this doesn't work, try running the MelonLoader Installer with administrator privileges.
Also, it appears that you are trying to mod the launcher instead of the game, are you sure that you are installing it correctly?

**Comment by croakcali** [comment]
I don't have access the game.exe only the launcher.exe. Also how do I run it with administrative privileges.

**Comment by rakosi2** [comment]
again, modding the launcher will not mod the game
to run as admin, all you need to do is right-click exe and click on "Run as Admin"

**Comment by croakcali** [comment]
Would it be possible to mod the runtime behavior.

**Comment by rakosi2** [comment]
We can not provide any support for that game as it has anti-cheat.

**Comment by croakcali** [comment]
appreciate it.
