### ISSUE TITLE
[Bug]: Error Generating Interop Assemblies, missing dependencies, cant load mod

### ISSUE THREAD

**Issue by ShiinaRinne** [LavaGang/MelonLoader#565]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13256157/Latest.log)
I encountered this error while using  `UnityExplorer`.
I tried reinstalling the latest `Nightly MelonLoader` and the mod, and according  https://github.com/sinai-dev/UnityExplorer/issues/204 to replace `Unhollower.dll`, but none of them can be solved
May I ask where the problem may be?

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment]
Which game is that?

**Comment by ShiinaRinne** [comment]
https://www.patreon.com/posts/new-app-shoost-62585593
Shoost

**Comment by rakosi2** [comment]
Do you have a virus scanner like McAfee? Missing those files usually means that a virus scanner deleted them.

**Comment by ShiinaRinne** [comment]
No, I only have Windows Defender. And I searched for related issues before and saw this possibility, so I even disabled Defender's real-time protection, but it still couldn't be solved. 
But meloader and unity explorer work fine on other games, so I guess it may be a problem with the game itself? Or is there any good way to determine where the problem is?

**Comment by ShiinaRinne** [comment]
Today, I tried MelonLoader [v0.6.2 Open-Beta](https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.2) and [the fork version](https://github.com/GrahamKracker/UnityExplorer) of UnityExplorer again, and found that the issue has been resolved.
