### ISSUE TITLE
[Bug]: game says [BloonsTD6_Mod_Helper] Failed to apply BloonsTD6 Mod Helper patch(es) in HTML_URLChanged_t_OnResultWithInfo: "Could not load file or assembly 'Il2CppFacepunch.Steamworks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified." The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles

### ISSUE THREAD

**Issue by samkomods** [LavaGang/MelonLoader#567]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

so i have the game on epic 
and this error just started to appear 

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13257137/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
Okay? That's not a MelonLoader issue. We do not make mods for games. Please contact the mod creator.

**Comment by rakosi2** [comment]
you are missing https://github.com/GrahamKracker/BTD6EpicGamesModCompat
