### ISSUE TITLE
[Bug]: CPP2IL doesn't execute

### ISSUE THREAD

**Issue by Cosmikyu** [LavaGang/MelonLoader#568]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13257770/Latest.log)
I have tried countless times to try and fix this issue, googling it doesn't work, its like im the only one who's having this darn issue
I run the exe (Boneworks) and it loads into the MelonLoader start menu before giving me an error that says ''Failed to execute Cpp2il''

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
Buy the game.

**Comment by Cosmikyu** [comment]
But here's the darn thing, i did the exact same thing on my friend's PC and it worked fine, my friend also has the same copy of the game as me.

**Comment by CNSLZ** [comment]
> But here's the darn thing, i did the exact same thing on my friend's PC and it worked fine, my friend also has the same copy of the game as me.

Have any method to solve this now?This problem really troubles me.
