### ISSUE TITLE
Melonloader Won't Work with v0.5.5, 0.5.7 or 0.6.1

### ISSUE THREAD

**Issue by AnaNgMightBe** [LavaGang/MelonLoader#569]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

FYI, I was getting the same error others got with Melonloader 0.6.1
Game: The Long Dark v. 2.23 on Windows 7 pro SP1

After starting the game, I got the following error in a cmd window. The cmd window closed, the game didn't start. Removed 0.6.1, installed 0.5.7 and it works fine.

[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...
[NewEntryPoint] Configuring imports...
[NewEntryPoint] Initializing. In default load context: True
[NewEntryPoint] Caught exception invoking Initialize! System.IO.IOException
 handle is invalid.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.GetFileOptions(), (etc....)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by AnaNgMightBe** [comment]
Update:
I can't get MelonLader to work with any mod. Have tried v .0.5.5, .0.5.7 and .0.6.1.
I will be trying the time capsule for TLD next.
0.5.7 and 0.5.5 both crash on the MelonLoader start screen when loading the mod .dll file.

**Comment by rakosi2** [comment]
No logs inside the MelonLoader folder?

**Comment by RinLovesYou** [comment]
Windows 7 is completely unsupported. 0.6 won't work on it because the C# version we use is too high.
