### ISSUE TITLE
[Bug]: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

### ISSUE THREAD

**Issue by novasnewgroove** [LavaGang/MelonLoader#571]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

whenever i try to open BTD6 (39.0, melonloader 0.57) it crashes halfway and prevents me from launching the game.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13313416/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
you can't use 0.5.7. Use the latest nightly version.

**Comment by novasnewgroove** [comment]
new problem
il2cpp_init detour failed: It was not possible to find a compatible framework version.

**Comment by novasnewgroove** [comment]
with 0.6.1 btw

**Comment by rakosi2** [comment]
Install .Net 6.0 Desktop Runtime
