### ISSUE TITLE
[Bug]: Unable to Handle "?" Version During Remote API Call

### ISSUE THREAD

**Issue by Sapper609** [LavaGang/MelonLoader#573]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

## Prerequisites
- .NET 6.0 Runtime installed
- Windows 11 Computer
- VS 2022 

## Overview
After simply installing Melonloader to Phasmophobia, I tried to run the game and I am getting a reflection error that it is unable to handle a "?" version during the Contacting RepoteAPI call. 

## Sample of Call Stack
```
[20:26:23.109] Loading Il2CppAssemblyGenerator...
[20:26:23.144] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[NewEntryPoint] Caught exception invoking PreStart! System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Invalid version '?'. (Parameter 'version')
   at Semver.SemVersion.Parse(String version, Boolean strict) in D:\a\MelonLoader\MelonLoader\MelonLoader\Semver\SemVersion.cs:line 107
   at MelonLoader.Il2CppAssemblyGenerator.RemoteAPI.ContactHosts() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\RemoteAPI.cs:line 104
   at MelonLoader.Il2CppAssemblyGenerator.RemoteAPI.Contact() in
 D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\RemoteAPI.cs:line 51
   at MelonLoader.Il2CppAssemblyGenerator.Core.Run() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Core.cs:line 58
   --- End of inner exception stack trace ---
```

## Crash Logs
Please see the attached logs below
[CrashLogs.txt](https://github.com/LavaGang/MelonLoader/files/13359785/CrashLogs.txt)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
Phasmophobia is unsupported. It has measures against ML and we do not support it.

**Comment by rakosi2** [comment]
Phasmophobia devs has requested that we not allow MelonLoader to run on their game. Even if you get around this issue, the game will detect MelonLoader and crash itself.

**Comment by Egilchrist609** [comment]
I did not know that! Thank you for such a quick response, and respecting their wishes by not allowing this to be loaded into their game.

I will do the same and not try to find a work around.

Thank you!
