### ISSUE TITLE
There was a conflict between "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

### ISSUE THREAD

**Issue by maloadjav** [LavaGang/MelonLoader#575]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

i dont think this is a bug  of   melonloader 

i make my mod with  0.57  and its work ...  but  its always bad when i try to use  0.61  ,  0.65  

then  that error  popup  .......   

its about   System.Net.Http,  in visual  studio   was bad config  and i don know how to fixed it 

i am kind of  copying other peoples  scripts  and  test it 

### Did you attach your log file?

Select an option below

**Comment by rakosi2** [comment]
Do you have .Net 6.0 Desktop installed? https://dotnet.microsoft.com/en-us/download/dotnet/6.0#runtime-desktop-6.0.23

**Comment by maloadjav** [comment]
i dont sure but when i try to download this .net 6.0 then i got the error

[30AC:3238][2023-11-20T10:11:44]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

so i think i have been installed it .

**Comment by rakosi2** [comment]
possibly, the current version now is 6.0.25
Mods made for MelonLoader 0.5.x will crash if installed into MelonLoader 0.6.x
