### ISSUE TITLE
[Bug]: Bug while launching BTD6: "Failed to Install UnityDependencies!"

### ISSUE THREAD

**Issue by AvKlol** [LavaGang/MelonLoader#577]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Whenever I launch BTD6, it loads with the error message shown in the title. It does launch, however, my mods and mod helper do not work. Is there any solution to this? (I have downloaded Visual Studio btw)
P.S: i checked the issues, and i did not find an answer that worked for me
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13427964/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by AvKlol** [comment]
sorry, that was the incorrect log file, here it is:
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13428135/Latest.log)

**Comment by rakosi2** [comment]
Try installing [Nightly](https://nightly.link/LavaGang/MelonLoader/actions/runs/6542693035/MelonLoader.Windows.x64.CI.Release.zip)
if that doesn't work then make sure that proxy is disabled on windows's settings

**Comment by AvKlol** [comment]
got it, also, my game isnt saving, any pointers?

**Comment by AvKlol** [comment]
nightly didnt work, also, this is my proxy settings, what should i do??
![image](https://github.com/LavaGang/MelonLoader/assets/98375406/943c9146-da83-40a3-8b22-5205654b5ff7)
im gonna upload another latest log file here:
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13450008/Latest.log)
btw, cant i just download the dependencies to the directory? (idk which one so you gotta help me out on that)

**Comment by PetrSeifert** [comment]
Same problem on another game. Proxy is disabled. 
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13847830/Latest.log)
