### ISSUE TITLE
[Bug]:  System.AccessViolaticnlxception: Attempted to read or write protected memory. This is often an indicationnat other memory is corrupt.at I12CppInterop.Runtime.Injection.

### ISSUE THREAD

**Issue by yuanfeng-net** [LavaGang/MelonLoader#580]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [x] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Class::Init signatures have been exhausted, using a substitute!atal error. System.AccessViolaticnlxception: Attempted to read or write protected memory. This is often an indicationnat other memory is corrupt.at I12CppInterop.Runtime.Injection. InjectorHelpers.hkGetlypelnfoFromlypeDefinitionIndex(Int32)at I12CppInterop.Runtime.Injection. InjectorHelpers.hkClassFromlame(I12CppInterop.Runtine.Runtime. I12CppImage*，IntPtiIntPtr)at I12CppInterop.Runtime.IL2CPP.i12cpp_class_from name(IntPtr, System. String, System. String)at I12CppInterop.Runtime.IL2CPP.GetI12CppClass(System. String, System String, System. String)at I12CppSystem Void..cctorat System Runtime.CompilerServices.RuntimeHelpers.assConstructor(System RuntimeTypeHandle)I12Cppmscorlib,Version=4.0.0.0,Culture=neutrat I12CppInterop.Runtime.I12CppClassPointerStorePublicKeyToken=nul1]J..cctor()at I12CppInterop.Funtime.Injection.ClassInjector.ConvertStaticllethod(VoidCtorDelegate, System. String, I12CppInterop.ntime.Runtime.VersionSpecific.Class.INativeClassStructat I120ppInterop.Runtime.Injection.ClassInjector.RegisterlypelnI120pp (System.Type, I12ppInterop.Runtime.Injection.Reisterlypelptionsat I12CppInterop.Funtime.Delegatesupport.ConvertDelegatellSystem. Canon, System. Private.Corelib, Version=6.0.0.0,Cture=neutral，PublicKeyToken=7cec85d7bea7798e]](System Delegate)at UnityEngine.Events.UnityAction 21lUnityngine. Scenellanagement. Scene, UnityEngine. Corellodule, Version=0.0.0.0,Cultrre=neutral，PublicKeyToken=nu11]，IUnityEngine.Sceneanagement.LoadSceneode, UnityEngine.Corellodule, Version=0.0.0.0，(dlture-neutral，Publickeyloken-nul1)1.0p Implicit System. Action <(UnityEngine. Sceneanagement.Scene,UnityEngine. Scenelaragement.LoadScenellode>)MelonLoader.Support.SceneHandler.InitatatMelonLoader.Support.Main.Initialize(lelonLoader

### Did you attach your log file?

Yes, I attached my log file to the text box above.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13439236/Latest.log)

**Comment by RinLovesYou** [comment]
Please upload the log file, don't just paste parts of it.

**Comment by yuanfeng-net** [comment]
OK,I send the log file

**Comment by ejektaflex** [comment]
I also got this same issue, but it crashes without outputting the error into the log. It's the exact same read-write protected memory error trace.

**Comment by KryptoST** [comment]
I have the same problem, the registry is from version 0.6.1 but it also happens with 0.6.2
[Latest.log](https://github.com/LavaGang/MelonLoader/files/14085603/Latest.log)

**Comment by Dynamixus** [comment]
Why is this marked as completed XD what's the fix or reason for this error?
