### ISSUE TITLE
[Bug]: Melon loader crashing every single time i try to play and I have no idea why

### ISSUE THREAD

**Issue by msfnxy** [LavaGang/MelonLoader#581]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

 E
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13450779/Latest.log)
verything seems to install perfectly fine to the point of melon saying "launching game" but it just crashes. I'm getting no errors or anything everything loads correctly but it just insta crashes as soon as its done.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment]
Do you still crash if no mods are installed, Just MelonLoader 0.5.7

**Comment by msfnxy** [comment]
> Do you still crash if no mods are installed, Just MelonLoader 0.5.7

yeah ive tried uninstalling every mod, still crashes, vanilla works just fine and boots no problem

**Comment by NeroWT** [comment]
Any news on this type of crash? I am looking to installing this specific version of melon loader because of a single mod i really want for Car mechanic simulator 21, is it perhaps that i am using a microsoft store version instead of the steam one?

**Comment by msfnxy** [comment]
> Any news on this type of crash? I am looking to installing this specific version of melon loader because of a single mod i really want for Car mechanic simulator 21, is it perhaps that i am using a microsoft store version instead of the steam one?

I asked around the community and currently its bugged so you would need to use steam verison
