### ISSUE TITLE
[Bug]: melonloader keeps crashing on btd6

### ISSUE THREAD

**Issue by Diamondgamer96** [LavaGang/MelonLoader#582]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

help with this pls

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Duplicate of https://github.com/LavaGang/MelonLoader/issues/541

**Comment by Diamondgamer96** [comment]
Stop
