### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EvilMrFinn** [LavaGang/MelonLoader#584]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

i am having trouble getting bonelib to work on my quest 2. if you have any suggestions please tell me and yes melon loader is installed

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Open an Issue at LemonLoader https://github.com/LemonLoader/MelonLoader/issues or join the Discord https://discord.gg/RAFGe33Y28
