### ISSUE TITLE
[Bug]: i get an error when i try to install and it told me to send this file

### ISSUE THREAD

**Issue by Scrambl2763** [LavaGang/MelonLoader#586]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[MLInstaller_23-11-28_14-40-06.546.log](https://github.com/LavaGang/MelonLoader/files/13492384/MLInstaller_23-11-28_14-40-06.546.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment]
Redownload the installer to use the latest version

**Comment by xery6dc9** [comment]
And, the same issue was here. But... I was literally having my game opened in the background and that was the reason.
I wonder when tf I became so careless even after spending hours on github, computer and all other techy shits.
