### ISSUE TITLE
[Bug]: loading screen and then crash

### ISSUE THREAD

**Issue by Sioscottecs23** [LavaGang/MelonLoader#588]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

v0.5.7, cause the fp and the modui tell me this ver. When i launch the game (zero mods in the Mods folder) I see the melonloader loading screen for a second and then a new window with the icon of the game (townscaper) and a “!” hovering it.

[MelonLoader_23-12-02_15-08-08.272.log](https://github.com/LavaGang/MelonLoader/files/13536504/MelonLoader_23-12-02_15-08-08.272.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by Sioscottecs23** [comment]
pls help

**Comment by rakosi2** [comment]
Townscaper crash fix
Uninstall MelonLoader (with the installer)
Create a new shortcut to your Townscaper.exe
Add   `--melonloader.disablestartscreen` as a startargument
Install MelonLoader 0.5.7
Start the game through the new shortcut from now on
