### ISSUE TITLE
[Crash]: DO NOT DELETE HAVE BTD6 MELON LOADER INSTALLED

### ISSUE THREAD

**Issue by Diamondgamer96** [LavaGang/MelonLoader#589]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [ ] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

so when i install melon loader it just crashes when it loads command prompt when it finishes. then i install mods doesnt work
i use epic games 
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13626548/Latest.log) here is the log idk what the hell is wrong

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by Diamondgamer96** [comment]
pls dont delete i have log and melonloader installed

**Comment by RinLovesYou** [comment]
Fixed in nightly. Please refer to the #btd6 channel in our [discord](https://discord.gg/2Wn3N2P) for install instructions. Duplicate of #541
