### ISSUE TITLE
[Bug]: Failed to get function pointer: il2cpp_init

### ISSUE THREAD

**Issue by Airy-Tian** [LavaGang/MelonLoader#590]
### All of the following criteria must be met

- [ ] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I have tried both nightly and latest stable release.

<img width="730" alt="image" src="https://github.com/LavaGang/MelonLoader/assets/81451357/974624c1-729a-4c35-89d2-05af2677164a">

Only Latest-Bootstrap.log was found in MelonLoader folder
[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/13695017/Latest-Bootstrap.log)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Reread the requirements page https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements

**Comment by rakosi2** [comment]
Wait, nvm, this is a miHoYo game, they are most likely blocking MelonLoader. we can't and won't support this game.
