### ISSUE TITLE
[Bug]: MelonLoader crashes for Death Must Die

### ISSUE THREAD

**Issue by damianolszewski** [LavaGang/MelonLoader#591]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Bug occurs for game Death Must Die.
Versions 0.6.1 and 0.6.0 don't work and crash instantly. Console windows pops up and instantly stops working. Game doesn't launch.
For version 0.5.7 it does work but during loading it crashes and this error occurs:
![Screenshot_48](https://github.com/LavaGang/MelonLoader/assets/44201801/560a4cc7-f570-4021-8257-8cc96e576391)
And this is visible in logs:
```
[20:13:08.718] [MelonStartScreen] Initializing...
[20:13:08.741] [MelonStartScreen] Using Start Screen Theme: "Default"
[20:13:10.147] [MelonStartScreen] [ERROR] Exception while rendering: System.NotImplementedException: The method or operation is not implemented.

  at UnityPlayer.GfxDevice.WaitForLastPresentationAndGetTimestamp (System.UInt32 deviceType) [0x00038] in <458ba450aca74195b4ba3d1c13011f5d>:0 

  at MelonLoader.MelonStartScreen.ScreenRenderer.Render () [0x00025] in <458ba450aca74195b4ba3d1c13011f5d>:0 
```
It works if I add --melonloader.disablestartscreen to steam start commands but Unity playback engine then crashes while exiting the game (which isn't that big of a problem because you already exit the game but the error still pops up so it is annoying)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
You can disable the start screen with a launch option, which you can find in the Readme. That will get you further on 0.6.1

**Comment by damianolszewski** [comment]
> You can disable the start screen with a launch option, which you can find in the Readme. That will get you further on 0.6.1

That only helps on 0.5.7.
On 0.6.1 it doesn't even launch and instantly crashes after cmd window pops up.

**Comment by cwz3658** [comment]
I had the same issue. Disabling the start screen is actually working.
--melonloader.disablestartscreen
