### ISSUE TITLE
[Bug]: i am downloading melonloader for cms 2021 and it needs to be a 5.0.7 version but i keep getting the "Failed to Download Cpp2il" please help!!

### ISSUE THREAD

**Issue by Stormy0o0** [LavaGang/MelonLoader#593]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

 i keep getting the "Failed to Download Cpp2il" please help!!  i tried everything all the proxy solutions  like EVERYTHING!!!!
[MelonLoader_23-12-24_20-10-07.017.log](https://github.com/LavaGang/MelonLoader/files/13763459/MelonLoader_23-12-24_20-10-07.017.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RaDeleon** [comment]
Make sure you dont have Last Epoch blocked in your firewall and maybe unblock unity crash handler as well. Fixed it for me.
