### ISSUE TITLE
[Bug]: Error Generating Interop Assemblies

### ISSUE THREAD

**Issue by Cozak92** [LavaGang/MelonLoader#600]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13848772/Latest.log)

Please look at the log, nothing works after I only installed MelonLoader and tried to run it, but an error like that occurs.

I think my issue is same with [this](https://github.com/LavaGang/MelonLoader/issues/565#issue-1977240759)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
Should already be fixed on newer MelonLoader versions.
