### ISSUE TITLE
[Bug]: Farthest Frontier: Could not load TimeManager from assembly

### ISSUE THREAD

**Issue by Turreaux** [LavaGang/MelonLoader#601]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13854642/Latest.log)
I keep getting the mentioned TimeManager error when launching. The game plays but does not load any mods. I have re-installed everything and have VB22 community installed.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
Those are issues with mods not made by us. You should contact the mod creators.
At least one of them was made for MelonLoader 0.5.7 or below
