### ISSUE TITLE
[Bug]: MelonLoader crashes abruptly while loading The Long Dark

### ISSUE THREAD

**Issue by SlavBerd** [LavaGang/MelonLoader#603]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Trying to use mods in The Long Dark, MelonLoader opens for a few seconds before closing in the middle of loading the mods. Removing the specific mods that it crashes while loading does not change the time it takes before crashing.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13881064/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
That's a lot of mods. We don't make mods. This is only for issues with MelonLoader itself. If you are experiencing issues without mods, please open another issue.
