### ISSUE TITLE
[Bug]: failed to download cpp2IL

### ISSUE THREAD

**Issue by lipaneeek** [LavaGang/MelonLoader#604]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I tried everything to fix this,but it just doesn't work. I tried running those 2 commands and still nothing.Tried to instal cpp2IL files and nothing.Please somebody help me
[Latest.log](https://github.com/LavaGang/MelonLoader/files/13929321/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by SamboyCoding** [comment]
Pirated games are not supported. Buy the game.
