### ISSUE TITLE
[Bug]: il2cpp_init failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime

### ISSUE THREAD

**Issue by carghoul** [LavaGang/MelonLoader#605]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

il2cpp_init failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime says this every time I try to launch btd6 even though I have already installed the .NET 6.0 runtime 
There is also no latest . log file

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
not a bug. Install the [.NET 6 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). (Desktop Runtime x64)

**Comment by marcusyoung77** [comment]
I'm experiencing the same issue. I installed .NET 6.029 and am still getting this error. I did the entire process as prescribed. When it did not work, I restored my computer to a previous restore point and tried again. Same error each time. Would love some other troubleshooting steps.
