### ISSUE TITLE
[Bug]: MelonLoader boots, but crashes and instantly closes

### ISSUE THREAD

**Issue by agent-bono** [LavaGang/MelonLoader#609]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

So. I start Bonelab on first boot up, and it starts the Melonloader but, It displays an error for a split second and vanishes. 
![image](https://github.com/LavaGang/MelonLoader/assets/140586139/8c7d456a-3c69-4460-8180-8ac961948c3d)
Any helpers?

### Did you attach your log file?

Select an option below

**Comment by AlphaLovesYou** [comment]
please attach your log file not just send a image of it.

**Comment by agent-bono** [comment]
Ph i figured it out. Just needed to remove bonelab shortcut from desktop.
