### ISSUE TITLE
[CRASH]: ive tried everything someone please help me with this!

### ISSUE THREAD

**Issue by INTERNAL35** [LavaGang/MelonLoader#610]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/14105085/Latest.log) it just crashes after like 15 secinds of melon loader

**Comment by AlphaLovesYou** [comment]
please attach the log file not just send a copy and paste from it.

**Comment by INTERNAL35** [comment]
> please attach the log file not just send a copy and paste from it.

idk how to do that i think i done it
