### ISSUE TITLE
[Bug]: A new guard page for the stack cannot be created

### ISSUE THREAD

**Issue by dropalways** [LavaGang/MelonLoader#612]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/14141952/Latest.log)

try load up
>loads till 90% and crashes

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
Online pvp games are not supported. They likely have anticheat & we don't support cheating anyways.
