### ISSUE TITLE
Crash of MelonLoader

### ISSUE THREAD

**Issue by MORKOVICH2010** [LavaGang/MelonLoader#613]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/14145708/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by psyellas** [comment]
use 0.5.7
