### ISSUE TITLE
Bump Il2CppInterop version to 1.4.6-ci.394

### ISSUE THREAD

**Issue by ALLMarvelous** [LavaGang/MelonLoader#615]
### Describe the new feature or enhancement

Bump the Il2CppInterop version to `1.4.6-ci.394`. This version fixes a bug in which non-blittable value types are not constructed like objects

https://github.com/BepInEx/Il2CppInterop/commit/a34205408f9b357bd0ae0ea0df324258d9e139d1

**Comment by RinLovesYou** [comment]
Done in [3fc3423](https://github.com/LavaGang/MelonLoader/commit/3fc3423dcee78c59d7d33c4bb3a07d04706ab662), leaving this open for you to test [this run](https://github.com/LavaGang/MelonLoader/actions/runs/7789057259) when it's done. Please close if everything works as expected

**Comment by ALLMarvelous** [comment]
Works as intended, thank you.
