### ISSUE TITLE
[Bug]: "Failed to initialize MelonLoader: LoadLibraryExW failed"

### ISSUE THREAD

**Issue by therealcheckweck** [LavaGang/MelonLoader#617]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

at first i had vcruntime.dll issue but with sometweaking i managed to fix it i guess.
but now i incountered a bigger problem with MelonLoader because when i try to open btd6
it says this :
"Failed to initialize MelonLoader: LoadLibraryExW failed"
pls help me bcs i rly wanna play modded btd6 its my first time trying it

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by psyellas** [comment]
its either:
have special characters in your path
you are missing dobby.dll
get this https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by therealcheckweck** [comment]
can you explain more about speacial characters in my path? @psyellas

**Comment by therealcheckweck** [comment]
THANK you so much bro you litrely saved me i can play modded now

**Comment by bloonsfan8932** [comment]
i downloaded the  https://aka.ms/vs/16/release/vc_redist.x64.exe and melon loader started but the game doesnt can someone help??

**Comment by Kidcross** [comment]
Same here it still has the error

**Comment by j4yj** [comment]
same here

**Comment by KibblesTheKitten** [comment]
Upload the filepath to the game please. Any special charcters like chinese or with accents can cause this

**Comment by Deadpool703** [comment]
it said an other version of the dobby is installed please help.

**Comment by gleb-a11y** [comment]
> не могли бы вы подробнее рассказать о специальных символах на моём пути? @psyellas

F:\SteamLibrary\steamapps\common\Desktop Mate
