### ISSUE TITLE
[Bug]: Games with launchers get terminated with "Not a unity process"

### ISSUE THREAD

**Issue by HookedBehemoth** [LavaGang/MelonLoader#618]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

The latest version of MelonLoader will abort the game launch if MelonLoader is injected into a non-Unity Application.
Games that utilize launchers which also import the version.dll will therefore halt for no apparent reason.
I changed the bootstrap & proxy code to just eprintln the error instead of aborting and the game works fine now.
[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/14230735/Latest-Bootstrap.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
Fixed in v0.6.3
