### ISSUE TITLE
btd6 crashes everytime it opens

### ISSUE THREAD

**Issue by noobronin** [LavaGang/MelonLoader#619]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/14234010/Latest-Bootstrap.log)
is just says [12:43:02.877] [ERROR] il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by psyellas** [comment]
install net 6 runtime then: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.26-windows-x64-installer

**Comment by noobronin** [comment]
ty it now works

**Comment by Mortis23** [comment]
But it didn't work for me... I've got still the same error message
