### ISSUE TITLE
[Bug]: When i try to install it for btd6 

### ISSUE THREAD

**Issue by kingacej** [LavaGang/MelonLoader#621]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

it crashes and makes an error saying internal failure please upload the log file and gives me this.
[MLInstaller_24-2-15_18-01-50.375.log](https://github.com/LavaGang/MelonLoader/files/14303329/MLInstaller_24-2-15_18-01-50.375.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
This often indicates there were issues downloading the install package from the Releases page.
I recommend following the Manual Installation guide in the README as an alternative to using the Installer.
