### ISSUE TITLE
[Bug]: When I put mods in, it crashes

### ISSUE THREAD

**Issue by CoolK66** [LavaGang/MelonLoader#622]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

![Screenshot (312)](https://github.com/LavaGang/MelonLoader/assets/93165621/e2ca0b34-f09d-487e-9f99-00b7582b5ebc)
this is what it says right before it crashes. Please help!

### Did you attach your log file?

Select an option below

**Comment by KibblesTheKitten** [comment]
Your culprit is right on your start menu. Mcaffe will delete any melon loader files it can see. You need to uninstall it and then re install melon loader
