### ISSUE TITLE
Crash cms 2021 Windows store edition

### ISSUE THREAD

**Issue by darkness3285** [LavaGang/MelonLoader#623]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Hello, I have tried to install melonloader, but the latest version gives me a bootstrap error, I tried to use the automatic installation and Windows does not allow me to use it because I require permissions. I tried using an older version of the melonloader, but the game keeps crashing. I have reinstalled it and it still continues doing the same thing.  CMS 2021 Windows store version.
[Latest.log](https://github.com/LavaGang/MelonLoader/files/14322895/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by psyellas** [comment]
for automatic install you need to install it on gamelauncher helper

**Comment by darkness3285** [comment]
Sorry but I don't understand, I tried to use the automatic installation but when selecting the .exe file it asks me for permissions. Unfortunately I haven't been able to get it to work.

**Comment by KibblesTheKitten** [comment]
The Microsoft store version can't be modded as melon loader will not work with it
