### ISSUE TITLE
i just got a new asus laptop and cant run it anymore [Bug]: 

### ISSUE THREAD

**Issue by armicool** [LavaGang/MelonLoader#624]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

![Screenshot 2024-02-20 214902](https://github.com/LavaGang/MelonLoader/assets/160599295/4711be9c-8adb-4039-b575-4b85f46009b8)

this is what i was met with over the 100 attempt's, it was really confusin, any ideas?
 

### Did you attach your log file?

Select an option below

**Comment by Jonyboylovespie** [comment]
Your antivirus is deleting files, sometimes with new laptops, companies like to install software like antiviruses on there to get you to use them. Go to installed apps in settings and look through all to see if any are antiviruses, if they are, uninstall them, then once finished, reinstall melonloader. This should fix your issue.
