### ISSUE TITLE
[Bug]: Latest version crashes TLD on startup, no log output

### ISSUE THREAD

**Issue by Kazcade** [LavaGang/MelonLoader#627]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Melon Loader 0.6.2 in combination with TLD crashes on startup, throwing an "Internal Failure" stating that it "Failed to load original DLL". Prior version (0.5.7) worked fine but unfortunately is not compatible with newer mods. Any help would be appreciated.

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
known issue, please downgrade to 0.6.1 or use the latest nightly from alpha-development if you're so inclined. Will keep this open until that version releases

**Comment by Kazcade** [comment]
Unfortunately both 0.6.0 and 0.6.1 fail with a "System.IO.IOExcpetion: Handle invalid [...]" error. Only 0.5.7 works as expected.

**Comment by KibblesTheKitten** [comment]
Modern mods with 2.27 require 0.6.1. the I/O exception smells like an antivirus thing

**Comment by HerpDerpinstine** [comment]
Fixed in v0.6.3
