### ISSUE TITLE
[Bug]: Cant find melonloader bootstrap

### ISSUE THREAD

**Issue by badcppdev** [LavaGang/MelonLoader#630]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When i try to start BONEWORKS with melonloader it says "Could not find bootstrap", or "Could not find original DLL"
![AHHHHHH](https://github.com/LavaGang/MelonLoader/assets/163696290/3cb6acda-af92-4ed2-93c9-ed809ba456e0)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Bonelab uses version 0.5.7, you have to downgrade melonloader. However this does detail some issues with the basedir argument that will be tackled in the rewrite so i may leave this open

**Comment by badcppdev** [comment]
> Bonelab uses version 0.5.7, you have to downgrade melonloader. However this does detail some issues with the basedir argument that will be tackled in the rewrite so i may leave this open

I'm using boneworks. Does this still apply?

**Comment by psyellas** [comment]
boneworks uses 0.5.4

**Comment by badcppdev** [comment]
> boneworks uses 0.5.4

I tried 0.5.4 but the game crashes when it opens

**Comment by rakosi2** [comment]
Reinstall MelonLoader 0.5.7 and make sure that virus scanners like McAfee or Webroot doesn't delete files from within the MelonLoader folder.

**Comment by badcppdev** [comment]
> Reinstall MelonLoader 0.5.7 and make sure that virus scanners like McAfee or Webroot doesn't delete files from within the MelonLoader folder.

I dont have any antivirus software, and bootstrap.dll is still there

**Comment by amzaldua** [comment]
Please, @RinLovesYou, could you fix this matter?
This is not the first issue related with it. What information do you need?

![Captura de pantalla 2024-03-27 113853](https://github.com/LavaGang/MelonLoader/assets/116205677/9bff112b-8711-43de-9c0f-c563bc9f794f)
![Captura de pantalla 2024-03-26 225710](https://github.com/LavaGang/MelonLoader/assets/116205677/f609722b-9c10-45f6-a5c7-0bbfa649133f)

**Comment by Supersaiyongodgs** [comment]
use revo uninstaller and then downlode it agan

**Comment by rakosi2** [comment]
sounds like you are missing one of the requirements (.NET 6.0) link is in the OP

**Comment by badcppdev** [comment]
> sounds like you are missing one of the requirements (.NET 6.0) link is in the OP

I do.
