### ISSUE TITLE
[Bug]: Quest 2 cant use this folder

### ISSUE THREAD

**Issue by Rickeyrabbittt** [LavaGang/MelonLoader#633]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

on quest 2, lemon installer cant access data folder, cant provide permission

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by psyellas** [comment]
THIS IS MELONLOADER

**Comment by RinLovesYou** [comment]
This is MelonLoader, not [LemonLoader](https://github.com/LemonLoader/MelonLoader).
