### ISSUE TITLE
melon loader failed to load library

### ISSUE THREAD

**Issue by PROSKAAAAA** [LavaGang/MelonLoader#642]
### All of the following criteria must be met

- [ ] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

i didnt installed the visual studio but i have newer version of it also i dont have latest.log

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by KibblesTheKitten** [comment]
Failed to load library is a normal issue of melon loader 0.6.2. please make sure you are using a version of ml made for the game you are trying to use melon with

**Comment by HerpDerpinstine** [comment]
Fixed in v0.6.3

**Comment by Luc1us23** [comment]
i got this error right now how to fix this?
