### ISSUE TITLE
[help me]: Im trying to download for cms 2021 it wont work

### ISSUE THREAD

**Issue by Ripslasher22** [LavaGang/MelonLoader#644]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

when I try to choose my exe it says you dont have permission to open this file btw I am using xbox app
![Screenshot 2024-05-01 095431](https://github.com/LavaGang/MelonLoader/assets/168666127/c71de0d1-11db-4712-ac9b-9be39d85cf68)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by KibblesTheKitten** [comment]
Melon loader doesn't works with CMS 2021 if it's downloaded from Microsoft store.
