### ISSUE TITLE
[Bug]: btd6 and mellon loader

### ISSUE THREAD

**Issue by placki1142** [LavaGang/MelonLoader#646]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

i have bug when i start btd6 with melon loader it normaly start but after i click on "start",black screen apear and in the center write"loading" i waited about 15 minuts.
![Zrzut ekranu 2024-05-11 154921](https://github.com/LavaGang/MelonLoader/assets/169539280/e2ab2766-f26c-4a5b-811d-dac3bed184ac)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by DarkTerraYT** [comment]
ask for help in the [btd6 mod helper](https://discord.gg/NnD6nRH) discord since melon loader isn't specifically for btd6
