### ISSUE TITLE
[Enhancement]: Use mod folders

### ISSUE THREAD

**Issue by Arkhorse** [LavaGang/MelonLoader#647]
### Describe the new feature or enhancement

BepInEx uses mod folders, which allows for things like a `mod.json`, which can define things like if the mod is enabled or any other things that game needs. Doing this in ML would make things easier to manage for both mod makers and mod users.

**Comment by RinLovesYou** [comment]
Planned for the rewrite 👍🏻

**Comment by HerpDerpinstine** [comment]
Bumping this to be worked on for the next v0.6.6 release.

**Comment by HerpDerpinstine** [comment]
This should now be Resolved in v0.6.6
