### ISSUE TITLE
[Bug]: Melons loander ошибка

### ISSUE THREAD

**Issue by Myza1** [LavaGang/MelonLoader#649]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'AlternativeActionUtilities' is missing the following dependencies:
    - 'ModSettings' v1.9.0.0
- 'CarryWeightMod' is missing the following dependencies:
    - 'ModSettings' v1.9.0.0
- 'SonicMode' is missing the following dependencies:
    - 'ModSettings' v1.9.0.0

### Did you attach your log file?

Select an option below

**Comment by Myza1** [comment]
я пытался установить и переустановить  и качал готовый лаунчер не что не помогало  мне

**Comment by HerpDerpinstine** [comment]
No Log file provided. Closing for being Invalid.
