### ISSUE TITLE
[Bug]: Failed to initialize MelonLoader: Failed to load library 

### ISSUE THREAD

**Issue by MeynethG** [LavaGang/MelonLoader#650]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

So i installed MelonLoader for SRMP2( multiplayer mod for Slime Rancher 2), MelonLoader 0.6.1, and it says that, i've looked everywhere to fix it but nothing works. I did the same exact steps on my gf computer and it worked, the only difference (i believe) is that her computer is running on win 11 while mine is still on 10. I tried reinstalling the game, downloading it from another website, reinstalling melon loader multiples times, same for all the requirements, i even tried uploading the files of my gf on drive to dl them on my computer but nothing works. Does anyone know how i could fix this ?

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by KibblesTheKitten** [comment]
With cracked games we can't provide help. And that downloaded from a different website is what makes me think of it
