### ISSUE TITLE
[Bug]: Failed to loading original DLL

### ISSUE THREAD

**Issue by feerd21** [LavaGang/MelonLoader#655]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

![Screenshot_1](https://github.com/LavaGang/MelonLoader/assets/171524643/6259310f-f0b4-40f2-8152-7a848fb7314d)

### Did you attach your log file?

Select an option below

**Comment by KibblesTheKitten** [comment]
Try using 0.6.1 or 0.6.3 nightly

**Comment by feerd21** [comment]
gave the same error as the other
![Screenshot_2](https://github.com/LavaGang/MelonLoader/assets/171524643/35e386a6-26c4-42de-b3c6-cdfe3715a2d6)

**Comment by feerd21** [comment]
I managed to install the mod loader, but when I try to enter the game, it closes
![Uploading Screenshot_3.png…]()

**Comment by KibblesTheKitten** [comment]
> gave the same error as the other
> ![Screenshot_2](https://github.com/LavaGang/MelonLoader/assets/171524643/35e386a6-26c4-42de-b3c6-cdfe3715a2d6)
> 

Here it's complaining about you having modhelper, which is a mod, inside the plugins folder

**Comment by HerpDerpinstine** [comment]
Fixed in v0.6.3
