### ISSUE TITLE
[Bug]: Failed to load Melon Assembly

### ISSUE THREAD

**Issue by mateokladaric** [LavaGang/MelonLoader#657]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

![image](https://github.com/LavaGang/MelonLoader/assets/52569856/b1f2ee94-2e3c-4fd3-be58-f087c3f90be0)

![image](https://github.com/LavaGang/MelonLoader/assets/52569856/e7b6e921-b477-485e-a7f3-a5ec740e8737)
![image](https://github.com/LavaGang/MelonLoader/assets/52569856/542181af-6aba-4f6d-8840-97e7399fab67)

Il2CPP game, can't load the thing, followed the wiki as best as I could, only issue I see is the blurry line as to how it should look when it comes to IL2CPP games, but I think I got it correctly.

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by KibblesTheKitten** [comment]
What is the game?

**Comment by mateokladaric** [comment]
RF4

**Comment by KibblesTheKitten** [comment]
Just asked it because you scribbled it out for... Literally no reason, only to make it harder to help
