### ISSUE TITLE
melonloader fails to find the file "System.Runtime"

### ISSUE THREAD

**Issue by Pane82** [LavaGang/MelonLoader#658]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

hi, the game is bonelab it worked until yesterday, and now don't work any more idk what happend, beacuse i didn't modify anythink...
i tried to remove the incriminated mods but same problem for every mod...
[Latest.log](https://github.com/user-attachments/files/15752536/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by Pane82** [comment]
we are in two having this problem

**Comment by SamboyCoding** [comment]
Bonelab got updated, community will be moving to MelonLoader 0.6. Please ask in your local Bonelab modding server for more information.
