### ISSUE TITLE
failed to load support module 

### ISSUE THREAD

**Issue by amp278484** [LavaGang/MelonLoader#662]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/15830130/Latest.log)

the game starts like normal and bloons loads and works but the mods option on the home screen is not there

and the melon loader console shows no support module loaded

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by KibblesTheKitten** [comment]
Melon loader couldn't generate assemblies for some reason.

**Comment by amp278484** [comment]
what does that mean for the problem I'm facing

**Comment by HerpDerpinstine** [comment]
Reinstall ML and it should regenerate the assemblies.

**Comment by amp278484** [comment]
it was an issue with my previous device using a new one fixed the issue
