### ISSUE TITLE
[Bug]: System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by khotaonickvai** [LavaGang/MelonLoader#675]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

i get this bug when try add melonloader to dark riddle, the mod and game crash immediately. 

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by khotaonickvai** [comment]
![image](https://github.com/LavaGang/MelonLoader/assets/49309014/f2350f69-234d-474a-a37f-a1fc69a03fb9)

**Comment by HerpDerpinstine** [comment]
Please actually attach the log file as well with your support request.
This looks to be an issue with possibly an anti-virus or something.
However because you didn't include the log file I have no way of knowing what went wrong.
