### ISSUE TITLE
[Bug]: Assertion: schould not be reached at .. \mono\mini\tramp-amd64.c : 229

### ISSUE THREAD

**Issue by Eywa69** [LavaGang/MelonLoader#680]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

So after a while i wanted to play boneworks again. So bc i wanted to play with some mods and a friend i installed Melonloader, Bonelib, Fusion and a Ragedoll mod. But when i try to start the game i get "Assertion: schould not be reached at .. \mono\mini\tramp-amd64.c : 229". I couldnt find a fix yet.

https://github.com/LavaGang/MelonLoader/assets/173852667/b77bc73b-bba8-489e-a4b7-2ecf106ec517

### Did you attach your log file?

Select an option below

**Comment by SamboyCoding** [comment]
BONELAB modding community is using melonloader 0.6.1 now for this reason

**Comment by Eywa69** [comment]
> BONELAB modding community is using melonloader 0.6.1 now for this reason

now this happens

https://github.com/LavaGang/MelonLoader/assets/173852667/051b274d-09bd-4e0e-a838-026954d80678

**Comment by TrevTV** [comment]
Most mods aren't yet updated for use with patch 4 or MelonLoader 0.6+, you'll have to wait for them to be updated or downgrade to patch 3 and ML 0.5.7
