### ISSUE TITLE
[Bug] Failed to download Cpp2IL

### ISSUE THREAD

**Issue by RebelHvHProWoW** [LavaGang/MelonLoader#689]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.
i tried to use melonloader 0.6.0 and it said "failed to download cpp2il". i download the cpp2il netframework zip thing and put it in C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator
opened btd6 and got same error

[log file](https://github.com/LavaGang/MelonLoader/files/11032462/Latest.log)

Did you attach your log file?
Yes, I attached my log file to the text box above.
No, I could not find a log file at {Game_Directory}\MelonLoader\Latest.log

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
That game requires you install at least MelonLoader v0.6.1
