### ISSUE TITLE
[Bug]: I use MelonLoader with the CinematicUnityExplorer mod on the GoreBox game.

### ISSUE THREAD

**Issue by DefysT** [LavaGang/MelonLoader#695]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/16264896/Latest.log)
**I used MelonLoader 0.6.4 with the CinematicUnityExplorer mod on the GoreBox game, But when launching MelonLoader, the error "Failed to donwload cpp2il" appeared
As a result, I tried a lot of things:
I disabled the proxy, dug into regedit and disabled SSL, Installed all the libraries, reinstalled the game, melonloader and mod. I tried to install cpp2il manually and installed it via an exe file. But there was always the error "Failed to donwload cpp2il"
Please help me fix this!
MelonLoader was used with the mod to play with the game settings.**

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
The disabling of SSL is what is causing the issue.
Also it looks like you moved a bunch of files everywhere that they shouldn't be.
I would recommend re-enabling SSL then manually cleaning out all folders for MelonLoader and trying again.

**Comment by DefysT** [comment]
Okay, I'm just reinstall my windows and now melonloader working without any problem.

**Comment by DefysT** [comment]
Thank you guys.
