### ISSUE TITLE
getting red code lines when trying to load modded bloons

### ISSUE THREAD

**Issue by astroman1023** [LavaGang/MelonLoader#696]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

 i had mods working a month ago then i removed them to play with a friend and now its not working. when i am trying to load mods into bloons tower defence 6 after the cmd window says "loading in dll format for backwards compatibility" it gives out a couple lines of red code then it just loads into bloons normally, it says i have a modded game client but i have no mods.
[Latest.log](https://github.com/user-attachments/files/16315117/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by astroman1023** [comment]
here is the red code lines. 
![error code](https://github.com/user-attachments/assets/114880dd-2e84-46af-bc2b-fa871e381897)

**Comment by HerpDerpinstine** [comment]
This usually means you have another instance of the game running.
This can also happen if you tried closing the game while MelonLoader was still generating assemblies which causes Cpp2IL to stay running in the background.

**Comment by astroman1023** [comment]
what do i do to fix it

**Comment by HerpDerpinstine** [comment]
Reinstall MelonLoader then run the game and allow it to finish its generation process.

**Comment by astroman1023** [comment]
i have tried doing that a dozen times and it still hasn't worked

**Comment by HerpDerpinstine** [comment]
Then the only thing I can suggest is open Task Manager and make sure you don't have the game or Cpp2IL.exe running in the background.
After that try again.
I own BTD6 and its working fine for me.

**Comment by astroman1023** [comment]
it still isn't working

**Comment by HerpDerpinstine** [comment]
Do you have an Anti-Virus throwing a false positive on your MelonLoader files?

**Comment by astroman1023** [comment]
i have bit defender. i will check if it is stopping it

**Comment by astroman1023** [comment]
it said a file for melon loader was infected 

The file C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\cpp2il_out\UnityEngine.TextCoreTextEngineModule.dll is infected with Gen:Variant.Lazy.555227 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by HerpDerpinstine** [comment]
You should add an exception for your MelonLoader folder then reinstall MelonLoader and try again.
Some Anti-Viruses like to throw false positives about generated assemblies and will try to remove them even though they are harmless.

**Comment by astroman1023** [comment]
now its saying that it can't find the melon loader boot strap and i can't re install melon loader

**Comment by astroman1023** [comment]
> now its saying that it can't find the melon loader boot strap and i can't re install melon loader

its not doing that any more
