### ISSUE TITLE
[Bug]: BTD6 crashing when i try to use any mod with custom models

### ISSUE THREAD

**Issue by qwsadf** [LavaGang/MelonLoader#698]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

so when i instal mod like sun god village everything is fine, but when i try to place it game is just freezing and crashing
[Latest.log](https://github.com/user-attachments/files/16347526/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by qwsadf** [comment]
Forgot to mention that it happens with every mod with their own model

**Comment by rakosi2** [comment]
Don't use pirated versions of games.

**Comment by Watermelotech** [comment]
i have same issue but im using steam version :(
