### ISSUE TITLE
melon loader wont launch multiple instances. 

### ISSUE THREAD

**Issue by 64BitDev** [LavaGang/MelonLoader#700]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

version 6.0.3. was working in version 5.7.4. the game crashes before the start screen.
The game was Karlson 3d by Dani
[Latest.log](https://github.com/user-attachments/files/16367627/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
This issue is already resolved in the latest alpha-development nightly build for an upcoming v0.6.5 update.
