### ISSUE TITLE
[Bug]: I can't lauch the game (slime rancher 2)

### ISSUE THREAD

**Issue by Retroradiant** [LavaGang/MelonLoader#703]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Hello each try to lauch slime rancher 2 with mod it say to update .NET 6.0 and I don't know how please help
[Latest-Bootstrap.log](https://github.com/user-attachments/files/16430114/Latest-Bootstrap.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by KibblesTheKitten** [comment]
Use this installer to install .net: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.32-windows-x64-installer
