### ISSUE TITLE
[Bug]: The game crash before getting in the main menu (slime rancher 2)

### ISSUE THREAD

**Issue by Retroradiant** [LavaGang/MelonLoader#704]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Hello when I open the game, touch a button and try to go into the main menu, the game crash please help.
[Latest.log](https://github.com/user-attachments/files/16430650/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
This is a known issue with some MelonLoader versions on Slime Rancher 2.
Please retest this issue with MelonLoader v0.6.5.
