### ISSUE TITLE
BTD6 crashing when i try to use any mod with custom models

### ISSUE THREAD

**Issue by Watermelotech** [LavaGang/MelonLoader#706]
### All of the following criteria must be met

- [x] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [x] Changed the title so that it doesn't just says "[Bug]: "
- [x] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

Other mods are working, like ultimate crosspassing, but mods with custom models it instanly crashes when i try to place modded unit.
[Latest.log](https://github.com/user-attachments/files/16432647/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
This issue is already resolved.
For the time being please use MelonLoader v0.6.1 on BTD6.
