### ISSUE TITLE
[Bug]: MelonLoader gets error as game is starting up, whole thing closes and does not work.

### ISSUE THREAD

**Issue by Ihousmanssloves1** [LavaGang/MelonLoader#707]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/16444651/Latest.log)

It gets this error after those accuracy checks and some other few calls and then it closes a few seconds after it gets it: Process terminated. A callback was made on a garbage collected delegate of type 'EOS!MelonLoader.CompatibilityLayers.EOS_Module+LoadLibraryWDetour::Invoke'.                    I'm trying this on Among Us Vr, it works for my friend we got the same set up, the only difference is that he is on Windows 10 and I'm on Windows 11.  I've tried everything like reinstalling melon, the game, restarting my pc, turning off windows virus defender, EVERYTHING! I'm sad I can't fix it..

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
Should already be resolved on newer MelonLoader versions.
