### ISSUE TITLE
[Bug]: MelonLoader v0.5.7 not using  dotnet 6 while being installed

### ISSUE THREAD

**Issue by LordNetro** [LavaGang/MelonLoader#708]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.
I have all the dependency installed but when I try to run MelonLoader with mods, it won't launch.

[Latest.log](https://github.com/user-attachments/files/16501666/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by Atmudia** [comment]
MelonLoader 0.5.7 don't support net6 mods

**Comment by SamboyCoding** [comment]
^. Use 0.6.x for net6 support.
