### ISSUE TITLE
BoneLib doesnt work

### ISSUE THREAD

**Issue by droFruhtrA** [LavaGang/MelonLoader#711]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Crash]: added bonelib to melon loader 0.5.7 and whenever i dont have bonelib its fine but when i do my game crashes and the error says [20:01:28.308] [ERROR] System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'   at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)   at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) [0x00013] in <e1319b7195c343e79b385cd3aa43f5dc>:0   at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x00037] in <e1319b7195c343e79b385cd3aa43f5dc>:0   at System.Reflection.Assembly.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0   at System.Attribute.GetCustomAttributes (System.Reflection.Assembly element, System.Boolean inherit) [0x00014] in <e1319b7195c343e79b385cd3aa43f5dc>:0   at MelonLoader.MelonUtils.PullAttributesFromAssembly[T] (System.Reflection.Assembly asm, System.Boolean inherit) [0x00000] in <6425afb6ac6a429aaf770255d2f7de57>:0   at MelonLoader.MelonUtils.PullAttributeFromAssembly[T] (System.Reflection.Assembly asm, System.Boolean inherit) [0x00000] in <6425afb6ac6a429aaf770255d2f7de57>:0   at MelonLoader.MelonAssembly.LoadMelons () [0x0008c] in <6425afb6ac6a429aaf770255d2f7de57>:0   at MelonLoader.MelonHandler.LoadMelonsFromDirectory[T] (System.String path) [0x000aa] in <6425afb6ac6a429aaf770255d2f7de57>:0   at MelonLoader.Core.Initialize () [0x0006e] in <6425afb6ac6a429aaf770255d2f7de57>:0
[Latest.log](https://github.com/user-attachments/files/16554275/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by galacticatron** [comment]
do you have mcafee
