### ISSUE TITLE
[Bug]: BTD6 Crash on Startup

### ISSUE THREAD

**Issue by STEEPERCREVE** [LavaGang/MelonLoader#724]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Not sure exactly how to describe it, just gets through loading most of the mods and then has an error at the end. It works with minimal mods, but I've gone through and deleted to test which mod is causing it and none of them being removed stops it. Not sure why. Also I've attached the log file but it does not show the error. I will also attach a screenshot I was able to take before the console crashed. My only guess is that some mod is causing this and is looking for a version of the modhelper file that doesn't exist but I cant seem to find anything in the log file.

edit: the screenshot shows me using 0.6.1 as thats what the official modding site says, but I also tried using newers versions after looking through errors others got on this github issues center!
[Latest.log](https://github.com/user-attachments/files/16652839/Latest.log)
![Screenshot 2024-08-18 162247](https://github.com/user-attachments/assets/a555e7d8-4a70-4567-aaed-cb399c0babfa)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by KibblesTheKitten** [comment]
Several of your mods are outdated and you are also on the wrong melon loader version. Please downgrade to melon 0.6.1 by unticking latest in the installer then selecting 0.6.1, then click downgrade. After that remove most of your mods as only modhelper, faster forward, ascended upgrades, ultimate crosspath and maybe better ultravision is safe. But the rest is all outdated.

**Comment by HerpDerpinstine** [comment]
Fixed in the upcoming MelonLoader v0.6.5 update
