### ISSUE TITLE
[Bug]: monodirector loading error

### ISSUE THREAD

**Issue by 256noname256** [LavaGang/MelonLoader#729]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [x] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/16824919/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
Not an ML issue, MonoDirector isn't updated for ML 0.6+ (nor is JeviLib to my knowledge)

**Comment by extraes** [comment]
can confirm jevilib is not updated for 0.6 i havent released an update/pushed to the repo in like a year loool
