### ISSUE TITLE
[Bug]: Hard Bullet crashs, then mods installed

### ISSUE THREAD

**Issue by Tino672** [LavaGang/MelonLoader#735]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Then I launching Hard Bullet, with any mod installed, melon loader command prompt starts and crashs. Without mods game launching. Then any mod installed(for example HBMF mod), this issue appears: Failed to load all types in assembly HBMF, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null due to: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.

I installed Desktop Runtime 6.0.0, but log has this issue: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
![Screenshot 2024-09-04 213906](https://github.com/user-attachments/assets/535e9020-8d49-4c8c-9b65-d3bf7df4286f)

I tried to start the game with different melon loader versions, but that didn't helped. Currently the 0.6.4 version installed.

[Latest.log](https://github.com/user-attachments/files/16875160/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
According to MelonLoader you are on an older version of the game.
There also appears to possibly be additional files somewhere that makes it detect as MonoBleedingEdge instead of the intended Il2Cpp.

I recommend cleaning out the game folder manually by going to it and deleting the files yourself.
After that have Steam reinstall the latest build and reinstall MelonLoader using the official installer.
It should hopefully work after that.

**Comment by Tino672** [comment]
Thanks, I'll try it

**Comment by Tino672** [comment]
Thank you again. The game now launching fine
