### ISSUE TITLE
[Bug]:  Some Melons are missing dependencies

### ISSUE THREAD

**Issue by Ahmedaltaib** [LavaGang/MelonLoader#743]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

**Fusion lab mod for Bonelab is not working.**

[Latest.log](https://github.com/user-attachments/files/17001671/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by psyellas** [comment]
not a melonloader issue, you are on the wrong mod versions for your patch (you have patch 3, mods are for 6)

**Comment by Ahmedaltaib** [comment]
Thank you so much.
