### ISSUE TITLE
[Security]: Is melonloader.net an official website?

### ISSUE THREAD

**Issue by K0-RR** [LavaGang/MelonLoader#744]
### Describe the new feature or enhancement

I don't see https://melonloader.net/ mentioned anywhere in this repository.

**Comment by KibblesTheKitten** [comment]
The website is filed with AI generated sludge. A takedown request was sent in but sadly it was ignored.

**Comment by K0-RR** [comment]
Was it sent to Namecheap or Cloudflare? Both?

https://www.whois.com/whois/melonloader.net

**Comment by HerpDerpinstine** [comment]
The website of .net is not official.
We have tried multiple times to get in contact with someone that could either help us get it taken down or put us in contact with the page's creator.
All attempts so far have been ignored.

That being said the only official websites are https://melonwiki.xyz/ and https://melonloader.com/
