### ISSUE TITLE
[Bug]: its not working

### ISSUE THREAD

**Issue by Bloonhero3201** [LavaGang/MelonLoader#745]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

when i try to load btd6 with melon loader on my steam deck it just doesnt do anything, no command line looking thing or game (yes i have dotnet 6 installed)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
If I understand correctly, with MelonLoader installed game doesn't load but without it game loads?

**Comment by Bloonhero3201** [comment]
yes

**Comment by HerpDerpinstine** [comment]
This is a known issue with newer MelonLoader versions on BTD6.
We are working on fixing the issues.
For now we recommend people revert to using MelonLoader v0.6.1 for the time being.

**Comment by Bloonhero3201** [comment]
i tried 0.6.1 but it just wont open the console window thing

**Comment by rakosi2** [comment]
Have you tried nightly?

**Comment by HerpDerpinstine** [comment]
BTD6 just updated and now you need to be using at least v0.6.5 or higher.
Closing this as we have confirmed the original issue posted is resolved.

**Comment by Bloonhero3201** [comment]
now its saying an item with the same key has already been added key:infinite
