### ISSUE TITLE
[Enhancement]: Update NuGet package

### ISSUE THREAD

**Issue by HAHOOS** [LavaGang/MelonLoader#756]
### Describe the new feature or enhancement

With the release of MelonLoader v0.6.5, the NuGet package was not updated which can be an issue for modders depending on it. If possible, can the NuGet package please be updated to be up-to-date

**Comment by HerpDerpinstine** [comment]
I completely forgot about updating NuGet yesterday.
I have gone ahead and uploaded the new package.
Might take an hour or more for NuGet to verify it and it should be ready for use after that.

**Comment by HerpDerpinstine** [comment]
> I completely forgot about updating NuGet yesterday. I have gone ahead and uploaded the new package. Might take an hour or more for NuGet to verify it and it should be ready for use after that.

Just as I pressed the Comment button it finished verification lol
Should be usable now

**Comment by HAHOOS** [comment]
> Just as I pressed the Comment button it finished verification lol 
> Should be usable now

Alright, thank you and I appreciate the fast response!
