### ISSUE TITLE
[Bug]: Devour "failed to download Cpp2IL"

### ISSUE THREAD

**Issue by nooblolerxd** [LavaGang/MelonLoader#757]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[24-9-29_18-48-13.log](https://github.com/user-attachments/files/17179845/24-9-29_18-48-13.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by moranmateo** [comment]
i have the same problem

**Comment by HerpDerpinstine** [comment]
This was a bug that was introduced with the latest MelonLoader release of v0.6.5 and how it interfaces with our API.
We have gone ahead and fixed the issue for DEVOUR.
Should be working again after reinstalling MelonLoader.
