### ISSUE TITLE
Failed Load Library

### ISSUE THREAD

**Issue by Joaorafael0012** [LavaGang/MelonLoader#758]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest-Bootstrap.log](https://github.com/user-attachments/files/17194305/Latest-Bootstrap.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by matheusgamerXdc** [comment]
aaaaaaaaaaaaaaaaaa

**Comment by matheusgamerXdc** [comment]
idk bro
sory

**Comment by HerpDerpinstine** [comment]
This usually means you have missing files.
The only thing I can recommend is reinstalling MelonLoader.
