### ISSUE TITLE
[Bug]: The encryption of global-metadata.dat prevents the game from opening normally 

### ISSUE THREAD

**Issue by ShadowBearKill** [LavaGang/MelonLoader#760]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

When opening the game, the terminal of MelonLoader will display "waiting for you to press enter - feel free to copy the error..." and then get stuck. Pressing the enter key does not have any effect. At this time, MelonLoader will display "Initialization - Checking GameAssembly" in the game window.

[Latest.log](https://github.com/user-attachments/files/17213092/Latest.log)

I suspect that this is due to the encryption of "global-metadata.dat". Now that I know the decrypted "global-metadata.dat" of this game, is there a way to successfully open the game?

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by nitrog0d** [comment]
Girl's Frontline 2 has encrypted metadata (and we will not help you decrypt it), MelonLoader & other mod loaders will not work out of the box, also obviously they don't like people modding their games, you're on your own 😁

**Comment by ShadowBearKill** [comment]
I've decrypted the metadata successfully, and now I just want to know how to apply it to IL2CPP in melonloader, it's been bothering me for a while.😥
