### ISSUE TITLE
[Enhancement]: Safeness Of MelonLoader?

### ISSUE THREAD

**Issue by CoolPuppyKid** [LavaGang/MelonLoader#761]
### Describe the new feature or enhancement

**Im not trying to put a bad image on melonloader i love the software**

ok so i was gonna install melon loader then i check it for virus`s before i run it just like i do with anything else and this is what it gave me

![Screenshot 2024-10-02 214038](https://github.com/user-attachments/assets/32940d63-84a8-456c-ad36-bb82ce286c86)

**Comment by beanscat1** [comment]
its safe its not malware and it makes connections to unpack it VIA the installer Its no issue I use ML everyday

**Comment by CoolPuppyKid** [comment]
> its save its not malware and it makes connections to unpack it VIA the installer Its no issue I use ML everyday

i meant the read specifically the ones under Pe resource parents

**Comment by Atmudia** [comment]
I hope you know that the MelonLoader and MelonInstaller code is public, so you can simply check it out

**Comment by KibblesTheKitten** [comment]
> > its save its not malware and it makes connections to unpack it VIA the installer Its no issue I use ML everyday
> 
> i meant the read specifically the ones under Pe resource parents

The only reason many things flag melon loader and the installer as a virus is that it does a few things: 
- connect to the internet
- download it's own packages (Cpp2il, unity dependencies, game dependencies)
- create files
- re create files if needed.

**Comment by CoolPuppyKid** [comment]
> I hope you know that the MelonLoader and MelonInstaller code is public, so you can simply check it out

im aware just seeing if anyone else has already looked at it

**Comment by CoolPuppyKid** [comment]
> > > its save its not malware and it makes connections to unpack it VIA the installer Its no issue I use ML everyday
> > 
> > 
> > i meant the read specifically the ones under Pe resource parents
> 
> The only reason many things flag melon loader and the installer as a virus is that it does a few things:
> 
> * connect to the internet
> * download it's own packages (Cpp2il, unity dependencies, game dependencies)
> * create files
> * re create files if needed.

thank you
