### ISSUE TITLE
[Bug]: Unknown error

### ISSUE THREAD

**Issue by alina-yejin** [LavaGang/MelonLoader#762]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

![error](https://github.com/user-attachments/assets/52b06c7d-57cf-4c69-9b88-02256c076266)
I am using melonloader for The Long Dark, but I am encountering this error. Is it a problem with the mods? I don't understand what the problem is. The mod was working before and I was entering the game

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by beanscat1** [comment]
the longdark uses 0.6.1
