### ISSUE TITLE
[Bug]: UserData and Plugins Is empty upon using the automated installer

### ISSUE THREAD

**Issue by wbaigbawgwa** [LavaGang/MelonLoader#763]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I do not get any logs when i run the game, nor do I see a loading screen, on top of that, i do not even have a latest.log file. I think the reason mods do not work for me is because when I install melon loader through the automated way, the UserData and Plugins is empty, which means that the loading screen does not work and maybe the code does not run properly. And when i install it manually and run the game, the files never appear so that does not work either.
![Screenshot 2024-10-04 174700](https://github.com/user-attachments/assets/fa7f93e9-334f-439c-a9e0-182cfe3b4a8f)
![Screenshot 2024-10-04 174647](https://github.com/user-attachments/assets/aed387b0-7b24-4354-81ca-fc00f40ca9c9)
![Screenshot 2024-10-04 174640](https://github.com/user-attachments/assets/6e89c6c2-9224-4f29-9d08-d7f5cef63ce4)
![Screenshot 2024-10-04 174632](https://github.com/user-attachments/assets/7d0c423b-3668-4de5-a8a3-7abe81f020ef)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by wbaigbawgwa** [comment]
Just want to mention that i do not know what you mean by "was able to see the start screen"

**Comment by HerpDerpinstine** [comment]
You are using the wrong MelonLoader version.
That community and mod is using v0.6.1 as the [BTD6ModHelper](https://gurrenm3.github.io/BTD-Mod-Helper/wiki/Install-Guide) guide says.
``Note: Currently, MelonLoader v0.6.1 is the specific version you should use.``

**Comment by wbaigbawgwa** [comment]
I have already tried using it in version 0.6.1 and 0.6.0 using the automated installer, they both do not work and the UserData file is still empty

**Comment by wbaigbawgwa** [comment]
![image_2024-10-05_130810038](https://github.com/user-attachments/assets/6ce26020-7649-4ed8-8611-89c34e49a378)

**Comment by wbaigbawgwa** [comment]
Neither the manual or automated installer works, infact, the automated installer just instantly puts UserData, Plugins and Mods in the folder, and they are all empty.

**Comment by AlphaLovesYou** [comment]
user data being empty on fresh install is normal. 
please make sure that you have all the dependencies of melon loader. 
also make sure that you use 0.6.1 as that is the version used for BTD6
