### ISSUE TITLE
[Bug]: Melon Loader crashes Bonelab after waiting 10-15m for it to load

### ISSUE THREAD

**Issue by ghost** [LavaGang/MelonLoader#765]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

I'm on Quest and every time I patch Bonelab it just puts me in the 3 dot waiting screen. After 10m it just crashes and if I check my notifications it says "Not enough memory to run Bonelab". I've copied the OBB's and put them back in, everything. Nothing works.

Thanks

### Did you attach your log file?

Select an option below

**Comment by HerpDerpinstine** [comment]
I would suggest reposting this on https://github.com/LemonLoader/MelonLoader/issues

**Comment by ghost** [comment]
Bruh I was in the wrong repository the whole time lol
