### ISSUE TITLE
BTD 6 wont load

### ISSUE THREAD

**Issue by TooCalmForYou** [LavaGang/MelonLoader#769]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Was working fine yesterday, not the game is invisible and won't load. Says that it is waiting for me to press enter but that is not doing anything.
[Latest.log](https://github.com/user-attachments/files/17320272/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by beanscat1** [comment]
try nightly https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development

**Comment by TooCalmForYou** [comment]
Didn't fix anything, same error message
[Latest.log](https://github.com/user-attachments/files/17320319/Latest.log)

**Comment by beanscat1** [comment]
uninstall melonloader Remove the MelonLoader, Mods, Plugins, UserData, UserLibs folders as well as dobby.dll, notice.txt and version.dll. then reinstall 0.6.5

**Comment by TooCalmForYou** [comment]
Works great, thanks

**Comment by RandomDumbassyea** [comment]
helped me too thanks
