### ISSUE TITLE
BTD6 doesn't boot up

### ISSUE THREAD

**Issue by JustVibe4994** [LavaGang/MelonLoader#770]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/17346140/Latest.log)
So idk what is happening but all i can say that it shows the cmd window writes a few lines and then crashes

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by JustVibe4994** [comment]
this happend after the btd6 uptdate btw
i had melonloader before but after the update the thing i described happend and somehow BTD6.exe disappeared after that i had to reinstall everything

**Comment by JustVibe4994** [comment]
[NewEntryPoint] Caught exception invoking Initialize! System.TypeInitializationException: The type initializer for 'HarmonyLib.Harmony' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'
   at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.Install()
   at HarmonyLib.Harmony..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.Harmony..ctor(String id)
   at MelonLoader.Core.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 80
   at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\MelonLoaderInvoker.cs:line 10
   at MelonLoader.NativeHost.NativeEntryPoint.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 43

those are the lines it writes before crashing

**Comment by HerpDerpinstine** [comment]
Duplicate issue for https://github.com/LavaGang/MelonLoader/issues/769

**Comment by JustVibe4994** [comment]
Now it doesn't load mods or rather modloader

**Comment by JustVibe4994** [comment]
now it loads the mods but the game crashes as soon as the booting is finished
