### ISSUE TITLE
[Bug]: led keyboard application

### ISSUE THREAD

**Issue by panjabrajawat** [LavaGang/MelonLoader#775]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

![Screenshot (1)](https://github.com/user-attachments/assets/1a04cb1c-29c9-4d9b-ae19-f8ec5aa3d818)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by beanscat1** [comment]
what did you even open up???
