### ISSUE TITLE
[Bug]: Il2CppNinjaKiwi.LiNK.Aot Missing from Il2CppAssemblies folder

### ISSUE THREAD

**Issue by General-MUTT** [LavaGang/MelonLoader#776]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Trying to use the Trophy Store Item Unlocker Mod. The log says that it is missing the dependency Il2CppNinjaKiwi.LiNK.Aot v48.1.2.0 
[Latest.log](https://github.com/user-attachments/files/17442679/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
BTD6 just recently had a game update.
You need to update your ML install to v0.6.5 or higher.
You also need to update your mods.
