### ISSUE TITLE
[Bug]: opens the cmd prompt and runs for a while then if you click it opens the game on a white screen and crashes 

### ISSUE THREAD

**Issue by Legs02** [LavaGang/MelonLoader#777]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

 opens the cmd prompt and runs for a while then if you click it opens the game on a white screen and crashes 

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
I love "the game"
