### ISSUE TITLE
[Bug]: Start Screen crashes GPU drivers

### ISSUE THREAD

**Issue by Lillious** [LavaGang/MelonLoader#780]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Graphics card: Radeon 6600 (Latest drivers)
Version: v0.6.4 (Affects all versions that use the start screen by default)

**Issue Description:**
Melonloader start screen can cause a fresh Melonloader install to crash the graphics card driver.

**Details:**
Task Manager shows an immediate 100% GPU spike when the game is about to start.
Melonloader debug flag logs are not relevant to issue.

**Windows Event Viewer Logs:**
```
[Graphics Driver Crash]
CoreCLR Version: 6.0.3524.45918
.NET Version: 6.0.35
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFC16E1E38B
Stack:
Display driver amduw23g stopped responding and has successfully recovered.

[Memory Access Violation]
Faulting application name: ***.exe, version: 2020.3.42.56850, time stamp: 0x636cd0db
Faulting module name: UnityPlayer.dll, version: 2020.3.42.56850, time stamp: 0x636cd287
Exception code: 0xc0000005
```

**Temp Resolution:** 
Using flag --melonloader.disablestartscreen fixed the issue. (This fix was not immediately apparent at the time and took 3 hours of troubleshooting)

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by HerpDerpinstine** [comment]
Latest alpha-development nightly versions have the Start Screen temporarily removed so this should already be resolved.
