### ISSUE TITLE
 when loading BTD6 it just crashes

### ISSUE THREAD

**Issue by carcar14p** [LavaGang/MelonLoader#781]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

 I was installing mods for BTD6 and on start up it just does a bunch of random things then just crashes

[24-10-30_19-29-6.log](https://github.com/user-attachments/files/17580055/24-10-30_19-29-6.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by beanscat1** [comment]
What anti virus do you have?

**Comment by carcar14p** [comment]
window defender

**Comment by HerpDerpinstine** [comment]
This is most likely either an issue with some mod you are using or your anti-virus is false flagging files.
I can't reproduce the issue on my game.
