### ISSUE TITLE
[Bug]: Melonloader boots well but then proceeds to launch in an infinite string of errors

### ISSUE THREAD

**Issue by Abibas0** [LavaGang/MelonLoader#785]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Melonloader starts working but then just spits out the same thing and crashes (I'm using Bonelib, Ragdoll Player, and Ragdoll View)  

[Latest.log](https://github.com/user-attachments/files/17637487/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by psyellas** [comment]
this isnt a melonloader issue, you're using the latest version of bonelib (patch 6) while being on patch 3, ask in the official bonelab server for more support: https://discord.gg/mjmpUR8
