### ISSUE TITLE
[Bug]: Command Line Arguments not working as expected

### ISSUE THREAD

**Issue by HAHOOS** [LavaGang/MelonLoader#786]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Hi! I've been attempting to create a mod for BONELAB that mainly works on command line arguments, but I have noticed a bug. If you input for example `--bonelab.ovewritelevel [something here]`, it will add 2 items to the External Arguments directory with no values, and if you input `--bonelab.overwritelevel=[something here]` then it sets the key as `bonelab.overwritelevel` and the value is `null`. I have tried other things like `--bonelab.overwritelevel -[something here]` to see if anything works but nothing seems to. I am not sure if internal arguments are also impacted by this.

I have attempted to edit the code and try to find the cause, but ultimately I was unable to test the new changes due to mismatching versions of certain dependencies which I wasn't quick sure how to update (wasn't sure where to find the new version), so that's why I'm creating this issue.

I have attached a log file below, the plugin `BoneLineArguments` wrote the key and values it found while checking when its `--bonelab.overwritelevel Rooftops` and there were 2 keys, no values:

[Latest.log](https://github.com/user-attachments/files/17651482/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
Is this issue still occurring on latest nightly?
There was recently some changes to launch argument parsing.
