### ISSUE TITLE
[Bug]: Unhollower missing in latest 6.x.x realeses 

### ISSUE THREAD

**Issue by Aleyzgit** [LavaGang/MelonLoader#788]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

im having the issue that unity explorer dosent work in the latest 6.x.x releases 

`System.IO.FileNotFoundException: Could not load file or assembly 'UnhollowerBaseLib`

and every link having the unhollower base lib dosent say how to do it or the link doesn't work

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by Atmudia** [comment]
Use this: https://github.com/GrahamKracker/UnityExplorer

**Comment by Aleyzgit** [comment]
> Use this: https://github.com/GrahamKracker/UnityExplorer

unhollower base lib is still missing
