### ISSUE TITLE
[Bug]: il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime. [18:42:03.232] [ERROR] il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime. 

### ISSUE THREAD

**Issue by NIKITARIKS** [LavaGang/MelonLoader#792]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

при запуске игры с melonloader (у меня это BONELAB) вылезает командная строка и ошибка
![image](https://github.com/user-attachments/assets/9454ba93-7b88-46d6-899d-34978894dc4d)

### Did you attach your log file?

Select an option below

**Comment by HerpDerpinstine** [comment]
You need to install the .NET 6.0 runtime just like the message says.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.36-windows-x64-installer

**Comment by NIKITARIKS** [comment]
I forgot to add that I have already downloaded NET 0.6.36 from this site
![image](https://github.com/user-attachments/assets/b54f6d9c-143f-473c-8e0f-1dbe0aa8703d)

**Comment by NIKITARIKS** [comment]
I downloaded the runtime specifically

**Comment by NIKITARIKS** [comment]
I somehow fixed myself...

**Comment by v0idx9** [comment]
how exactly did you fix it? having the same issue...
