### ISSUE TITLE
[Bug]: melon loader internal failure

### ISSUE THREAD

**Issue by Keylimetea** [LavaGang/MelonLoader#795]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

It says to upload a log file in which the log file says failure to read unity version from file info. It says app.info does not exist. What does this mean? 

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
I am marking this post as invalid.
Please provide the actual log file with your issue post.
