### ISSUE TITLE
[Bug]: BTD6 taking two hours to load up and just shows a black screen

### ISSUE THREAD

**Issue by Ari-Fudu** [LavaGang/MelonLoader#798]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/17965521/Latest.log)

Melonloader opens, starts and does everything else just fine, however, it takes two hours to even show the "Retargetting mods" screen and doesn't even open the game. It also gets stuck at "Writing Assemblies..." and "Writing method pointer map...", taking extremely long in every step. I play BTD6 on Version 45, and have had 65h of playtime pre-modded but just now installed a few utility mods.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by slxdy** [comment]
As for the il2cpp assembly generator, are you running a slow hard drive?
The mods part is unrelated here. You should ask in the [BTD modding community Discord](https://discord.gg/SeRH8xQ5mQ)

**Comment by Ari-Fudu** [comment]
sorry im not very tech savvy what exactly are you asking for? If you're asking for my pc's ram, it's about 1.5GB usable ram.

**Comment by slxdy** [comment]
Just ask for help in that community

**Comment by Ari-Fudu** [comment]
I don't use discord TvT,, i understand if mods are not the problem but then what is it that i am doing wrong

**Comment by slxdy** [comment]
No. Mods ARE the problem, so we can't help with that

**Comment by Ari-Fudu** [comment]
are you positive there's no other fix for this il2cpp thing?

**Comment by slxdy** [comment]
The "il2cpp thing" is caused by slow hardware, which does not contribute to the crash. The crash is caused by one of your mods, which we have no control over.
