### ISSUE TITLE
[Bug]:btd6 wont open after melonloader loads

### ISSUE THREAD

**Issue by hiyyyme** [LavaGang/MelonLoader#799]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

when i try opening btd6 it doesnt open the start menu, it opens melon loader but the btd6 game itself is just blank, not black but blank so that i can see what i have open, yes i tried pressing enter but nothing happened
[Latest.log](https://github.com/user-attachments/files/18080471/Latest.log)

### Did you attach your log file?

Select an option below

Yes. I put the log file into the text above.

**Comment by SamboyCoding** [comment]
Update to MelonLoader 0.6.6

**Comment by hiyyyme** [comment]
> Update to MelonLoader 0.6.6

Doesnt work, if i do so it doesnt even open without crashing
