### ISSUE TITLE
[Bug]: MelonLoader still wont launch

### ISSUE THREAD

**Issue by greeeeeens** [LavaGang/MelonLoader#800]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Hi, i have issues with runnning Bloons TD6. I have installed everything needed, but MelonLoader still wont load.
Currently, it's running on Windows 11 with ARM. Does that have to do with it not working?
[Latest-Bootstrap.log](https://github.com/user-attachments/files/18091979/Latest-Bootstrap.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by slxdy** [comment]
Hm. If you're on an ARM laptop, I'm assuming it's running the game through a compatibility layer. You should try installing [the x64 version of the .net 6 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.36-windows-x64-installer)

**Comment by slxdy** [comment]
MelonLoader hasn't been tested on the ARM compatibility layer yet, so feel free to report any additional issues.

**Comment by greeeeeens** [comment]
> Hm. If you're on an ARM laptop, I'm assuming it's running the game through a compatibility layer. You should try installing [the x64 version of the .net 6 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.36-windows-x64-installer)

Ok, MelonLoader works properly now. Thanks for your help!
Edit: It does work, but please note that it can be slow, so have som patience!
