### ISSUE TITLE
[Bug]: Can't update melonloader to 0.6.6 version

### ISSUE THREAD

**Issue by poulpisator81** [LavaGang/MelonLoader#801]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[24-12-12_9-22-42.log](https://github.com/user-attachments/files/18108096/24-12-12_9-22-42.log)
UPgrade from 0.6.0  to 0.6.6 dont work. Have a  pop up "failed to excecute cpp2IL"

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by slxdy** [comment]
Please run with the `--melonloader.debug` launch argument, wait for the crash and send the new log

**Comment by poulpisator81** [comment]
> Please run with the `--melonloader.debug` launch argument, wait for the crash and send the new log

how i do that? i dont find any file debug  on my melonloader installed.  someone can  tell me please ?

**Comment by slxdy** [comment]
Open your steam library, right click your game and go to Properties. Copy `--melonloader.debug` into the empty field and rerun the game.
![image](https://github.com/user-attachments/assets/ea3679db-dd81-4948-ac0f-0cd8b7c5f962)

**Comment by poulpisator81** [comment]
[24-12-13_14-15-14.log](https://github.com/user-attachments/files/18126757/24-12-13_14-15-14.log)

there the log with debug launch

**Comment by poulpisator81** [comment]
[Latest-Bootstrap.log](https://github.com/user-attachments/files/18126770/Latest-Bootstrap.log)
[Latest.log](https://github.com/user-attachments/files/18126773/Latest.log)

**Comment by poulpisator81** [comment]
only 0.6.1 version of melonloader can launch the  game, after its not working

**Comment by poulpisator81** [comment]
yep, nobody to help  me ?
please help

**Comment by poulpisator81** [comment]
it was  my firewall blocked some files
