### ISSUE TITLE
[Bug]: cant grab things

### ISSUE THREAD

**Issue by S4mp1Redox** [LavaGang/MelonLoader#803]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

cant grab almost all of my modded things 

### Did you attach your log file?

Select an option below

**Comment by KibblesTheKitten** [comment]
Attach the Latest.log file from inside of the melon loader folder!!

**Comment by TrevTV** [comment]
Likely unrelated to MelonLoader, their other issue was for BONELAB, and ML has nothing to do with loading item mods for the game.

**Comment by slxdy** [comment]
> Attach the Latest.log file from inside of the melon loader folder!!

Issues unrelated to MelonLoader should be closed. Mod questions/issues should be reported to the appropriate community.

**Comment by S4mp1Redox** [comment]
IDK if it was ml fault or not

**Comment by S4mp1Redox** [comment]
> Attach the Latest.log file from inside of the melon loader folder!!

how ? im pretty new

**Comment by slxdy** [comment]
Please report your issue in the Bonelab discord server. We do not provide support for mods.
