### ISSUE TITLE
[Bug]: Slime rancher 2 does not start with melon loader higher than 0.6.4

### ISSUE THREAD

**Issue by NahName171** [LavaGang/MelonLoader#805]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I'll say right away that I'm writing through a translator, so forgive me for the mistakes in the text. After a recent update in SR2, the game began to crash due to the Melon loader version higher than 0.6.4. Please help me with this problem, and I will attach the log file (if it helps)

[Latest.log](https://github.com/user-attachments/files/18140690/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by KibblesTheKitten** [comment]
This is know. A fix isninnthe works. For now mods are trying to be updated too to be compatible wirh melon 0.6.4
