### ISSUE TITLE
[Bug]: Can't use AddComponent in IL2CPP

### ISSUE THREAD

**Issue by cudadotsln** [LavaGang/MelonLoader#813]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Hello! I have recently been getting a bug whenever I use IL2CPP. Whenever I use AddComponent, it gives no errors in visual studio, but gives me an error in the console, and won't add the component. (THE BLURRED PARTS DONT NEED TO BE WORRIED ABOUT)
(errors loop bc i put a check in update)
![image](https://github.com/user-attachments/assets/c2538489-d07e-4bb0-b623-37e7c66359ae)
[Latest.log](https://github.com/user-attachments/files/18233484/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by Atmudia** [comment]
Please use wiki. You need to register class with ClassInjector

**Comment by cudadotsln** [comment]
Works now! Thank you :)
