### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lon1xcyberspor** [LavaGang/MelonLoader#818]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[LogOutput.log](https://github.com/user-attachments/files/18274590/LogOutput.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by SamboyCoding** [comment]
First, this is a log from bepinex, not melonloader. 
Secondly, this is not a bug in the loader anyway, but in the Console Unlocker mod.

**Comment by slxdy** [comment]
Error!
