### ISSUE TITLE
Cleanup Managed Folder

### ISSUE THREAD

**Issue by HerpDerpinstine** [LavaGang/MelonLoader#95]
After: https://github.com/LavaGang/MelonLoader/issues/94

Mono Library included files can be moved from MelonLoader/Managed to its own Managed folder within the Mono Library Dependencies folder.
Keep all Il2Cpp Generated Assemblies within MelonLoader/Managed.

This will not only clean up the Managed folder but also prevent confusion from developers.
The library files are usually referenced and included from the .NET SDK by the IDE anyways instead of manually referencing from a Managed folder.

**Comment by ds5678** [comment]
I think this has been mostly solved by #345
