### ISSUE TITLE
Add Wine/Proton Usage Guide to README and Wiki

### ISSUE THREAD

**Issue by HerpDerpinstine** [LavaGang/MelonLoader#98]
The instructions for how to run a Game with MelonLoader under Wine or Steam Proton was posted on Discord.
They were written in the context of VRChat but they are the same no matter what Game it is.
Should probably state it in the README and Wiki.

_Image for Reference:_
<img src="https://i.imgur.com/0oZWKVo.png">

**Comment by gyroninja** [comment]
What I currently do is just put

>WINEDLLOVERRIDES="version=n,b" %command% --melonloader.hideconsole

In the launch options in steam. The dll override lets you load MelonLoader's vresion.dll and --melonloader.hideconsole avoids a problem with MelonLoader failing to start due to AllocConsole failing.

I didn't find it necessary to install dotnet separetely, so it might depend on the game.

**Comment by HerpDerpinstine** [comment]
> What I currently do is just put
> 
> > WINEDLLOVERRIDES="version=n,b" %command% --melonloader.hideconsole
> 
> In the launch options in steam. The dll override lets you load MelonLoader's vresion.dll and --melonloader.hideconsole avoids a problem with MelonLoader failing to start due to AllocConsole failing.
> 
> I didn't find it necessary to install dotnet separetely, so it might depend on the game.

What game did you try this on?

**Comment by gyroninja** [comment]
> What game did you try this on?

VTube Studio

**Comment by gyroninja** [comment]
By manually changing the version of Proton from 5.0-10 to Proton Experimental I found that AllocConsole no longer fails meaning that --melonloader.hideconsole is not necessary to get the game to start.

**Comment by HerpDerpinstine** [comment]
> By manually changing the version of Proton from 5.0-10 to Proton Experimental I found that AllocConsole no longer fails meaning that --melonloader.hideconsole is not necessary to get the game to start.

Must mean it actually was a Proton bug causing it to fail and they have it fixed in the Experimental branch.
None the less I appreciate you keeping us up to date on this. 😄

**Comment by slxdy** [comment]
Hasn't this been added already?

**Comment by HerpDerpinstine** [comment]
> Hasn't this been added already?

To the Wiki but not the Readme.
